(function(g){var window=this;'use strict';var my=function(C){C.publish("cardstatechange",C.oS()&&C.Fh()?1:0)},f1=function(C,b){var h=g.nW(b),N=h?b:arguments;
for(h=h?0:1;h<N.length;h++){if(C==null)return;C=C[N[h]]}return C},PBh=function(C){var b=g.Su(C);
C=g.Hc(C);return new g.pV(b.x,b.y,C.width,C.height)},jye=function(C,b,h){var N=N===void 0?{}:N;
var p;return p=g.Hj(C,b,function(){g.VJ(p);h.apply(C,arguments)},N)},rx=function(C){C=g.B1(C);
delete A6[C];g.A8(A6)&&yg&&yg.stop()},k5$=function(){yg||(yg=new g.wl(function(){c1d()},20));
var C=yg;C.isActive()||C.start()},c1d=function(){var C=g.Cd();
g.GA(A6,function(b){exC(b,C)});
g.A8(A6)||k5$()},iL=function(C,b,h,N){g.Zo.call(this);
if(!Array.isArray(C)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(C.length!=b.length)throw Error("Start and end points must be the same length");this.K=C;this.J=b;this.duration=h;this.G=N;this.coords=[];this.progress=this.W=0;this.X=null},exC=function(C,b){b<C.startTime&&(C.endTime=b+C.endTime-C.startTime,C.startTime=b);
C.progress=(b-C.startTime)/(C.endTime-C.startTime);C.progress>1&&(C.progress=1);C.W=1E3/(b-C.X);C.X=b;LRI(C,C.progress);C.progress==1?(C.j=0,rx(C),C.onFinish(),C.dg()):C.isPlaying()&&C.uC()},LRI=function(C,b){typeof C.G==="function"&&(b=C.G(b));
C.coords=Array(C.K.length);for(var h=0;h<C.K.length;h++)C.coords[h]=(C.J[h]-C.K[h])*b+C.K[h]},Zv0=function(C,b){g.un.call(this,C);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.W;this.state=b.j},J6=function(C,b,h,N,p){iL.call(this,b,h,N,p);
this.element=C},YQj=function(C,b,h,N,p){if(b.length!=2||h.length!=2)throw Error("Start and end points must be 2D");
J6.call(this,C,b,h,N,p)},aBh=function(C){return Math.pow(C,3)},lBD=function(C){return 3*C*C-2*C*C*C},oAd=function(C){g.O.call(this);
this.K=C||window;this.j=[]},uL=function(C){return C.baseUrl||null},RP=function(C,b){return g.kS(g.M_(C,b),function(h){return!!h})},FRp=function(C,b,h){function N(jV){var CW=jV.hovercardButton;
if(!CW)return null;CW=CW.subscribeButtonRenderer;if(!CW)return null;var W=P(CW.unsubscribedButtonText),w=P(CW.subscribedButtonText);if(CW.subscribed){var H=P(CW.subscriberCountWithUnsubscribeText);var E=P(CW.subscriberCountText)}else H=P(CW.subscriberCountText),E=P(CW.subscriberCountWithSubscribeText);var Ol=null;if(jV.signinEndpoint){Ol=f1(jV,"signinEndpoint","webNavigationEndpointData","url");if(!Ol){var H$,YI;Ol=(YI=g.d((H$=CW.signInEndpoint)==null?void 0:H$.commandMetadata,g.St))==null?void 0:
YI.url}if(!Ol)return null}return W&&(w||Ol)?{subscribed:CW.subscribed,subscribeText:W,subscribeCount:H,unsubscribeText:w,unsubscribeCount:E,enabled:CW.enabled,signinUrl:Ol,classic:jV.useClassicSubscribeButton}:null}
function p(jV){if(jV){var CW=[],W=jV.videoId;W&&CW.push("v="+W);(W=jV.playlistId)&&CW.push("list="+W);(jV=jV.startTimeSeconds)&&CW.push("t="+jV);return"/watch?"+CW.join("&")}}
function P(jV){if(!jV)return null;var CW=jV.simpleText;return CW?CW:jV.runs?g.M_(jV.runs,function(W){return W.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var c=b.style,e=b.endpoint||{},L=null,Z=null,Y=!1,a=null,l=null,F=null,G=null,V=!1,q=null,f=null,y=null,u=null,K=null,v=null;if(c==="VIDEO")g.d(e,g.QA)?L=g.d(e,g.QA).url:(v=g.d(e,g.Da),L=p(v)),Z=!1,a=C,b.thumbnailOverlays?(Y=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,l=P(Y.text),Y=Y.style==="LIVE"):l=P(b.videoDuration);else if(c==="PLAYLIST")g.d(e,g.QA)?L=g.d(e,g.QA).url:(v=g.d(e,g.Da),L=p(v)),Z=!1,a=C,F=P(b.playlistLength);else if(c===
"CHANNEL"){if(V=f1(e,"browseEndpoint","browseId"))G=V,L="/channel/"+G;Z=!1;a="new";(V=!!b.isSubscribe)?q=N(b):f=P(b.subscribersText)}else c==="WEBSITE"?((y=f1(e,"urlEndpoint","url"))&&(L=y),Z=!0,a="new",y=b.icon.thumbnails[0].url):c==="CREATOR_MERCHANDISE"&&(b.productPrice&&(u=P(b.productPrice)),b.additionalFeesText&&(K=P(b.additionalFeesText)),(Z=f1(e,"urlEndpoint","url"))&&(L=Z),Z=!0,a="new");C=f1(b,"title","accessibility","accessibilityData","label");var T=b.endpoint?b.endpoint.clickTrackingParams:
null,t="";if(b.metadata){var go=P(b.metadata);go&&(t=go)}return{id:"element-"+h,type:c,title:P(b.title),metadata:t,callToAction:P(b.callToAction),u8:b.image,iconUrl:y,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:l,Ls:Y,playlistLength:F,channelId:G,subscribeButton:q,subscribersText:f,isSubscribe:V,targetUrl:L||null,kiX:Z,sessionData:T?{itct:T}:null,JLX:a,PB:C?C:null,
isPlaceholder:b.isPlaceholder,impressionUrls:RP(b.impressionUrls||[],uL),hDf:RP(b.hovercardShowUrls||[],uL),clickUrls:RP(e.loggingUrls||[],uL),visualElement:g.HL(b.trackingParams),productPrice:u,additionalFeesText:K,watchEndpoint:v||null}},G50=function(C,b){var h={startMs:Math.floor(Number(C.startMs)),
impressionUrls:RP(C.impressionUrls||[],uL),elements:RP(C.elements||[],function(N,p){return FRp(b,N,p)})};
C.trackingParams&&(h.visualElement=g.HL(C.trackingParams));return h},SQE=function(C){g.qK.call(this,C);
this.X=this.endscreen=null;this.K={};this.W={};this.G=this.N=null;this.L=[];this.j=null;this.KO=!0;this.J=0;C=C.Y();this.V=g.qX(C)||g.fO(C);this.events=new g.Jm(this);g.D(this,this.events);this.events.S(this.player,g.gL("creatorendscreen"),this.onCueRangeEnter);this.events.S(this.player,g.p8("creatorendscreen"),this.onCueRangeExit);this.events.S(this.player,"resize",this.eC);this.events.S(window,"focus",this.ab6);this.load();var b=g.wk("STYLE");(g.vE("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.gQ(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},$0e=function(C){return C.player.getVideoData().jS?"current":C.V?"new":"current"},Qg=function(C){return C.player.Y().playerStyle==="creator-endscreen-editor"},zxh=function(C){var b=C.player.getVideoData(),h=b.videoId;
C.X&&C.X.abort();h={method:"POST",onFinish:function(p){var P=C.X=null;p.status===200&&(p=p.responseText,p.substring(0,3)===")]}"&&(p=p.substring(3),P=JSON.parse(p),P=G50(P,$0e(C))));UV(C,P)},
urlParams:{v:h},withCredentials:!0};C.V&&(h.urlParams.ptype="embedded");var N=b.Lw;N&&(h.postParams={ad_tracking:N});if(b=g.h6c(b))if(b=g.iq(b),b=g.AQ(b))C.X=g.mt(b,h)},UV=function(C,b,h){h=h===void 0?!0:h;
C.player.Sh("creatorendscreen");C.N&&(C.N.dispose(),C.N=null,C.G.dispose(),C.G=null);for(var N=g.z(Object.values(C.K)),p=N.next();!p.done;p=N.next())p.value.dispose();C.K={};C.W={};C.L.length>0&&(C.L.forEach(function(e){e.dispose()}),C.L.length=0);
C.j&&(g.kb(C.j,"ytp-ce-element-show"),C.j.setAttribute("aria-hidden","true"));C.J=0;if((C.endscreen=b)&&b.elements){h&&HvU(C);h=[];N=new g.hk(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});h.push(N);C.player.Y().K||(C.N=new g.n({B:"div",C:"ytp-ce-shadow"}),g.MC(C.player,C.N.element,4),C.G=new g.CF(C.N,200));for(N=0;N<b.elements.length;++N){p=b.elements[N];var P=VYC(C,p);if(P){C.K[p.id]=P;C.W[p.id]=p;g.MC(C.player,P.element,4);var c=new g.hk(p.startMs,p.endMs,{id:"ytp-ce-element-"+
p.id,namespace:"creatorendscreen"});h.push(c);MYE(C,P,p)}else g.Ri(new g.np("buildEndscreenElement null",p))}C.player.A8(h);C.eC()}},HvU=function(C){var b=g.M6(),h=g.q6();
h&&b&&C.endscreen.visualElement&&g.wW(g.nZ)(void 0,h,b,C.endscreen.visualElement)},VYC=function(C,b){var h=null;
switch(b.type){case "VIDEO":C={B:"div",J4:["ytp-ce-element","ytp-ce-video"],T:{tabindex:"0","aria-label":b.PB||"","aria-hidden":"true"},U:[{B:"div",C:"ytp-ce-element-shadow"},{B:"div",C:"ytp-ce-covering-image",T:XC(b)},{B:"div",C:"ytp-ce-covering-shadow-top"},{B:"a",C:"ytp-ce-covering-overlay",T:{href:K1(C,b.targetUrl),tabindex:"-1"},U:[{B:"div",J4:["ytp-ce-video-title","ytp-webkit-ellipsis"],T:{dir:g.FY(b.title||"")},BE:b.title},{B:"div",C:b.Ls?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
BE:b.videoDuration||void 0}]}]};h=new g.n(C);break;case "PLAYLIST":C={B:"div",J4:["ytp-ce-element","ytp-ce-playlist"],T:{tabindex:"0","aria-label":b.PB||"","aria-hidden":"true"},U:[{B:"div",C:"ytp-ce-element-shadow"},{B:"div",C:"ytp-ce-covering-image",T:XC(b)},{B:"div",C:"ytp-ce-covering-shadow-top"},{B:"a",C:"ytp-ce-covering-overlay",T:{href:K1(C,b.targetUrl),tabindex:"-1"},U:[{B:"div",J4:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],T:{dir:g.FY(b.title||"")},BE:b.title},{B:"div",C:"ytp-ce-playlist-count",
U:[{B:"div",C:"ytp-ce-playlist-icon"},{B:"div",C:"ytp-ce-playlist-count-text",BE:b.playlistLength||void 0}]}]}]};h=new g.n(C);break;case "CHANNEL":h={B:"div",J4:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],T:{tabindex:"0","aria-label":b.PB||"","aria-hidden":"true"},U:[{B:"div",C:"ytp-ce-element-shadow"},{B:"div",C:"ytp-ce-expanding-overlay",U:[{B:"div",C:"ytp-ce-expanding-overlay-hider"},{B:"div",C:"ytp-ce-expanding-overlay-background"},{B:"div",C:"ytp-ce-expanding-overlay-content",
U:[{B:"div",C:"ytp-ce-expanding-overlay-body",U:[{B:"div",C:"ytp-ce-expanding-overlay-body-padding",U:[{B:"a",J4:["ytp-ce-channel-title","ytp-ce-link"],T:{href:K1(C,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.FY(b.title||"")},BE:b.title},b.subscribeButton?{B:"div",C:"ytp-ce-subscribe-container",U:[{B:"div",C:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{B:"div",C:"ytp-ce-channel-subscribers-text",BE:b.subscribersText}:"",b.metadata?{B:"div",J4:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],BE:b.metadata}:""]}]}]}]},{B:"div",C:"ytp-ce-expanding-image",T:XC(b)}]};h=new g.n(h);var N=g.dk(document,"div","ytp-ce-channel-subscribe",h.element)[0];if(b.subscribeButton&&b.channelId){g.j6(N,"ytp-ce-subscribe-button");if(C.player.Y().K){var p=null;var P=b.sessionData.itct}else p="endscreen",P=null;p=new g.PH(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,p,P,C.player,!1);N.appendChild(p.element);C.L.push(p)}break;case "WEBSITE":C={B:"div",J4:["ytp-ce-element","ytp-ce-website"],T:{tabindex:"0","aria-label":b.PB||"","aria-hidden":"true"},U:[{B:"div",C:"ytp-ce-element-shadow"},{B:"div",C:"ytp-ce-expanding-overlay",U:[{B:"div",C:"ytp-ce-expanding-overlay-hider"},{B:"div",C:"ytp-ce-expanding-overlay-background"},{B:"div",C:"ytp-ce-expanding-overlay-content",U:[{B:"div",C:"ytp-ce-expanding-overlay-body",U:[{B:"div",
C:"ytp-ce-expanding-overlay-body-padding",U:[{B:"div",C:"ytp-ce-website-title",T:{dir:g.FY(b.title||"")},BE:b.title},{B:"div",C:"ytp-ce-website-metadata",BE:b.metadata},{B:"a",J4:["ytp-ce-website-goto","ytp-ce-link"],T:{href:K1(C,b.targetUrl),target:"_blank",tabindex:"-1"},BE:b.callToAction}]}]}]}]},{B:"div",C:"ytp-ce-expanding-image",T:XC(b)},{B:"div",C:"ytp-ce-expanding-icon",T:qQj(b.iconUrl)}]};h=new g.n(C);break;case "CREATOR_MERCHANDISE":h="",b.productPrice&&(h={B:"div",C:"ytp-ce-merchandise-price-container",
U:[{B:"div",C:"ytp-ce-merchandise-price",BE:b.productPrice}]},b.additionalFeesText&&h.U.push({B:"div",C:"ytp-ce-merchandise-additional-fees",BE:b.additionalFeesText})),C={B:"div",J4:["ytp-ce-element","ytp-ce-merchandise"],T:{tabindex:"0","aria-label":b.PB||"","aria-hidden":"true"},U:[{B:"div",C:"ytp-ce-element-shadow"},{B:"div",C:"ytp-ce-expanding-overlay",U:[{B:"div",C:"ytp-ce-expanding-overlay-hider"},{B:"div",C:"ytp-ce-expanding-overlay-background"},{B:"div",C:"ytp-ce-expanding-overlay-content",
U:[{B:"div",C:"ytp-ce-expanding-overlay-body",U:[{B:"div",C:"ytp-ce-expanding-overlay-body-padding",U:[{B:"div",C:"ytp-ce-merchandise-title",T:{dir:g.FY(b.title||"")},BE:b.title},h,{B:"div",C:"ytp-ce-merchandise-metadata",BE:b.metadata},{B:"a",J4:["ytp-ce-merchandise-goto","ytp-ce-link"],T:{href:K1(C,b.targetUrl),target:"_blank",tabindex:"-1"},BE:b.callToAction}]}]}]}]},{B:"div",C:"ytp-ce-expanding-image",T:XC(b)},{B:"div",C:"ytp-ce-merchandise-invideo-cta-container",U:[{B:"div",C:"ytp-ce-merchandise-invideo-cta",
BE:b.callToAction||void 0}]}]},h=new g.n(C)}b.isPlaceholder&&g.j6(h.element,"ytp-ce-placeholder");return h},XC=function(C){if(C.u8)var b=C.u8.thumbnails;
return qQj(b?b[b.length-1].url:null)},qQj=function(C){return C?{style:"background-image: url("+C+")"}:{}},MYE=function(C,b,h){function N(L){L&&(b.listen("blur",function(){L.style.display!="none"&&C.KO&&L.focus()}),b.S(L,"focus",P),b.S(L,"blur",c))}
function p(L){C.J+=L;C.J>0?(g.j6(b.element,"ytp-ce-force-expand"),sV(C,h.id,!0)):(g.kb(b.element,"ytp-ce-force-expand"),g.kb(b.element,"ytp-ce-element-hover"),sV(C,h.id,!1))}
function P(){p(1)}
function c(){p(-1)}
b.listen("mouseenter",function(){m0E(C,b,h)});
b.listen("mouseleave",function(){fBD(C,b,h)});
C.player.Y().K||b.listen("click",function(){g.j6(b.element,"ytp-ce-element-hover")});
b.listen("click",function(L){A1U(C,h,L)});
b.listen("keypress",function(L){A1U(C,h,L)});
b.listen("focus",function(){m0E(C,b,h)});
b.listen("blur",function(){fBD(C,b,h)});
b.listen("touchstart",function(){m0E(C,b,h)});
var e=g.WE("ytp-ce-expanding-overlay-hider",b.element);e&&b.S(e,"touchstart",function(L){L.stopPropagation();g.kb(b.element,"ytp-ce-element-hover");g.kb(b.element,"ytp-ce-force-expand")});
b.listen("keydown",function(L){C.KO=L.keyCode===9&&!L.shiftKey});
N(g.WE("ytp-sb-subscribe",b.element));N(g.WE("ytp-sb-unsubscribe",b.element));b.listen("focus",P);b.listen("blur",c)},A1U=function(C,b,h){if(b.targetUrl&&(!h||h.type!=="keypress"||h.keyCode===13)){for(var N=h.target;N&&!g.P4(N,"ytp-ce-element");){g.P4(N,"subscribe-label")&&y10(C,b);
if(g.P4(N,"ytp-ce-channel-subscribe"))return;N=N.parentElement||null}if(!N||g.P4(N,"ytp-ce-element-hover")){h.preventDefault();h.stopPropagation();if(N=C.K[b.id])fBD(C,N,b),N.element.blur();if(h.ctrlKey||h.metaKey||b.JLX==="new")y10(C,b),C.player.sendVideoStatsEngageEvent(17,void 0),C.player.pauseVideo(),h=g.iq(K1(C,b.targetUrl)),h=g.AQ(h),g.dG(h,void 0,b.sessionData);else{var p=g.Oa(C.player.Y())||C.player.getVideoData().jS,P=function(){var c=K1(C,b.targetUrl),e=b.sessionData,L=b.watchEndpoint,Z=
g.pN(c);p&&Z&&(Z.v||Z.list)?C.player.fk(Z.v,e,Z.list,!1,void 0,L||void 0):g.DK(c,e)};
y10(C,b,function(){C.player.sendVideoStatsEngageEvent(17,P)})}}}},K1=function(C,b){C=C.player.Y();
if(b){if(b.startsWith("//"))return C.protocol+":"+b;if(b.startsWith("/"))return g.t9(C)+b}else return"";return b},m0E=function(C,b,h){g.P4(b.element,"ytp-ce-element-hover")||(h.type==="VIDEO"||h.type==="PLAYLIST"?g.j6(b.element,"ytp-ce-element-hover"):C.player.Y().K?(new g.wl(function(){g.j6(b.element,"ytp-ce-element-hover")},200)).start():g.j6(b.element,"ytp-ce-element-hover"),OV(C,h.hDf),sV(C,h.id,!0))},fBD=function(C,b,h){g.kb(b.element,"ytp-ce-element-hover");
g.kb(b.element,"ytp-ce-force-expand");sV(C,h.id,!1)},sV=function(C,b,h){C.N&&(h?C.G.show():C.G.hide());
for(var N=g.z(Object.keys(C.K)),p=N.next();!p.done;p=N.next())p=p.value,p!==b&&g.L2(C.K[p].element,"ytp-ce-element-shadow-show",h)},OV=function(C,b,h){function N(){P||(p++,p===b.length&&(c.stop(),h&&h()))}
if(!b||b.length===0||Qg(C))h&&h();else{b=r1D(C,b);var p=0,P=!1,c=new g.wl(function(){P=!0;h&&h()},1E3,C);
c.start();for(C=0;C<b.length;C++)g.vm(b[C],N)}},y10=function(C,b,h){OV(C,b.clickUrls,h);
(C=g.q6())&&b.kiX&&g.gK(C,b.visualElement)},r1D=function(C,b){var h=C.player.getVideoData().clientPlaybackNonce;
C=C.player.getCurrentTime().toFixed(2);h={CPN:h,AD_CPN:h,MT:C};C=[];for(var N=0;N<b.length;N++)C.push(ivU(b[N],h));return C},ivU=function(C,b){return C.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(h){var N=unescape(h);
N=N.substring(1,N.length-1);return b[N]?escape(b[N]):h})},J1$=function(C){return typeof C==="string"?C:""},vM=function(C,b,h){for(var N in b)if(b[N]===C)return C;
return h},u4e=function(C,b,h,N){this.value=C;
this.target=b;this.showLinkIcon=h;this.j=N},D$=function(C){return C.value?C.value:null},dx=function(C){if(!C)return null;
var b=g.iq(J1$(C.value));b=g.AQ(b);if(!b)return null;var h=vM(C.target,Rxj,"current");if(h==null)C=null;else{var N=C.show_link_icon;C=new u4e(b,h,N==="true"||N==="false"?N==="true":!0,C.pause_on_navigation!=null?C.pause_on_navigation:!0)}return C},QyD=function(C,b,h){this.type=C;
this.trigger=b;this.url=h},KRd=function(C){if(!C)return null;
var b=vM(C.type,U0$),h=vM(C.trigger,XJo);C=C.url;C=Array.isArray(C)&&C.length?C[0]:C;C=dx(C?C:null);return b?new QyD(b,h,C):null},syD=function(C,b,h,N,p){this.id=C;
this.type=b;this.style=h;this.data=p;this.action=N||[]},Ovj=function(C,b){return g.Te(C.action,b)},vAj=function(C,b){this.context=C;
this.j=b},D0D=function(C){return C.customMessage?WM("div","iv-card-message",C.customMessage):""},EV=function(C,b){C="background-image: url("+C+");";
var h=[];b&&h.push(b);return{B:"div",C:"iv-card-image",T:{style:C},U:h}},d0e=function(C){if(!C.metaInfo||C.metaInfo.length===0)return"";
var b=[];C=g.z(C.metaInfo);for(var h=C.next();!h.done;h=C.next())b.push(WM("li","",h.value));return{B:"ul",C:"iv-card-meta-info",U:b}},WM=function(C,b,h){b?typeof b==="string"?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.FY(h);return{B:C,T:b,BE:h}},WRC=function(C){if(!C.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],h={};C.B8&&(b.push("iv-card-action-icon"),h.style="background-image: url("+C.B8+");");h.dir=g.FY(C.customMessage);var N=[{B:"span",BE:C.customMessage}];C.showLinkIcon&&(N.push("\u00a0"),N.push({B:"span",C:"iv-card-link-icon"}));return{B:"div",J4:b,T:h,U:N}},n1=function(C,b,h,N){if(N){b=g.z(b);
for(var p=b.next();!p.done;p=b.next())C.j(p.value,N,h.id,h.sessionData,h.aF.click,5)}},EAd=function(C,b){this.merchant=C;
this.price=b},nAC=function(C){var b;
(b=C)&&!(b=C.length>1?C.charAt(0)==="/"&&C.charAt(1)!=="/":C==="/")&&(b=C.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||b.length<1||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b=b[0]==="com"&&b[1]==="youtube"||b[0]==="be"&&b[1]==="youtu");return b?C.indexOf("/redirect?")===-1:!1},tYo=function(C,b){return b?b:nAC(C)?"current":"new"},t6=function(C,b){g.O.call(this);
var h=this;this.element=C;this.context=b;this.zi=!1;this.CO=new Map;this.m6=new Map;this.context.Z.addEventListener(g.gL("annotations_module"),function(N){(N=h.CO.get(N))&&N.apply(h)});
this.context.Z.addEventListener(g.p8("annotations_module"),function(N){(N=h.m6.get(N))&&N.apply(h)})},TP=function(C,b,h,N,p,P,c){C.context.j.listen(b,"click",function(e){C.St(h,N,p,P||[],c||0,e)});
C.context.j.listen(b,"touchstart",function(){C.zi=!1});
C.context.j.listen(b,"touchmove",function(){C.zi=!0})},Twp=function(C){var b;
return((b=g.d(C,g.QA))==null?0:b.url)?g.d(C,g.QA).url:(C=g.d(C,g.Da))&&C.videoId?(b="/watch?v="+C.videoId,C.playlistId&&(b+="&list="+C.playlistId),C.index&&(b+="&index="+C.index),C.startTimeSeconds&&(b+="&t="+C.startTimeSeconds),b):null},BM=function(C,b,h){return{Qq:(C.impressionLoggingUrlsV2s||[]).map(function(N){return N.baseUrl||""}),
click:(h.loggingUrls||[]).map(function(N){return N.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(N){return N.baseUrl||""}),
Ci:(b.impressionLoggingUrlsV2s||[]).map(function(N){return N.baseUrl||""}),
KY:(b.clickLoggingUrlsV2s||[]).map(function(N){return N.baseUrl||""})}},Bwd=function(C,b,h){t6.call(this,b,h);
var N=this;this.Z=C;this.eventId=null;this.G$=this.Df=this.ob=this.N=this.isInitialized=!1;this.cards=[];this.Vz=this.L=this.Qz=this.G=this.t4=this.j=null;this.KO=[];this.N2=this.J=this.O_=this.sX=null;this.W=0;this.q2=new g.wl(function(){},h.If.du?4E3:3E3);
g.D(this,this.q2);this.kh=new g.wl(function(){});
g.D(this,this.kh);this.nO=new vAj(h,function(p,P,c,e,L,Z){TP(N,p,P,c,e,L,Z)});
this.V=new g.n({B:"div",C:"iv-drawer",T:{id:"iv-drawer"},U:[{B:"div",C:"iv-drawer-header",T:{"aria-role":"heading"},U:[{B:"span",C:"iv-drawer-header-text"},{B:"button",J4:["iv-drawer-close-button","ytp-button"],T:{"aria-label":"Hide cards",tabindex:"0"}}]},{B:"div",C:"iv-drawer-content"}]});g.D(this,this.V);this.X=this.V.element;this.Yh=new g.CF(this.V,330);g.D(this,this.Yh);this.sI=g.WE("iv-drawer-header-text",this.X);this.K=g.WE("iv-drawer-content",this.X);this.addCueRange(0,h.videoData.lengthSeconds*
1E3,"",function(){N.ob&&IP(N,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(N.ob=N.N)&&xo(N)});
this.rO=new g.Jm(this);g.D(this,this.rO);this.Z.addEventListener("videodatachange",this.bN.bind(this))},IBp=function(C,b){b=b.data;
b.autoOpenMs&&C.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){IP(C,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&C.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){xo(C)});
var h=b.headerText;g.PP(C.sI,h);C.L&&C.L.setAttribute("title",h);b.eventId&&(C.eventId=b.eventId);C.sX=g.HL(b.trackingParams);C.J=g.HL(b.closeTrackingParams);C.O_=g.HL(b.iconTrackingParams)},x0d=function(C,b){var h=b.cardId?b.cardId:"cr:"+C.W,N=C.Z.Y().experiments.Fo("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&N){var p=b.teaser.simpleCardTeaserRenderer,P=b.icon?b.icon.infoCardIconRenderer:null;b={id:h,timestamp:C.W,type:"simple",teaserText:g.lI(p.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,aF:{},Ua:null,NU:p.trackingParams?g.HL(p.trackingParams):null,O_:P&&P.trackingParams?g.HL(P.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
B8:null,title:"",customMessage:"",url:null,onClickCommand:p.onTapCommand||null};wx(C,b)}else{var c;if((c=b.content)==null?0:c.simpleCardContentRenderer){if(!b.cueRanges.length)return;P=(p=b.content)==null?void 0:p.simpleCardContentRenderer;p=b.teaser.simpleCardTeaserRenderer;var e=b.icon?b.icon.infoCardIconRenderer:null;b={id:h,timestamp:C.W,type:"simple",teaserText:g.lI(p.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:Cq(C,h,b,P),sponsored:!1,aF:BM(P,p,P.command),Ua:P.trackingParams?g.HL(P.trackingParams):null,NU:p.trackingParams?g.HL(p.trackingParams):null,O_:e&&e.trackingParams?g.HL(e.trackingParams):null,imageUrl:b5(P.image.thumbnails,290).url,displayDomain:P.displayDomain?g.lI(P.displayDomain):null,showLinkIcon:!!P.showLinkIcon,B8:null,title:P.title?g.lI(P.title):"",customMessage:P.callToAction?g.lI(P.callToAction):"",url:g.d(P.command,g.QA).url?dx({pause_on_navigation:!C.context.videoData.isLivePlayback,
target:"new",value:g.d(P.command,g.QA).url}):null,onClickCommand:null};wx(C,b)}else{var L;if((L=b.content)==null?0:L.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;p=(P=b.content)==null?void 0:P.collaboratorInfoCardContentRenderer;P=b.teaser.simpleCardTeaserRenderer;e=b.icon?b.icon.infoCardIconRenderer:null;b={id:h,timestamp:C.W,type:"collaborator",teaserText:g.lI(P.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:Cq(C,h,b,p),sponsored:!1,aF:BM(p,P,p.endpoint),Ua:p.trackingParams?g.HL(p.trackingParams):null,NU:P.trackingParams?g.HL(P.trackingParams):null,O_:e&&e.trackingParams?g.HL(e.trackingParams):null,channelId:g.d(p.endpoint,g.oD).browseId,customMessage:p.customText?g.lI(p.customText):null,profileImageUrl:b5(p.channelAvatar.thumbnails,290).url,title:p.channelName?g.lI(p.channelName):"",metaInfo:[p.subscriberCountText?g.lI(p.subscriberCountText):""],url:dx({pause_on_navigation:!C.context.videoData.isLivePlayback,
target:"new",value:g.d(p.endpoint,g.oD).canonicalBaseUrl?g.d(p.endpoint,g.oD).canonicalBaseUrl:"/channel/"+g.d(p.endpoint,g.oD).browseId}),onClickCommand:null};wx(C,b)}else{var Z;if((Z=b.content)==null?0:Z.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;p=(e=b.content)==null?void 0:e.playlistInfoCardContentRenderer;P=b.teaser.simpleCardTeaserRenderer;e=b.icon?b.icon.infoCardIconRenderer:null;b={id:h,timestamp:C.W,type:"playlist",teaserText:g.lI(P.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:Cq(C,h,b,p),sponsored:!1,aF:BM(p,P,p.action),Ua:p.trackingParams?g.HL(p.trackingParams):null,NU:P.trackingParams?g.HL(P.trackingParams):null,O_:e&&e.trackingParams?g.HL(e.trackingParams):null,XW:b5(p.playlistThumbnail.thumbnails,258).url,customMessage:p.customMessage?g.lI(p.customMessage):null,playlistVideoCount:g.lI(p.playlistVideoCount),title:p.playlistTitle?g.lI(p.playlistTitle):"",metaInfo:[p.channelName?g.lI(p.channelName):
"",p.videoCountText?g.lI(p.videoCountText):""],url:dx({pause_on_navigation:!C.context.videoData.isLivePlayback,target:"new",value:Twp(p.action)}),onClickCommand:null};wx(C,b)}else{var Y;if((Y=b.content)==null?0:Y.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var a;p=(a=b.content)==null?void 0:a.videoInfoCardContentRenderer;P=b.teaser.simpleCardTeaserRenderer;e=b.icon?b.icon.infoCardIconRenderer:null;b={id:h,timestamp:C.W,type:"video",teaserText:g.lI(P.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:Cq(C,h,b,p),sponsored:!1,aF:BM(p,P,p.action),Ua:p.trackingParams?g.HL(p.trackingParams):null,NU:P.trackingParams?g.HL(P.trackingParams):null,O_:e&&e.trackingParams?g.HL(e.trackingParams):null,XW:b5(p.videoThumbnail.thumbnails,258).url,videoDuration:p.lengthString?g.lI(p.lengthString):null,customMessage:p.customMessage?g.lI(p.customMessage):null,title:p.videoTitle?g.lI(p.videoTitle):"",metaInfo:[p.channelName?g.lI(p.channelName):
"",p.viewCountText?g.lI(p.viewCountText):""],isLiveNow:!!p.badge,url:dx({pause_on_navigation:!C.context.videoData.isLivePlayback,target:"new",value:Twp(p.action)}),onClickCommand:null};wx(C,b)}}}}}C.W++},b5=function(C,b){for(var h=-1,N=-1,p=0;p<C.length;p++){if(C[p].height===b||C[p].width===290)return C[p];
((C[p].height||0)<b||(C[p].width||0)<290)&&(h<0||(C[h].height||0)<(C[p].height||0)||(C[h].width||0)<(C[p].width||0))?h=p:((C[p].height||0)>=b||(C[p].width||0)>=290)&&(N<0||(C[N].height||0)>(C[p].height||0)||(C[N].width||0)>(C[p].width||0))&&(N=p)}return C[N>=0?N:h]},Cq=function(C,b,h,N){return{feature:h.feature?h.feature:"cards",
src_vid:C.context.videoData.videoId,annotation_id:b,ei:C.context.videoData.eventId||"",itct:N.trackingParams||""}},Cq0=function(C,b){if(b=wJC(C,b))b===C.j&&(C.j=null),C.Z.removeCueRange(b.U_.id),g.gQ(b.AS),g.wD(C.cards,b),C.f7(),hs(C)},IP=function(C,b,h){if(!C.N){C.Yh.show();
C.t4=new g.wl(function(){g.j6(C.context.Z.getRootNode(),g.Rc.IV_DRAWER_OPEN)},0);
C.t4.start();C.rO.S(C.K,"mousewheel",function(c){C.q2.start();c.preventDefault();c=c||window.event;var e=0;c.type=="MozMousePixelScroll"?e=0==(c.axis==c.HORIZONTAL_AXIS)?c.detail:0:window.opera?e=c.detail:e=c.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?c.wheelDeltaY/-30:c.wheelDeltaY/-1.2:c.wheelDelta/-1.6:c.wheelDeltaY/-3;if(c=e)C.K.scrollTop+=c});
C.N=!0;var N=g.q6();N&&C.sX&&C.J&&g.hu(N,[C.sX,C.J]);b={TRIGGER_TYPE:b};for(var p=g.z(C.cards),P=p.next();!P.done;P=p.next())P=P.value,P.DM||(P.DM=!0,bo0(C.context.logger,P.U_.aF.Qq,b)),N&&g.hu(N,[P.U_.Ua]);my(C.Z);h&&(C.G=new g.wl(function(){C.Qz=C.L;C.Vz.focus()},330),C.G.start())}},xo=function(C){C.N&&(C.Yh.hide(),g.yJ(C.rO),g.kb(C.context.Z.getRootNode(),g.Rc.IV_DRAWER_OPEN),C.N=!1,my(C.Z),C.G&&C.G.stop(),C.G=new g.wl(function(){C.Qz&&(C.Qz.focus(),C.Qz=null)},330),C.G.start())},hnD=function(C){g.c4(C.Rb(),
[g.Rc.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.MC(C.Z,C.X,5);C.Ru();C.L=g.WE("ytp-cards-button",C.Z.getRootNode());C.Vz=g.WE("iv-drawer-close-button",C.X);C.isInitialized=!0},N2h=function(C){C.KO.push(g.Pl("iv-teaser-shown",C.JI,C));
C.KO.push(g.Pl("iv-teaser-hidden",C.x8z,C));C.KO.push(g.Pl("iv-teaser-clicked",C.H9,C));C.G$=!0},gTd=function(C,b){var h;
return b.onClickCommand&&((h=g.d(b.onClickCommand,g.JoU))==null?void 0:h.targetId)==="engagement-panel-error-corrections"?(C.N2=b,!0):!1},phd=function(C,b){C.N2=b;
var h=C.Z.getVideoData();if(!h)return!1;h=g.FJ(h);if(h==null?0:h.markersMap)for(var N,p=0;((N=h)==null?void 0:N.markersMap.length)>p;p++){var P=void 0,c=(P=h)==null?void 0:P.markersMap[p];if(c.key==="ERROR_CORRECTION_MARKERS"&&(P=void 0,(c=(P=c.value)==null?void 0:P.markers)&&c.length>0))return N=void 0,b.startMs=((N=g.d(c[0],g.SI1))==null?void 0:N.timeRangeStartMillis)||0,C.N2=null,!0}return!1},wx=function(C,b){if(!gTd(C,b)||phd(C,b)){var h=Pq0(C,b);
if(h){var N={U_:b,AS:h.element,DM:!1};if(b.onClickCommand)C.Z.D("web_infocards_teaser_show_logging_fix")&&(C.G$||N2h(C),Cq0(C,b.id),h=C.findLastIndex(N),g.P5(C.cards,h,0,N));else{C.isInitialized||hnD(C);Cq0(C,b.id);var p=C.findLastIndex(N);g.P5(C.cards,p,0,N);h.Gi(C.K,p);C.f7()}b.autoOpen?C.addCueRange(b.startMs,0x8000000000000,b.id,function(){C.N||(C.j=N,hs(C),jeC(C,N),IP(C,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(h=C.context.Z.getCurrentTime()*1E3,h<5E3&&h>b.startMs&&cQ0(C,N),C.addCueRange(b.startMs,
b.startMs+1,b.id,function(){cQ0(C,N)}),hs(C))}}},Pq0=function(C,b){switch(b.type){case "simple":C=C.nO;
var h=b.displayDomain?{B:"div",C:"iv-card-image-text",BE:b.displayDomain}:void 0;var N=WRC(b);h={B:"div",J4:["iv-card"],U:[{B:"a",C:"iv-click-target",T:{href:b.url?D$(b.url)||"":""},U:[EV(b.imageUrl,h),{B:"div",C:"iv-card-content",U:[WM("h2",void 0,b.title),N]}]}]};h=new g.n(h);n1(C,g.DZ("iv-click-target",h.element),b,b.url);b=h;break;case "collaborator":C=C.nO;h={B:"div",J4:["iv-card","iv-card-channel"],U:[{B:"a",J4:["iv-click-target"],T:{href:D$(b.url)||"","data-ytid":b.channelId},U:[EV(b.profileImageUrl),
{B:"div",C:"iv-card-content",U:[D0D(b),{B:"h2",C:"iv-card-primary-link",BE:b.title},d0e(b)]}]}]};h=new g.n(h);n1(C,g.DZ("iv-click-target",h.element),b,b.url);b=h;break;case "playlist":C=C.nO;h={B:"div",J4:["iv-card","iv-card-playlist"],U:[{B:"a",C:"iv-click-target",T:{href:D$(b.url)||""},U:[EV(b.XW,{B:"div",C:"iv-card-image-overlay",U:[{B:"span",C:"iv-card-playlist-video-count",BE:b.playlistVideoCount}]}),{B:"div",C:"iv-card-content",U:[D0D(b),WM("h2","iv-card-primary-link",b.title),d0e(b)]}]}]};
h=new g.n(h);n1(C,g.DZ("iv-click-target",h.element),b,b.url);b=h;break;case "productListing":C=C.nO;var p=b.offers.length!=0;h=["iv-card"];N="";var P=WRC(b);p&&(h.push("iv-card-product-listing"),N="iv-card-primary-link",P=b.offers[0],p=[],P.price&&p.push({B:"div",C:"iv-card-offer-price",BE:P.price}),P.merchant&&p.push({B:"div",C:"iv-card-offer-merchant",BE:P.merchant}),P={B:"div",U:p});p=b.url?D$(b.url)||"":"";h={B:"div",J4:h,T:{tabindex:"0"},U:[{B:"a",J4:["iv-card-image","iv-click-target"],T:{style:"background-image: url("+
b.imageUrl+");",href:p,"aria-hidden":"true",tabindex:"-1"}},{B:"div",C:"iv-card-content",U:[b.sponsored?{B:"div",C:"iv-card-sponsored",U:["Sponsored",{B:"div",C:"iv-ad-info-container",U:[{B:"div",C:"iv-ad-info",BE:"{{adInfo}}"},{B:"div",C:"iv-ad-info-icon-container",U:[{B:"div",C:"iv-ad-info-icon"},{B:"div",C:"iv-ad-info-callout"}]}]}]}:"",{B:"a",C:"iv-click-target",T:{href:p},U:[WM("h2",N,b.title),P]}]}]};h=new g.n(h);N=g.wk("span");g.PP(N,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
h.jh(N,"adInfo");n1(C,g.DZ("iv-click-target",h.element),b,b.url);b=h;break;case "video":C=C.nO;N=b.videoDuration?{B:"span",C:"iv-card-video-duration",BE:b.videoDuration}:void 0;P=b.isLiveNow?{B:"span",J4:["yt-badge","yt-badge-live"],BE:"LIVE NOW"}:null;p={B:"div",J4:["iv-card","iv-card-video"],U:[{B:"a",C:"iv-click-target",T:{href:((h=b.url)==null?void 0:D$(h))||""},U:[EV(b.XW,N),{B:"div",C:"iv-card-content",U:[D0D(b),WM("h2","iv-card-primary-link",b.title),d0e(b),P]}]}]};h=new g.n(p);n1(C,g.DZ("iv-click-target",
h.element),b,b.url);b=h;break;default:return null}return b},kCC=function(C){if(C.j)return C.j.U_.type==="productListing";
if(C.Z.D("enable_wn_infocards")){var b;return!((b=C.cards)==null||!b.length)&&g.q_(C.cards,function(h){return h.U_.type==="productListing"})}return g.q_(C.cards,function(h){return h.U_.type==="productListing"})},hs=function(C){g.L2(C.Z.getRootNode(),"ytp-cards-shopping-active",kCC(C))},cQ0=function(C,b){if(!g.P4(C.Z.getRootNode(),"ytp-cards-teaser-shown")){if(C.j!==b){var h=g.q6(),N=C.j?C.j.U_.O_:C.O_;
h&&N&&g.Nb(h,[N]);C.j=b;hs(C)}(h=C.isInitialized&&C.Rb().style.display=="none")||(h=C.context.Z.getPlayerState(),N=h===0&&C.context.Z.getCurrentTime()===0,h=!(h===1||h===3||N));h||b.U_.teaserDurationMs&&C.Z.TT(!0,{teaserText:b.U_.teaserText,durationMs:b.U_.teaserDurationMs,onClickCommand:b.U_.onClickCommand});C.kh.isActive()||((!C.N||!C.q2.isActive()&&C.Df)&&jeC(C,b),C.kh.start(910+b.U_.teaserDurationMs))}},jeC=function(C,b){C.V.Bb?(b=new iL([0,
C.K.scrollTop],[0,b.AS.offsetTop],600,lBD),C.context.N.listen(b,"animate",function(h){C.K.scrollTop=h.y}),C.context.N.listen(b,"finish",function(h){C.K.scrollTop=h.y}),b.play()):(C.V.Kj(!0),C.K.scrollTop=b.AS.offsetTop,C.V.Kj(!1))},Nk=function(C){return C.j&&C.j.U_?C.j.U_:C.cards[0]&&C.cards[0].U_?C.cards[0].U_:null},wJC=function(C,b){return g.Te(C.cards,function(h){return h.U_.id===b})},g5=function(C,b,h){t6.call(this,C,b);
this.annotation=h;this.isActive=!1},eno=function(C){var b=C.annotation.data;
"start_ms"in b&&"end_ms"in b&&C.addCueRange(Number(b.start_ms),Number(b.end_ms),C.annotation.id,function(){C.show()},function(){C.hide()})},pq=function(C,b,h){g5.call(this,C,b,h);
this.K=null;this.J=!1;this.N=null;this.X=!1;this.j=this.W=this.G=null},Loh=function(C,b){var h=h===void 0?0:h;
var N=PBh(b).width;g.Fo(b,N);h=new YQj(b,[N,b.offsetTop],[N-N-h,b.offsetTop],200,aBh);g.D(C,h);C.context.N.listen(h,"begin",function(){g.Vx(b,!0)});
h.play()},aqI=function(C,b){if(b.channel_name){var h=C.createElement({B:"div",
J4:["iv-branding-context-name"],BE:b.channel_name}),N=C.createElement({B:"div",J4:["iv-branding-context-subscribe"]}),p=b.standalone_subscribe_button_data;p&&(C.j=new g.PH(p.subscribeText,p.subscribeCount,p.unsubscribeText,p.unsubscribeCount,!!p.enabled,!!p.classic,b.channel_id,!!p.subscribed,p.feature,b.session_data.itct,C.context.Z,!1),C.j.Gi(N));var P=C.createElement({B:"div",J4:["iv-branding-context-subscribe-caret"]}),c=C.createElement({B:"div",J4:["branding-context-container-inner"]});c.appendChild(P);
c.appendChild(h);c.appendChild(N);g.Vx(c,!1);var e=C.createElement({B:"div",J4:["branding-context-container-outer"]});e.appendChild(c);g.LV(e,"right",b.image_width+"px");g.bn(C.Rb(),e);C.N=new g.wl(function(){Zo0(C,c,e)},500);
g.D(C,C.N);C.context.j.listen(C.Rb(),"mouseover",function(){YN$(C,c,e,P,b.image_height)});
C.context.j.listen(C.Rb(),"mouseout",function(){C.N.start()})}},YN$=function(C,b,h,N,p){C.N.stop();
if(!C.X){var P=g.Hc(b);C.j||(b.style.width=g.ou(P.width,!0),h.style.width=g.ou(P.width,!0));g.LV(N,"top",P.height-Math.max(Math.min(P.height,p)/2+10,20)+"px");g.LV(N,"right","1px");C.X=!0;g.Vx(b,!0);C.G=new g.wl(function(){g.j6(this.Rb(),"iv-branding-active")},0,C);
C.G.start()}},Zo0=function(C,b,h){g.kb(C.Rb(),"iv-branding-active");
C.W=new g.wl(function(){g.Vx(b,!1);C.j||(h.style.width=g.ou(0,!0))},250);
C.W.start();C.X=!1},lqd=function(C,b,h,N,p,P,c){this.j=C;
this.N=b;this.If=h;this.videoData=N;this.logger=p;this.Z=P;this.K=c},oTj=function(C,b,h){g5.call(this,C,b,h);
var N=this;this.L=this.isCollapsed=this.V=!1;this.W=5E3;this.K=this.N=this.j=this.X=null;this.J=this.createElement({B:"div",J4:["iv-promo-contents"]});this.G=new g.wl(function(){N.j.setAttribute("aria-hidden","true");g.Vx(N.N,!1);g.Vx(N.K,!0)},700,this);
g.D(this,this.G)},GCI=function(C){var b=C.annotation.data;
if(C.annotation.style==="cta")var h=6;else if(C.annotation.style==="video"||C.annotation.style==="playlist")h=7;C.W=b.collapsedelay_ms||C.W;var N=["iv-promo","iv-promo-inactive"];C.Rb().setAttribute("aria-hidden","true");C.Rb().setAttribute("aria-label","Promotion");C.Rb().tabIndex=0;var p=C.annotation.p9(),P=b.image_url;if(P){var c=C.createElement({B:"div",J4:["iv-promo-img","iv-click-target"]});P=C.createElement({B:"img",T:{src:P,"aria-hidden":"true"}});c.appendChild(P);b.video_duration&&!b.is_live?
(P=C.createElement({B:"span",C:"iv-promo-video-duration",BE:b.video_duration}),c.appendChild(P)):b.playlist_length&&(P=C.createElement({B:"span",C:"iv-promo-playlist-length",BE:b.playlist_length.toString()}),c.appendChild(P));p&&TP(C,c,p,C.annotation.id,b.session_data,void 0,h)}p?(P=C.createElement({B:"a",C:"iv-promo-txt"}),g.uq(P,D$(p)),C.j=P):C.j=C.createElement({B:"div",C:"iv-promo-txt"});switch(C.annotation.style){case "cta":case "website":var e=C.createElement({B:"p",U:[{B:"strong",BE:b.text_line_1}]});
var L=C.createElement({B:"p",U:[{B:"span",C:"iv-promo-link",BE:b.text_line_2}]});if(P=b.text_line_3){N.push("iv-promo-website-card-cta-redesign");var Z=C.createElement({B:"button",J4:["iv-promo-round-expand-icon","ytp-button"]});P=C.createElement({B:"button",J4:["iv-button","iv-promo-button"],U:[{B:"span",C:"iv-button-content",BE:P}]});var Y=C.createElement({B:"div",C:"iv-promo-button-container"});Y.appendChild(P);p&&TP(C,C.Rb(),p,C.annotation.id,b.session_data,void 0,h)}g.j6(C.j,"iv-click-target");
p&&TP(C,C.j,p,C.annotation.id,b.session_data,void 0,h);break;case "playlist":case "video":e=C.createElement({B:"p",U:[{B:"span",BE:b.text_line_1}]}),L=C.createElement({B:"p",U:[{B:"strong",BE:b.text_line_2}]}),b.is_live&&(e=L,L=C.createElement({B:"span",J4:["yt-badge","iv-promo-badge-live"],BE:"LIVE NOW"})),g.j6(C.j,"iv-click-target"),p&&TP(C,C.j,p,C.annotation.id,b.session_data,void 0,h),N.push("iv-promo-video")}e&&C.j.appendChild(e);L&&C.j.appendChild(L);C.J.appendChild(C.j);Y&&C.J.appendChild(Y);
h=C.createElement({B:"div",C:"iv-promo-actions"});C.K=C.createElement({B:"button",J4:["iv-promo-expand","ytp-button"]});C.K.title="Expand";C.context.j.listen(C.K,"click",function(a){FoC(C,5E3,a)});
h.appendChild(C.K);g.Vx(C.K,!1);C.context.j.listen(C.Rb(),"mouseover",C.wED,C);C.context.j.listen(C.Rb(),"mouseout",C.XEi,C);C.context.j.listen(C.Rb(),"touchend",function(a){FoC(C,5E3,a)});
C.N=C.createElement({B:"button",J4:["iv-promo-close","ytp-button"]});C.N.title="Close";C.context.j.listen(C.N,"click",C.annotation.style==="cta"&&b.text_line_3?C.vhi:C.Ifp,C);h.appendChild(C.N);g.c4(C.Rb(),N);c&&(g.bn(C.Rb(),c),Z&&c.appendChild(Z));g.bn(C.Rb(),C.J);g.bn(C.Rb(),h)},FoC=function(C,b,h){h.stopPropagation();
SNC(C);$Nj(C,b);C.j.focus()},znd=function(C){C.isCollapsed||C.L||C.X||(g.j6(C.Rb(),"iv-promo-collapsed"),C.isCollapsed=!0,C.G.start())},SNC=function(C){C.G.stop();
C.isCollapsed&&(g.e6(C.Rb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),C.isCollapsed=!1,C.j&&C.j.removeAttribute("aria-hidden"),g.Vx(C.K,!1),g.Vx(C.N,!0))},$Nj=function(C,b){C.X||(C.X=g.Vh(function(){Hoh(this);
znd(this)},b,C))},Hoh=function(C){C.X&&(g.KW.clearTimeout(C.X),C.X=null)},V9o=function(C){this.Z=C},bo0=function(C,b,h){b&&(h?PB(C,b.map(function(N){return g.J5(N,h)})):PB(C,b))},PB=function(C,b,h,N){var p=1,P=void 0,c=-1;
if(h){var e=!1;P=function(){p--;p||e||(clearTimeout(c),e=!0,h())};
c=setTimeout(function(){e=!0;h()},1E3)}b=g.z(b||[]);
for(var L=b.next();!L.done;L=b.next())L=L.value,p++,g.vm(L,P);N&&(p++,N!==0&&C.Z.sendVideoStatsEngageEvent(N,P))},M9e=function(C){g.qK.call(this,C);
var b=this;this.KO=this.L=!1;this.loadNumber=0;this.W={};this.logger=new V9o(this.player);this.X=new g.Jm(this);this.G=this.J=null;this.events=new g.Jm(this);this.JL=this.V=this.j=null;this.N2=[];g.D(this,this.X);this.X.S(this.player,"onVideoAreaChange",function(){b.publish("onVideoAreaChange")});
this.X.S(this.player,"onHideControls",function(){b.publish("onHideControls")});
this.X.S(this.player,"onShowControls",function(){b.publish("onShowControls")});
this.X.S(this.player,"resize",function(N){b.publish("resize",N)});
this.X.S(this.player,"presentingplayerstatechange",function(N){b.publish("presentingplayerstatechange",N)});
this.subscribe("presentingplayerstatechange",this.QN,this);this.subscribe("resize",this.bD,this);this.player.Y().Df.subscribe("vast_info_card_add",this.mG,this);g.D(this,this.events);this.nO=this.createElement({B:"div",C:"video-custom-annotations"});this.K=new g.n({B:"div",J4:["ytp-player-content","ytp-iv-player-content"]});g.D(this,this.K);g.MC(this.player,this.K.element,4);this.K.hide();this.N=new g.n({B:"div",J4:["ytp-iv-video-content"]});g.D(this,this.N);C=this.createElement({B:"div",C:"video-annotations"});
C.appendChild(this.nO);this.N.element.appendChild(C);this.Fa()&&this.load();var h=this.createElement({B:"style"});(g.vE("HEAD")[0]||document.body).appendChild(h);this.addOnDisposeCallback(function(){g.gQ(h)});
if(C=h.sheet)C.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),C.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),C.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),C.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),C.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),C.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),C.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),C.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),C.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),C.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},qN$=function(C){C=C.createElement({B:"div",
J4:["annotation","annotation-type-custom"]});g.Vx(C,!1);return C},mND=function(C,b){b=!b.isCued()&&!g.B(b,1024);
C.K.Kj(b);C.N.Kj(b)},fqE=function(C,b,h){C.L=!0;
C.G=g.mt(b,h)},AQo=function(C,b){for(var h={},N=g.z(b.attributes),p=N.next();!p.done;p=N.next())p=p.value,h[p.name]=p.nodeValue;
for(N=0;N<b.childNodes.length;N++)if(p=b.childNodes[N],g.tl(p)&&p.nodeType==1){if(h[p.tagName])var P=h[p.tagName];else if(p.tagName==="data"){p.childNodes.length>0&&(P=p.childNodes[0].nodeValue,h[p.tagName]=typeof P==="string"?P.trim():P);continue}else P=[],h[p.tagName]=P;p&&p.tagName==="TEXT"?p.childNodes.length===1&&p.childNodes[0].nodeType===3?P.push(p.childNodes[0].nodeValue):P.push(""):p&&P.push(AQo(C,p))}return h},JQU=function(C){var b=C.player.getVideoData();
if(b.m6){var h=C.player.Y().Df.get(b.videoId);if(h){var N={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(p,P,c){p=C.loadNumber;P=b.videoId;C.loaded&&C.loadNumber===p&&C.player.getVideoData().videoId===P&&(c=g.la(c)&&c.responseXML?c.responseXML:null)&&yQU(C,c)}};
g.bf()&&(N.onFinish=rQD(C,N.onFinish));N.postParams={ic_only:"1"};ioE(N,h);C.L=!0;g.mt(b.m6,N)}}},ioE=function(C,b){C.method="POST";
C.postParams=C.postParams||{};b.ij&&(C.postParams.ic_coll=b.ij);b.Ii&&(C.postParams.ic_xml=b.Ii);b.nY&&(C.postParams.ic_track=b.nY)},unD=function(C){var b=new g.n({B:"div"});
g.Vx(b.element,!1);var h=new Bwd(C.player,b.element,jy(C));g.D(h,b);b.Gi(C.K.element);h.Sm();return h},Qep=function(C,b){var h,N;
if(b=(h=b.getWatchNextResponse())==null?void 0:(N=h.cards)==null?void 0:N.cardCollectionRenderer)C.KO=!0,Rno(C,b),b.headerText&&C.JL&&(h=g.lI(b.headerText),C.JL.setAttribute("title",h))},jy=function(C){if(!C.V){var b=new oAd(C);
g.D(C,b);var h=new g.VV(C);g.D(C,h);C.V=new lqd(b,h,C.player.Y(),C.player.getVideoData(),C.logger,C.player,C.Fz)}return C.V},yQU=function(C,b){var h=!1,N=b.getElementsByTagName("annotations");
if(N&&!(N.length<1)&&(N=N[0].getAttribute("itct"))){var p=g.q6();if(p){var P=g.M6();P&&g.wW(g.Er)(void 0,p,P,[g.HL(N)])}}b=b.getElementsByTagName("annotation");for(N=0;N<b.length;N++){P=AQo(C,b[N]);p=null;try{if(P){var c=P.id,e=/.+/;var L=typeof c==="string"&&e!=null&&c!=null&&c.match(e)?c:"";var Z=vM(P.type,UN0),Y=vM(P.style,Xhh),a=J1$(P.data),l=a.length!==0?JSON.parse(a):{};var F=P.action;P=KRd;if(F==null)var G=null;else if(g.nW(F)){e=[];for(var V=g.z(F),q=V.next();!q.done;q=V.next()){var f=P(q.value);
f&&e.push(f)}G=e}else{var y=P(F);G=y?[y]:[]}p=L&&Z?new syD(L,Z,Y,G,l):null}else p=null}catch(go){}if(p)if(p.type==="branding"||p.type==="promotion"){P=C;e=p;var u=qN$(P),K=null;switch(e.type){case "branding":if(P.player.Y().w9)break;P.K.element.appendChild(u);K=new pq(u,jy(P),e);break;case "promotion":g.MC(P.player,u,4),K=new oTj(u,jy(P),e)}K&&K.Sm();if(P=K)g.D(C,P),C.W[p.id]=P}else if(p.type==="card"||p.type==="drawer"){C.j||(C.j=unD(C),g.D(C,C.j));if(p.type==="card"){u=C.j;var v=(h=p)&&h.data&&
h.data.card_type;p=h.data;if(v)switch(P=p.tracking||{},P={Qq:P.impression,click:P.click,close:P.close,Ci:P.teaser_impression,KY:P.teaser_click},e=p.tracking_params||{},K=null,v){case "collaborator":h={id:h.id,timestamp:p.timestamp||0,type:p.card_type,teaserText:p.teaser_text,teaserDurationMs:p.teaser_duration_ms,startMs:p.start_ms,autoOpen:p.auto_open||!1,sessionData:p.session_data||{},sponsored:p.sponsored||!1,aF:P,Ua:e.card?g.HL(e.card):null,NU:e.teaser?g.HL(e.teaser):null,O_:e.icon?g.HL(e.icon):
null,channelId:p.channel_id,customMessage:p.custom_message?p.custom_message:null,profileImageUrl:p.image_url,title:p.title,metaInfo:p.meta_info,url:dx({pause_on_navigation:p.pause_on_navigation,target:p.target||"new",value:p.url}),onClickCommand:null};wx(u,h);break;case "playlist":h={id:h.id,timestamp:p.timestamp||0,type:p.card_type,teaserText:p.teaser_text,teaserDurationMs:p.teaser_duration_ms,startMs:p.start_ms,autoOpen:p.auto_open||!1,sessionData:p.session_data||{},sponsored:p.sponsored||!1,aF:P,
Ua:e.card?g.HL(e.card):null,NU:e.teaser?g.HL(e.teaser):null,O_:e.icon?g.HL(e.icon):null,XW:p.image_url,playlistVideoCount:p.playlist_video_count,customMessage:p.custom_message?p.custom_message:null,title:p.title,metaInfo:p.meta_info,url:dx({pause_on_navigation:p.pause_on_navigation,target:p.target||"new",value:p.url}),onClickCommand:null};wx(u,h);break;case "productListing":p.signin_url&&(K=dx({target:"current",value:p.signin_url}));v=[];for(var T=p.offers||[],t=0;t<T.length;t++)v.push(new EAd(g.xT(T[t].merchant),
g.xT(T[t].price)));h={id:h.id,timestamp:p.timestamp||0,type:p.card_type,teaserText:p.teaser_text,teaserDurationMs:p.teaser_duration_ms,startMs:p.start_ms,autoOpen:p.auto_open||!1,sessionData:p.session_data||{},sponsored:p.sponsored||!1,aF:P,Ua:e.card?g.HL(e.card):null,NU:e.teaser?g.HL(e.teaser):null,O_:e.icon?g.HL(e.icon):null,imageUrl:p.image_url,displayDomain:p.display_domain?p.display_domain:null,showLinkIcon:!!p.show_link_icon,B8:p.button_icon_url?p.button_icon_url:null,title:p.title,customMessage:p.custom_message?
p.custom_message:null,url:dx({pause_on_navigation:p.pause_on_navigation,target:p.target||"new",value:p.url}),cKD:K,rKO:p.signin_title?p.signin_title:void 0,MU2:p.signin_message?p.signin_message:void 0,offers:v,onClickCommand:null};wx(u,h);break;case "simple":h={id:h.id,timestamp:p.timestamp||0,type:p.card_type,teaserText:p.teaser_text,teaserDurationMs:p.teaser_duration_ms,startMs:p.start_ms,autoOpen:p.auto_open||!1,sessionData:p.session_data||{},sponsored:p.sponsored||!1,aF:P,Ua:e.card?g.HL(e.card):
null,NU:e.teaser?g.HL(e.teaser):null,O_:e.icon?g.HL(e.icon):null,imageUrl:p.image_url,displayDomain:p.display_domain?p.display_domain:null,showLinkIcon:!!p.show_link_icon,B8:p.button_icon_url?p.button_icon_url:null,title:p.title,customMessage:p.custom_message?p.custom_message:null,url:dx({pause_on_navigation:p.pause_on_navigation,target:p.target||"new",value:p.url}),onClickCommand:null};wx(u,h);break;case "video":h={id:h.id,timestamp:p.timestamp||0,type:p.card_type,teaserText:p.teaser_text,teaserDurationMs:p.teaser_duration_ms,
startMs:p.start_ms,autoOpen:p.auto_open||!1,sessionData:p.session_data||{},sponsored:p.sponsored||!1,aF:P,Ua:e.card?g.HL(e.card):null,NU:e.teaser?g.HL(e.teaser):null,O_:e.icon?g.HL(e.icon):null,XW:p.image_url,videoDuration:p.video_duration||null,customMessage:p.custom_message?p.custom_message:null,title:p.title,metaInfo:p.meta_info,isLiveNow:!!p.is_live_now,url:dx({pause_on_navigation:p.pause_on_navigation,target:p.target||"new",value:p.url}),onClickCommand:null},wx(u,h)}}else IBp(C.j,p);h=!0}}h&&
(my(C.player),C.bD())},Rno=function(C,b){var h=!1;
C.j||(C.j=unD(C),g.D(C,C.j));for(var N=g.z(b.cards||[]),p=N.next();!p.done;p=N.next())p=p.value,p.cardRenderer&&(x0d(C.j,p.cardRenderer),h=!0);if(h){var P;(P=C.player.getVideoData())!=null&&g.V4(P)||(h=C.j,N=b.headerText?g.lI(b.headerText):"",g.PP(h.sI,N),h.L&&h.L.setAttribute("title",N),h.context.videoData.eventId&&(h.eventId=h.context.videoData.eventId),h.sX=b.trackingParams?g.HL(b.trackingParams):null,h.J=b.closeButton.infoCardIconRenderer.trackingParams?g.HL(b.closeButton.infoCardIconRenderer.trackingParams):
null,h.O_=b.icon.infoCardIconRenderer.trackingParams?g.HL(b.icon.infoCardIconRenderer.trackingParams):null,C.bD());my(C.player)}},KoD=function(C,b,h,N,p){if(!C.player.Y().w9){var P=[];
b.navigationEndpoint&&g.d(b.navigationEndpoint,g.oD)&&g.d(b.navigationEndpoint,g.oD).browseId&&P.push(new QyD("openUrl","click",new u4e("/channel/"+g.d(b.navigationEndpoint,g.oD).browseId,"new",!0,!0)));var c=b.watermark.thumbnails[0];N={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:c.height,image_type:1,image_url:c.url,image_width:c.width,is_mobile:!1,session_data:{annotation_id:h,ei:p,feature:"iv",itct:b.trackingParams,src_vid:N},start_ms:b.startTimeMs};if(b.subscribeButton&&g.d(b.subscribeButton,
g.F5)){N.channel_id=g.d(b.subscribeButton,g.F5).channelId;var e;b=g.d(b.subscribeButton,g.F5);c=p=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(p=g.lI(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(c=g.lI(b.subscriberCountText))):(b.subscriberCountText&&(p=g.lI(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(c=g.lI(b.subscriberCountWithSubscribeText)));var L,Z=((L=g.d((e=b.signInEndpoint)==null?void 0:e.commandMetadata,g.St))==null?void 0:L.url)||"";e={subscribeText:g.lI(b.unsubscribedButtonText),
subscribeCount:p||"",unsubscribeText:g.lI(b.subscribedButtonText),unsubscribeCount:c||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:Z};N.standalone_subscribe_button_data=e}P=new syD(h,"branding","branding",P,N);e=qN$(C);C.K.element.appendChild(e);P=new pq(e,jy(C),P);P.Sm();g.D(P,P);C.W[h]=P}},rQD=function(C,b){return function(){var h=g.yH.apply(0,arguments);
C.HE()||C.N2.push(g.dl.Vy(function(){b.apply(null,g.M(h))}))}},seU=function(C){return C==="annotation-editor"||C==="live-dashboard"};
g.oC.prototype.TT=g.NW(40,function(C,b){var h=g.sC(this.N8());h&&h.TT(C,b)});
var A6={},yg=null;g.bC(iL,g.Zo);g.k=iL.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(C){if(C||this.j==0)this.progress=0,this.coords=this.K;else if(this.isPlaying())return!1;rx(this);this.startTime=C=g.Cd();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.X=this.startTime;this.progress||this.DS();this.hs("play");this.isPaused()&&this.hs("resume");this.j=1;var b=g.B1(this);b in A6||(A6[b]=this);k5$();exC(this,C);return!0};
g.k.stop=function(C){rx(this);this.j=0;C&&(this.progress=1);LRI(this,this.progress);this.onStop();this.dg()};
g.k.pause=function(){this.isPlaying()&&(rx(this),this.j=-1,this.hs("pause"))};
g.k.wO=function(){this.j==0||this.stop(!1);this.hs("destroy");iL.Re.wO.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.uC=function(){this.hs("animate")};
g.k.hs=function(C){this.dispatchEvent(new Zv0(C,this))};
g.bC(Zv0,g.un);g.bC(J6,iL);J6.prototype.N=function(){};
J6.prototype.uC=function(){this.N();J6.Re.uC.call(this)};
J6.prototype.dg=function(){this.N();J6.Re.dg.call(this)};
J6.prototype.DS=function(){this.N();J6.Re.DS.call(this)};
g.bC(YQj,J6);YQj.prototype.N=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.S(oAd,g.O);g.k=oAd.prototype;g.k.listen=function(C,b,h,N){h=(0,g.Il)(h,N||this.K);C=g.Hj(C,b,h);this.j.push(C);return C};
g.k.Zl=function(C,b,h,N){h=(0,g.Il)(h,N||this.K);C=jye(C,b,h);this.j.push(C);return C};
g.k.D9=function(C){g.VJ(C);g.wD(this.j,C)};
g.k.removeAll=function(){g.VJ(this.j);this.j.length=0};
g.k.wO=function(){this.removeAll();g.O.prototype.wO.call(this)};g.S(SQE,g.qK);g.k=SQE.prototype;g.k.load=function(){g.qK.prototype.load.call(this);if(!Qg(this)){var C=g.NcU(this.player.getVideoData());C?(C=G50(C,$0e(this)),UV(this,C,!1)):zxh(this)}};
g.k.unload=function(){UV(this,null);this.X&&(this.X.abort(),this.X=null);g.qK.prototype.unload.call(this)};
g.k.X8=function(C,b){return Qg(this)?C==="loadCustomEndscreenRenderer"?(C=G50(b,"new"),UV(this,C),!0):null:null};
g.k.getOptions=function(){return Qg(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.eC=function(){if(this.endscreen&&this.endscreen.elements){var C=this.player.getVideoContentRect();if(C&&C.width!==0&&C.height!==0){var b=this.player.getPlayerSize();if(b&&b.width!==0&&b.height!==0){var h=C.width/C.height;var N=0;for(var p=-1,P=0;P<Ood.length;P++){var c=Math.abs(b.width-Ood[P]);if(p===-1||N>=c)p=P,N=c}N=vT$[p];this.N&&g.LV(this.N.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(P=this.endscreen.elements[b].id,p=this.K[P],
c=this.W[P],p&&c){var e=c.width*h/c.aspectRatio,L=Math.round(c.width*C.width);P=Math.round(e*C.height);var Z=C.left+Math.round(c.left*C.width),Y=C.top+Math.round(c.top*C.height);g.zV(p.element,L,P);g.Fo(p.element,Z,Y);g.e6(p.element,DNU);L>256||P>256?g.j6(p.element,"ytp-ce-large-round"):L>96||P>96?g.j6(p.element,"ytp-ce-medium-round"):g.j6(p.element,"ytp-ce-small-round");g.e6(p.element,dN0);L=c.left+c.width/2;c=c.top+e/2;g.j6(p.element,L<=.5&&c<=.5?"ytp-ce-top-left-quad":L>.5&&c<=.5?"ytp-ce-top-right-quad":
L<=.5&&c>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.e6(p.element,vT$);g.j6(p.element,N);(p=g.dk(document,"div","ytp-ce-expanding-overlay-body",p.element)[0])&&g.LV(p,"height",P+"px")}}}}};
g.k.onCueRangeEnter=function(C){if(this.endscreen)if(C.getId()==="ytp-ce-in-endscreen")OV(this,this.endscreen.impressionUrls),(C=g.q6())&&this.endscreen.visualElement&&g.bI(C,this.endscreen.visualElement),this.j&&(g.j6(this.j,"ytp-ce-element-show"),this.j.removeAttribute("aria-hidden"),this.player.oS()?g.j6(this.j,"ytp-ce-hide-button-lower"):g.kb(this.j,"ytp-ce-hide-button-lower"));else{C=C.getId().substring(15);var b=this.K[C],h=this.W[C];g.j6(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");
b=this.player.getRootNode();g.j6(b,"ytp-ce-shown");OV(this,h.impressionUrls);(b=g.q6())&&g.bI(b,h.visualElement);this.player.Y().J&&this.player.LO("endscreenelementshown",C)}};
g.k.onCueRangeExit=function(C){if(C.getId()==="ytp-ce-in-endscreen")this.j&&(g.kb(this.j,"ytp-ce-element-show"),this.j.setAttribute("aria-hidden","true"));else{C=C.getId().substring(15);var b=this.K[C];g.kb(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.kb(b,"ytp-ce-shown");this.player.Y().J&&this.player.LO("endscreenelementhidden",C)}};
g.k.ab6=function(C){var b=this;C.target===window&&(new g.wl(function(){for(var h=g.z(Object.values(b.K)),N=h.next();!N.done;N=h.next())g.e6(N.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.k.Kj=function(C){for(var b=g.z(Object.values(this.K)),h=b.next();!h.done;h=b.next())h=h.value,C?h.element.setAttribute("hidden",""):h.element.removeAttribute("hidden")};
g.k.F54=function(C){this.j&&this.player.getRootNode().removeChild(this.j);C&&(g.j6(C,"ytp-ce-hide-button-container"),this.j=C,g.MC(this.player,this.j,4))};
var Ood=[346,426,470,506,570,640,853,1280,1920],vT$="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),dN0=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],DNU=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Rxj={Ulf:"current",Jjh:"new"};var U0$={CLOSE:"close",cj$:"openUrl",SUBSCRIBE:"subscribe"},XJo={M1i:"click",CLOSE:"close",PYp:"hidden",W7p:"rollOut",snf:"rollOver",rsX:"shown"};syD.prototype.p9=function(){var C=Ovj(this,function(b){return b.type==="openUrl"&&b.url!=null});
return C?C.url:null};
var Xhh={iZ$:"anchored",T3:"branding",CHANNEL:"channel",knO:"cta",VLD:"highlightText",ub4:"label",PLAYLIST:"playlist",POPUP:"popup",bS6:"speech",SUBSCRIBE:"subscribe",zjf:"title",VIDEO:"video",hVf:"website"},UN0={T3:"branding",qB4:"card",Nuf:"drawer",Tuf:"highlight",v7p:"marker",euh:"promotion",TEXT:"text",wmO:"widget"};g.S(t6,g.O);g.k=t6.prototype;g.k.addCueRange=function(C,b,h,N,p){C=new g.hk(C,b,{id:h,namespace:"annotations_module"});N&&this.CO.set(C,N);p&&this.m6.set(C,p);this.context.Z.A8([C],1)};
g.k.Sm=function(){this.context.K.subscribe("resize",this.f7,this)};
g.k.Rb=function(){return this.element};
g.k.St=function(C,b,h,N,p,P){if(this.zi)return!1;P&&(P.stopPropagation(),P.preventDefault());this.navigate(C,h,N,p);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.gQ(this.Rb())};
g.k.f7=function(){};
g.k.navigate=function(C,b,h,N){var p=this,P=D$(C);if(P){var c=tYo(P,C.target),e=function(){C.j&&p.context.Z.pauseVideo();var L=p.context.videoData.jS||!1,Z=g.pN(P||"");L&&Z&&(Z.v||Z.list)?p.context.Z.fk(Z.v,b,Z.list,!1):g.dG(P||"",c==="current"?"_top":void 0,b)};
c==="new"&&(e(),e=null);PB(this.context.logger,h,e,N);nAC(P)||(h=g.q6(),N=b.itct,h&&N&&g.gK(h,g.HL(N)))}};
g.k.wO=function(){this.CO.clear();this.m6.clear();g.O.prototype.wO.call(this)};
g.k.createElement=function(C){C=new g.n(C);g.D(this,C);return C.element};g.S(Bwd,t6);g.k=Bwd.prototype;g.k.bN=function(){this.N2&&wx(this,this.N2)};
g.k.isAvailable=function(){var C;if(C=!!this.cards.length)(C=this.Z.getRootNode())?(C=g.Hc(C),C=173<C.width&&173<C.height):C=!1;return C};
g.k.f7=function(){var C=this.isAvailable();g.Vx(this.Rb(),C);g.L2(this.context.Z.getRootNode(),g.Rc.IV_DRAWER_ENABLED,C);my(this.Z)};
g.k.destroy=function(){this.Z.TT(!1);try{this.Z.getRootNode().removeChild(this.X)}catch(C){}g.j8(this.KO);g.yJ(this.rO);this.t4&&this.t4.dispose();this.G&&this.G.dispose();t6.prototype.destroy.call(this)};
g.k.Ru=function(){var C=this;this.context.j.listen(g.WE("iv-drawer-close-button",this.X),"click",this.FY,this);this.context.j.listen(this.K,"touchend",function(){C.q2.start()});
this.context.j.listen(this.K,"scroll",this.Je,this);this.context.K.subscribe("onHideControls",function(){C.Df=!0});
this.context.K.subscribe("onShowControls",function(){C.Df=!1});
this.context.K.subscribe("onVideoAreaChange",function(){C.Df=g.P4(C.Z.getRootNode(),"ytp-autohide")});
this.KO.push(g.Pl("iv-button-shown",this.RWO,this));this.KO.push(g.Pl("iv-button-hidden",this.ngo,this));N2h(this)};
g.k.findLastIndex=function(C){if(this.cards.length===0)return 0;var b=g.B$(this.cards,function(h){return C.U_.startMs>h.U_.startMs||C.U_.startMs===h.U_.startMs&&C.U_.timestamp>=h.U_.timestamp?!0:!1});
return b===-1?0:b+1};
g.k.FY=function(){if(this.N){PB(this.context.logger,Nk(this).aF.close);var C=g.q6();C&&this.J&&g.gK(C,this.J);xo(this)}};
g.k.Je=function(){g.L2(this.X,"iv-drawer-scrolled",this.K.scrollTop>0)};
g.k.RWO=function(){var C=g.q6(),b=Nk(this);b=b?b.O_:this.O_;C&&b&&g.hu(C,[b])};
g.k.ngo=function(){var C=g.q6(),b=Nk(this);b=b?b.O_:this.O_;C&&b&&g.Nb(C,[b])};
g.k.JI=function(){var C=Nk(this);PB(this.context.logger,C.aF.Ci);var b=g.q6();if(b&&C)if(this.Z.D("web_infocards_teaser_show_logging_fix")){var h=[];C.NU&&h.push(C.NU);C.O_&&h.push(C.O_);h.length>0&&g.hu(b,h)}else g.hu(b,[C.NU,C.O_])};
g.k.x8z=function(){var C=g.q6(),b=Nk(this);C&&b&&g.Nb(C,[b.NU])};
g.k.H9=function(C){var b=Nk(this),h=g.q6();this.j?C?(C=this.context.logger,PB(C,b.aF.KY),C.Z.sendVideoStatsEngageEvent(4,void 0),h&&b.NU&&g.gK(h,b.NU)):(C=this.context.logger,PB(C,b.aF.KY),C.Z.sendVideoStatsEngageEvent(4,void 0),h&&b.O_&&g.gK(h,b.O_)):(C=this.context.logger,PB(C,b.aF.KY),C.Z.sendVideoStatsEngageEvent(4,void 0),h&&this.O_&&g.gK(h,this.O_))};g.S(g5,t6);g5.prototype.Sm=function(){t6.prototype.Sm.call(this);eno(this)};
g5.prototype.show=function(){t6.prototype.show.call(this);var C=g.q6(),b=this.annotation.data;C&&b&&(b=b.session_data)&&g.hu(C,[g.HL(b.itct)])};
g5.prototype.hide=function(){t6.prototype.hide.call(this);var C=g.q6(),b=this.annotation.data;C&&b&&(b=b.session_data)&&g.Nb(C,[g.HL(b.itct)])};g.S(pq,g5);
pq.prototype.show=function(){if(!this.isActive){g5.prototype.show.call(this);if(!this.J){g.j6(this.Rb(),"iv-branding");var C=this.annotation.data;this.K=this.createElement({B:"img",J4:["branding-img","iv-click-target"],T:{"aria-label":"Channel watermark",src:C.image_url,width:C.image_width,height:C.image_height}});g.Vx(this.K,!1);var b=this.createElement({B:"button",J4:["branding-img-container","ytp-button"]});b.appendChild(this.K);this.Rb().appendChild(b);var h=this.annotation.p9();h&&TP(this,b,
h,this.annotation.id,C.session_data);this.context.Z.D("disable_branding_context")||aqI(this,C);this.J=!0}g.Vx(this.Rb(),!0);this.isActive=!0;if(this.K){try{Loh(this,this.K)}catch(N){}g.j6(this.context.Z.getRootNode(),"ytp-branding-shown");this.context.Z.getRootNode().style.setProperty("--branding-image-width",this.K.getAttribute("width")+"px")}}};
pq.prototype.hide=function(){this.isActive&&(g5.prototype.hide.call(this),g.Vx(this.Rb(),!1),this.isActive=!1,g.kb(this.context.Z.getRootNode(),"ytp-branding-shown"))};
pq.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);g.kb(this.context.Z.getRootNode(),"ytp-branding-shown");g5.prototype.destroy.call(this)};g.S(oTj,g5);g.k=oTj.prototype;g.k.show=function(){this.isActive||(g5.prototype.show.call(this),this.V||(GCI(this),this.V=!0),g.Vx(this.Rb(),!0),g.Vh(function(){g.kb(this.Rb(),"iv-promo-inactive")},100,this),this.Rb().removeAttribute("aria-hidden"),this.isActive=!0,Hoh(this),SNC(this),$Nj(this,this.W))};
g.k.hide=function(){this.isActive&&(g.j6(this.Rb(),"iv-promo-inactive"),this.isActive=!1,this.Rb().setAttribute("aria-hidden","true"))};
g.k.St=function(C,b,h,N,p,P){return this.isCollapsed?!1:g5.prototype.St.call(this,C,b,h,N,p,P)};
g.k.wED=function(C){this.L=!0;FoC(this,500,C)};
g.k.XEi=function(){this.L=!1;znd(this)};
g.k.Ifp=function(C){C.stopPropagation();this.hide()};
g.k.vhi=function(C){C.stopPropagation();Hoh(this);this.isCollapsed=!0;g.j6(this.Rb(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();g5.prototype.destroy.call(this)};g.S(M9e,g.qK);g.k=M9e.prototype;g.k.X8=function(C,b){if(!seU(this.player.Y().playerStyle))return null;switch(C){case "loadCustomAnnotationsXml":return(C=g.Tr(b))&&yQU(this,C),!0;case "removeCustomAnnotationById":return b&&this.j&&(Cq0(this.j,b),my(this.player)),!0}return null};
g.k.getOptions=function(){return seU(this.player.Y().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Fa=function(){var C=this.player.Y(),b=this.player.getVideoData(),h=C.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.Ev(b)||this.player.isMutedByEmbedsMutedAutoplay()?!1:h===1&&!b.b0||C.Df.get(b.videoId)||g.MF(b)||g.qF(b)?!0:!1};
g.k.bD=function(){if(this.N){var C=this.player.Ti().getVideoContentRect(!0);g.zV(this.N.element,C.width,C.height);g.Fo(this.N.element,C.left,C.top)}if(this.j){var b=this.player.f2();C=this.j;b=b.width;g.L2(C.X,"iv-drawer-small",b<=426);g.L2(C.X,"iv-drawer-big",b>=1280)}};
g.k.QN=function(C){mND(this,C.state);g.B(C.state,2)&&(this.oS()&&this.Fh()&&this.player.getPresentingPlayerType()!==2&&this.Vk(!1),this.TT(!1))};
g.k.load=function(){function C(c){var e=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===e&&b.player.getVideoData().videoId===N&&(c=g.la(c)&&c.responseXML?c.responseXML:null)&&(yQU(b,c),g.j6(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.qK.prototype.load.call(this);mND(this,this.player.getPlayerStateObject());this.loadNumber++;var h=this.player.getVideoData(),N=h.videoId;g.bf()&&(C=rQD(this,C));var p={format:"XML",onFinish:C,onError:function(){b.G=null},
urlParams:{}};h.isPharma&&(p.urlParams.pharma="1");p.method="POST";p.withCredentials=!0;var P=this.player.Y().Df.get(N);P&&ioE(p,P);P=P&&(P.Ii||P.ij);if(!h.l6||P)h.m6?fqE(this,h.m6,p):(this.J=function(){if(!b.L)b.onVideoDataChange(p);var c=b.player.getVideoData();(c==null?0:g.V4(c))&&!b.KO&&Qep(b,c)},this.player.addEventListener("videodatachange",this.J));
g.MC(this.player,this.N.element,4);this.bD();(P=g.MF(h))&&Rno(this,P);(P=g.qF(h))&&P.featuredChannel&&KoD(this,P.featuredChannel,P.annotationId||"branding",h.videoId||null,h.eventId||null);this.JL=g.WE("ytp-cards-button",this.player.getRootNode());g.V4(h)&&Qep(this,h)};
g.k.onVideoDataChange=function(C){var b=this.player.getVideoData();b.m6&&fqE(this,b.m6,C)};
g.k.unload=function(){this.player.Sh("annotations_module");for(var C=g.z(Object.keys(this.W)),b=C.next();!b.done;b=C.next())this.W[b.value].destroy();this.V=null;this.j&&(this.j.destroy(),this.j=null,my(this.player));this.L=!1;this.G&&(this.G.abort(),this.G=null);this.KO=!1;this.W={};this.K.hide();g.qK.prototype.unload.call(this);this.N.detach();this.J&&(this.player.removeEventListener("videodatachange",this.J),this.J=null)};
g.k.mG=function(C){C===this.player.getVideoData().videoId&&(this.loaded?JQU(this):this.load())};
g.k.oS=function(){var C;return((C=this.j)==null?void 0:C.isAvailable())||this.KO};
g.k.Fh=function(){return!!this.j&&this.j.N};
g.k.Vk=function(C,b,h){b=b===void 0?!1:b;this.oS();this.j&&(C?h?IP(this.j,h,b):IP(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):xo(this.j))};
g.k.TT=function(C,b){this.player.publish(C?"cardsteasershow":"cardsteaserhide",b)};
g.k.wO=function(){this.player.Y().Df.unsubscribe("vast_info_card_add",this.mG,this);g.kb(this.player.getRootNode(),g.Rc.IV_DRAWER_OPEN);for(var C=this.N2,b=g.dl,h=0,N=C.length;h<N;h++)b.E2(C[h]);this.N2.length=0;g.qK.prototype.wO.call(this)};
g.k.createElement=function(C){C=new g.n(C);g.D(this,C);return C.element};g.MK("annotations_module",M9e);g.MK("creatorendscreen",SQE);})(_yt_player);
