(function(g){var window=this;'use strict';var nTE=function(C,b,h){g.R(function(N){C.j=g.mt(b,h);g.SV(N)})},cB=function(C){C.isActive()||C.start()},t90=function(C,b){return b?C.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},T2D=function(C){return g.Oa(C)||C.D("web_enable_caption_language_preference_stickiness")},B2j=function(C,b){var h=new g.gF;
h.languageCode=C.languageCode;h.languageName=C.languageName;h.name=C.name;h.displayName=C.displayName;h.kind=C.kind;h.isDefault=!1;h.j=C.j;h.isTranslateable=C.isTranslateable;h.vssId=C.vssId;h.url=C.url;h.translationLanguage=b;C.xtags&&(h.xtags=C.xtags);C.captionId&&(h.captionId=C.captionId);return h},Iqj=function(C,b){var h,N,p;
return g.R(function(P){if(P.j==1)return h=C+"|"+b,g.J(P,g.wm(),2);if(P.j!=3){N=P.K;if(!N)throw g.zn("gct");return g.J(P,g.H7(N),3)}p=P.K;return P.return(p.get("captions",h))})},xNd=function(C,b,h){Iqj(C,b).then(function(N){N&&h(N.trackData,new g.gF(N.metadata))})},bRE=function(C){if(!whD.test(C))throw Error("'"+C+"' is not a valid hex color");
C.length==4&&(C=C.replace(CF$,"#$1$1$2$2$3$3"));C=C.toLowerCase();C=parseInt(C.slice(1),16);return[C>>16,C>>8&255,C&255]},h4j=function(){var C=void 0;
C=C===void 0?{}:C;var b="suggest_correction"in g.MoE?g.MoE.suggest_correction:"Edit caption";b=b||"";var h={},N;for(N in C){h={OD:h.OD};h.OD=N;var p=function(P){return function(){return String(C[P.OD])}}(h);
b=b.replace(new RegExp("\\$\\{"+h.OD+"\\}","gi"),p);b=b.replace(new RegExp("\\$"+h.OD,"gi"),p)}return b},Nkh=function(){return g.R1("yt-player-caption-display-settings")},kx=function(){this.segments=[]},gvE=function(C,b){var h=g.c5(C.segments,b);
h>=0||h<0&&(-h-1)%2===1||(h=-h-1,h>0&&b-C.segments[h-1]===1&&h<C.segments.length&&C.segments[h]-b===1?(g.xI(C.segments,h),g.xI(C.segments,h-1)):h>0&&b-C.segments[h-1]===1?C.segments[h-1]=b:h<C.segments.length&&C.segments[h]-b===1?C.segments[h]=b:(g.P5(C.segments,h,0,b),g.P5(C.segments,h+1,0,b)))},pEd=function(C,b,h,N,p,P){g.O.call(this);
this.policy=C;this.player=b;this.KO=h;this.L=N;this.G=p;this.V=P;this.X=new kx;this.W=-1;this.N=this.K=this.j=null;this.N2=0;this.J=new g.wl(this.dc,1E3,this);this.events=new g.Jm(this);g.D(this,this.J);g.D(this,this.events);this.events.S(b,"SEEK_COMPLETE",this.HQ);this.HQ();this.dc()},PF0=function(C){return C.j&&C.j.cF?C.j.cF+C.player.Z9()<C.player.getCurrentTime():!1},jVU=function(C,b){if(C.policy.nS&&C.player.Bm()){var h=g.i0(b,C.policy,{});
h.set("pot",C.player.Bm());h=h.p9()}else h=g.i0(b,C.policy,{}).p9();var N={format:"RAW",withCredentials:!0};if(C.policy.Qz){N.method="POST";var p=b.X;p&&Object.keys(p).length>0?N.postBody=g.pY(p,g.Dp):N.postBody=(0,g.e4)([120,0])}C.G&&(N.responseType="arraybuffer");var P=++C.N2,c=(0,g.fB)();C.N=g.rJ(h,N,3,100).then(function(e){if(C.policy.Y5&&P%100===1){var L=(0,g.fB)();C.player.jp("caprsp",{rn:P,ms:L-c,kb:(e.xhr.responseText.length/1024).toFixed()})}a:{e=e.xhr;C.HE();if(C.K){var Z=!(C.G?e.response:
e.responseText)||e.status>=400;if(L=g.m8W(e)){e=g.i0(C.K,C.policy,{});C.K.p5(e,L);jVU(C,C.K);break a}Z?C.player.jp("capfail",{status:e.status}):(C.player.FX().Jy("fcb_r"),L=C.K.UX[0].yz,C.L!=null&&C.W!==L&&(Z=C.K.UX[0],C.G?C.L(e.response,(Z.startTime+C.player.Z9())*1E3):C.L(e.responseText,(Z.startTime+C.player.Z9())*1E3),C.W=L))}C.K=null;C.N=null}}).jX(function(e){C.K=null;
C.N=null;var L;C.player.jp("capfail",{rn:P,status:(L=e.xhr)==null?void 0:L.status})});
C.K=b;gvE(C.X,C.K.UX[0].yz)},ey=function(C,b){g.fP.call(this,b);
this.j=C;this.Z=b;this.N=null;this.W=!1;this.logger=new g.ty("caps");this.J=g.Va(this.Z.Y())&&!this.j.isManifestless},kAD=function(C,b){var h=[],N;
for(N in C.j.j)if(C.j.j.hasOwnProperty(N)){var p=C.j.j[N];if(g.yi(p,b||null)){var P=p.info.id,c=P,e="."+P,L="",Z="";if(p=p.info.captionTrack)P=p.languageCode,c=p.displayName,e=p.vssId,L=p.kind,Z=p.id;else{p=P;var Y=g.tH0.get(p);Y==null&&(Y=c8h[p]||c8h[p.replace(/-/g,"_")],g.tH0.set(p,Y));p=Y;c=p||c}h.push(new g.gF({id:N,languageCode:P,languageName:c,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:e,kind:L,captionId:Z}))}}return h},e4E=function(C,b){return b!=null&&b in C.j.j?C.j.j[b]:null},
LgE=function(C,b,h){var N=[],p;
for(p in C.j.j)if(C.j.j.hasOwnProperty(p)){var P=C.j.j[p];if(g.yi(P,h||null)){var c=P.info.captionTrack;c&&c.languageCode===b&&N.push(P)}}return N.length?N[0]:null},Lq=function(C,b,h,N,p,P,c,e,L,Z){var Y=Z.isInline()&&!0,a={};
Object.assign(a,b);Object.assign(a,C.params);Object.assign(a,h);var l={};Object.assign(l,b.nK);C.params.nK&&Object.assign(l,C.params.nK);Object.assign(l,h.nK);Y&&(a.windowOpacity=.6,l.backgroundOpacity=0);a.nK=l;var F=a.P2===1,G=[{B:"span",C:"captions-text",T:{style:"word-wrap: normal; display: block;"}}],V,q,f;(e=e.Fo("caption_edit_on_hover")&&((V=Z.getVideoData().getPlayerResponse())==null?void 0:(q=V.captions)==null?void 0:(f=q.playerCaptionsTracklistRenderer)==null?void 0:f.openTranscriptCommand))&&
G.unshift({B:"button",C:"caption-edit",T:{tabindex:"0","aria-label":h4j()},U:[{B:"svg",T:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},U:[{B:"path",T:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.n.call(this,{B:"div",C:"caption-window",T:{id:"caption-window-"+C.id,dir:F?"rtl":"ltr",tabindex:"0",lang:a.lang},U:G});var y=
this;this.J=[];this.sX=!1;this.K=C;this.Df=this.Qz=null;this.playerWidth=P;this.playerHeight=c;this.L=null;this.maxWidth=P*.96;this.maxHeight=c*.96;this.j=a;this.IV=h;this.N2=b;this.X=this.dO("captions-text");this.SC=this.X.style.getPropertyValue("box-decoration-break")!==""||this.X.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.t4=ZRC(N,p,P,c);this.AZ=L;e&&(this.W=this.dO("caption-edit"),this.S(this.W,"click",function(){y.AZ()}));
this.type=0;this.m6=this.t4*Yij(l);this.G$=Y;C=new g.IY(this.element,!0);g.D(this,C);C.subscribe("dragstart",this.rd,this);C.subscribe("dragmove",this.MA,this);C.subscribe("dragend",this.yN,this);this.kh=this.Yh=this.Vz=this.zi=0;C="";this.j.windowOpacity&&(C=bRE(this.j.windowColor),C="rgba("+C[0]+","+C[1]+","+C[2]+","+this.j.windowOpacity+")");b={"background-color":C,display:this.j.isVisible===!1?"none":"","text-align":aZC[this.j.textAlign]};this.SC&&(b["border-radius"]=C?this.m6/8+"px":"");(this.N=
this.K.params.P2===2||this.K.params.P2===3)&&lZo(this,this.element);g.LV(this.element,b);if(Y){var u;(u=this.element.parentElement)==null||u.style.setProperty("--caption-window-color",C)}switch(this.j.W5){case 0:case 1:case 2:g.j6(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.j6(this.element,"ytp-caption-window-bottom")}},lZo=function(C,b){var h="vertical-rl";
C.j.lw===1&&(h="vertical-lr");g.le&&(h=h==="vertical-lr"?"tb-lr":"tb-rl");g.LV(b,"-o-writing-mode",h);g.LV(b,"-webkit-writing-mode",h);g.LV(b,"writing-mode",h);g.LV(b,"text-orientation","upright");g.j6(b,"ytp-vertical-caption");C.K.params.P2===3&&(g.LV(b,"text-orientation",""),g.LV(b,"transform","rotate(180deg)"))},Yij=function(C){var b=1+.25*(C.fontSizeIncrement||0);
if(C.offset===0||C.offset===2)b*=.8;return b},ovd=function(C,b){var h={},N=b.background?b.background:C.j.nK.background;
if(b.backgroundOpacity!=null||b.background){var p=b.backgroundOpacity!=null?b.backgroundOpacity:C.j.nK.backgroundOpacity;N=bRE(N);h.background="rgba("+N[0]+","+N[1]+","+N[2]+","+p+")";C.SC&&(h["box-decoration-break"]="clone",h["border-radius"]=C.m6/8+"px")}if(b.fontSizeIncrement!=null||b.offset!=null)h["font-size"]=C.t4*Yij(b)+"px";N=1;p=b.color||C.j.nK.color;if(b.color||b.textOpacity!=null)p=bRE(p),N=b.textOpacity==null?C.j.nK.textOpacity:b.textOpacity,p="rgba("+p[0]+","+p[1]+","+p[2]+","+N+")",
h.color=p,h.fill=p;var P=b.charEdgeStyle;P===0&&(P=void 0);if(P){p="rgba(34, 34, 34, "+N+")";var c="rgba(204, 204, 204, "+N+")";b.vJ&&(c=p=b.vJ);var e=C.t4/16/2,L=Math.max(e,1),Z=Math.max(2*e,1),Y=Math.max(3*e,1),a=Math.max(5*e,1);N=[];switch(P){case 4:for(;Y<=a;Y+=e)N.push(Z+"px "+Z+"px "+Y+"px "+p);break;case 1:Z=window.devicePixelRatio>=2?.5:1;for(P=L;P<=Y;P+=Z)N.push(P+"px "+P+"px "+p);break;case 2:N.push(L+"px "+L+"px "+c);N.push("-"+L+"px -"+L+"px "+p);break;case 3:for(Y=0;Y<5;Y++)N.push("0 0 "+
Z+"px "+p)}h["text-shadow"]=N.join(", ")}p="";switch(b.fontFamily){case 1:p='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:p='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:p='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:p='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:p='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:p=g.WQ()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:p='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}p&&(h["font-family"]=p);p=b.offset;p==null&&(p=C.j.nK.offset);switch(p){case 0:h["vertical-align"]="sub";break;case 2:h["vertical-align"]="super"}b.fontFamily===7&&(h["font-variant"]="small-caps");b.bold&&(h["font-weight"]="bold");b.italic&&(h["font-style"]="italic");b.underline&&(h["text-decoration"]=
"underline");b.r4h&&(h.visibility="hidden");b.Hv===1&&C.N&&(h["text-combine-upright"]="all",h["text-orientation"]="mixed",p=g.d_||g.Sn,C.K.params.P2===3?h.transform=p?"rotate(90deg)":"rotate(180deg)":p&&(h.transform="rotate(-90deg)"));if(b.Ea===1||b.Ea===2||b.Ea===3||b.Ea===4||b.Ea===5)if(g.d_)h["font-weight"]="bold";else switch(h["text-emphasis-style"]="filled circle",h["text-emphasis-color"]="currentcolor",h["webkit-text-emphasis"]="filled circle",b.Ea){case 4:case 3:h["text-emphasis-position"]=
"under left";h["webkit-text-emphasis-position"]="under left";break;case 5:case 2:h["text-emphasis-position"]="over right",h["webkit-text-emphasis-position"]="over right"}return h},Z3=function(C){C=C.split("px");
return C.length>0?(C=Number(C[0]))?C:0:0},Fge=function(C){C.L=g.wk("SPAN");
g.LV(C.L,{display:"block"});g.j6(C.L,"caption-visual-line");C.X.appendChild(C.L)},GAh=function(C,b){var h=g.wk("SPAN");
g.LV(h,{display:"inline-block","white-space":"pre-wrap"});g.LV(h,ovd(C,b));h.classList.add("ytp-caption-segment");C.L.appendChild(h);h.previousElementSibling&&(g.LV(h.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.LV(h,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return h},Si0=function(C,b,h){C.sX=C.sX||!!h;
var N={};Object.assign(N,C.j.nK);Object.assign(N,h||b.j);Object.assign(N,C.IV.nK);(h=!C.L)&&Fge(C);for(var p=C.Qz&&C.Df&&g.rk(N,C.Df)?C.Qz:GAh(C,N),P=typeof b.text==="string",c=P?b.text.split("\n"):[b.text],e=0;e<c.length;e++){var L=e>0||!b.append,Z=c[e];L&&!h?(Fge(C),p=GAh(C,N)):L&&h&&(h=!1);Z&&(p.appendChild(P?g.CM(Z):Z),P||Z.tagName!=="RUBY"||Z.childElementCount!==4||g.d_||!g.YX(Z.children[2],"text-emphasis")||(L=C.N?"padding-right":"padding-top",g.YX(Z.children[2],"text-emphasis-position")&&(L=
C.N?"padding-left":"padding-bottom"),g.TA?g.LV(p,L,"1em"):g.LV(p,L,"0.5em")))}C.Df=N;C.Qz=p;C.J.push(b)},ZRC=function(C,b,h,N){var p=b/360*16;
b>=C&&(C=640,N>h*1.3&&(C=480),p=h/C*16);return p},z4E=function(){this.N=this.time=this.mode=this.K=0;
this.X=new $eD(this);this.G=new $eD(this);this.j=[];this.clear()},VeE=function(C,b,h){if(C===255&&b===255||!C&&!b)return{eP:C,
RT:b,result:0};C=HRD[C];b=HRD[b];if(C&128){var N;if(N=!(b&128))N=b,N=h.bF()&&h.RT===N;if(N)return{eP:C,RT:b,result:1}}else if(b&128&&1<=C&&C<=31)return{eP:C,RT:b,result:2};return{eP:C,RT:b,result:3}},qiC=function(C,b,h,N){b===255&&h===255||!b&&!h?(++C.N===45&&C.reset(),C.X.K.clear(),C.G.K.clear()):(C.N=0,MeD(C.X,b,h,N))},meD=function(C,b){C.j.sort(function(p,P){var c=p.time-P.time;
return c===0?p.order-P.order:c});
for(var h=g.z(C.j),N=h.next();!N.done;N=h.next())N=N.value,C.time=N.time,N.type===0?qiC(C,N.Xf,N.wR,b):N.type===1&&C.K&496&&MeD(C.G,N.Xf,N.wR,b);C.j.length=0},Yx=function(){this.type=0},aB=function(){this.state=this.RT=this.eP=0},fZe=function(){this.timestamp=this.j=0},l5=function(C){this.G=C;
this.N=[];this.j=this.K=this.row=0;this.style=new Yx;for(C=this.X=0;C<=15;C++){this.N[C]=[];for(var b=0;b<=32;b++)this.N[C][b]=new fZe}},oB=function(C,b){if(C.style.type===3){for(var h=0,N=0,p=C.G.time+0,P="",c="",e=p,L=1;L<=15;++L){for(var Z=!1,Y=N?N:1;Y<=32;++Y){var a=C.N[L][Y];
if(a.j!==0){h===0&&(h=L,N=Y);Z=String.fromCharCode(a.j);var l=a.timestamp;l<p&&(p=l);a.timestamp=e;c&&(P+=c,c="");P+=Z;Z=!0}if((a.j===0||Y===32)&&Z){c="\n";break}else if(N&&!Z)break}if(h&&!Z)break}P&&b.X(h,N,p,e,P)}else for(N=h=0,P=p=C.G.time+0,c=1;c<=15;++c)for(e="",L=1;L<=32;++L)if(Y=C.N[c][L],a=Y.j,a!==0&&(h===0&&(h=c,N=L),Z=String.fromCharCode(a),l=Y.timestamp,l<=p&&(p=l),e+=Z,Y.reset()),L===32||a===0)e&&b.X(h,N,p,P,e),p=P,e="",N=h=0},J8j=function(C,b){switch(C){case 0:return A8D[(b&127)-32];
case 1:return y8E[b&15];case 2:return r8d[b&31];case 3:return iR$[b&31]}return 0},Fa=function(C){return C.N[C.row][C.K]},GJ=function(C,b,h){b>=2&&C.K>1&&(--C.K,Fa(C).j=0);
var N=Fa(C);N.timestamp=C.G.time+0;N.j=J8j(b,h);C.K<32&&C.K++},ud$=function(C,b,h,N){for(var p=0;p<N;p++)for(var P=0;P<=32;P++){var c=C.N[b+p][P],e=C.N[h+p][P];
c.j=e.j;c.timestamp=e.timestamp}},Sy=function(C,b,h){for(var N=0;N<h;N++)for(var p=0;p<=32;p++)C.N[b+N][p].reset()},R4p=function(C){C.row=C.j>0?C.j:1;
C.K=1;Sy(C,0,15)},QV0=function(C){this.N=C;
this.G=0;this.style=new Yx;this.W=new l5(this.N);this.J=new l5(this.N);this.text=new l5(this.N);this.K=this.W;this.X=this.J;this.j=this.K},Uej=function(C,b,h){var N=C.K,p=!1;
switch(C.style.get()){case 4:case 1:case 2:C.style.get()===4&&N.j>0||(oB(N,h),R4p(C.K),R4p(C.X),N.row=15,N.j=b,p=!0)}C.style.set(3);C.j=N;C.j.style=C.style;C.N.mode=1<<N.X;p?N.K=1:N.j!==b&&(N.j>b?(oB(N,h),Sy(N,N.row-N.j,b)):N.row<b&&(b=N.j),N.j=b)},XEe=function(C){C.style.set(1);
C.j=C.X;C.j.j=0;C.j.style=C.style;C.N.mode=1<<C.j.X},KgC=function(C){C.style.set(4);
C.j=C.text;C.j.style=C.style;C.N.mode=1<<C.j.X},$eD=function(C){this.j=C;
this.G=0;this.N=new QV0(this.j);this.W=new QV0(this.j);this.K=new aB;this.X=this.N},MeD=function(C,b,h,N){C.K.update();
b=VeE(b,h,C.K);switch(b.result){case 0:return;case 1:case 2:return}var p=b.eP;h=b.RT;if(32<=p||!p)C.j.mode&C.j.K&&(b=p,b&128&&(b=127),h&128&&(h=127),C=C.X.j,b&96&&GJ(C,0,b),h&96&&GJ(C,0,h),b!==0&&h!==0&&C.style.type===3&&oB(C,N));else if(p&16)a:if(!C.K.matches(p,h)&&(b=C.K,b.eP=p,b.RT=h,b.state=2,b=p&8?C.W:C.N,C.X=b,C.j.mode=1<<(C.G<<2)+(b.G<<1)+(b.style.type===4?1:0),(C.j.mode|1<<(C.G<<2)+(b.G<<1)+(b.style.type!==4?1:0))&C.j.K))if(h&64){N=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(p&7)<<1|h>>5&1];
C=h&16?((h&14)>>1)*4:0;h=b.j;switch(b.style.get()){case 4:N=h.row;break;case 3:if(N!==h.row){if(N<h.j&&(N=h.j,N===h.row))break;var P=1+h.row-h.j,c=1+N-h.j;ud$(h,c,P,h.j);b=P;p=h.j;c<P?(P=c+p-P,P>0&&(b+=P,p-=P)):(P=P+p-c,P>0&&(p-=P));Sy(h,b,p)}}h.row=N;h.K=C+1}else switch(p&7){case 1:switch(h&112){case 32:GJ(b.j,0,32);break a;case 48:h===57?(N=b.j,Fa(N).j=0,N.K<32&&N.K++):GJ(b.j,1,h&15)}break;case 2:h&32&&GJ(b.j,2,h&31);break;case 3:h&32&&GJ(b.j,3,h&31);break;case 4:case 5:if(32<=h&&h<=47)switch(h){case 32:XEe(b);
break;case 33:N=b.j;N.K>1&&(--N.K,Fa(N).j=0);break;case 36:N=b.j;b=Fa(N);for(C=0;C<=15;C++)for(h=0;h<=32;h++)if(N.N[C][h]===b){for(;h<=32;h++)N.N[C][h].reset();break}break;case 37:Uej(b,2,N);break;case 38:Uej(b,3,N);break;case 39:Uej(b,4,N);break;case 40:GJ(b.j,0,32);break;case 41:b.style.set(2);b.j=b.K;b.j.j=0;b.j.style=b.style;b.N.mode=1<<b.j.X;break;case 42:N=b.text;N.j=15;N.style.set(4);R4p(N);KgC(b);break;case 43:KgC(b);break;case 44:C=b.K;switch(b.style.get()){case 1:case 2:case 3:oB(C,N)}Sy(C,
0,15);break;case 45:b:{C=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(C.row<15){++C.row;C.K=1;break b}break;case 3:}C.j<2&&(C.j=2,C.row<C.j&&(C.row=C.j));b=C.row-C.j+1;oB(C,N);ud$(C,b,b+1,C.j-1);Sy(C,C.row,1)}break;case 46:Sy(b.X,0,15);break;case 47:oB(b.K,N),b.X.updateTime(b.N.time+0),N=b.X,b.X=b.K,b.K=N,XEe(b)}break;case 7:switch(h){case 33:case 34:case 35:N=b.j,(N.K+=h&3)>32&&(N.K=32)}}},sV$=function(){},$x=function(C,b,h,N,p,P,c){P=P===void 0?!1:P;
c=c===void 0?null:c;g.hk.call(this,C,C+b,{priority:h,namespace:"captions"});this.windowId=N;this.text=p;this.append=P;this.j=c},vvo=function(C,b,h,N,p,P,c){var e=P[0],L=c[e.getAttribute("p")];
if(L.Dv===1){var Z=P[1],Y=P[2];P=P[3];e.getAttribute("t");Z.getAttribute("t");Y.getAttribute("t");P.getAttribute("t");e.getAttribute("p");Z.getAttribute("p");P.getAttribute("p");c=c[Y.getAttribute("p")];e=ORD(e.textContent,Z.textContent,Y.textContent,P.textContent,c);return new $x(C,b,p,h,e,N,L)}switch(L.Dv){case 9:case 10:L.Ea=1;break;case 11:L.Ea=2;break;case 12:L.Ea=3;break;case 13:L.Ea=4;break;case 14:L.Ea=5}return new $x(C,b,p,h,e.textContent||"",N,L)},ORD=function(C,b,h,N,p){var P=g.WQ(),c=
P?g.wk("DIV"):g.wk("RUBY"),e=g.wk("SPAN");
e.textContent=C;c.appendChild(e);C=P?g.wk("DIV"):g.wk("RP");C.textContent=b;c.appendChild(C);b=P?g.wk("DIV"):g.wk("RT");b.textContent=h;c.appendChild(b);h=p.Dv;if(h===10||h===11||h===12||h===13||h===14)if(g.LV(b,"text-emphasis-style","filled circle"),g.LV(b,"text-emphasis-color","currentcolor"),g.LV(b,"webkit-text-emphasis","filled circle"),p.Dv===11||p.Dv===13)g.LV(b,"webkit-text-emphasis-position","under left"),g.LV(b,"text-emphasis-position","under left");h=!0;if(p.Dv===4||p.Dv===7||p.Dv===12||
p.Dv===14)g.LV(c,"ruby-position","over"),g.LV(c,"-webkit-ruby-position","before");else if(p.Dv===5||p.Dv===6||p.Dv===11||p.Dv===13)g.LV(c,"ruby-position","under"),g.LV(c,"-webkit-ruby-position","after"),h=!1;p=P?g.wk("DIV"):g.wk("RP");p.textContent=N;c.appendChild(p);P&&(N=h,g.LV(c,{display:"inline-block",position:"relative"}),P=c.firstElementChild.nextElementSibling,g.LV(P,"display","none"),P=P.nextElementSibling,g.LV(P,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.LV(c.lastElementChild,"display","none"),N?(g.LV(c,"padding-top","0.6em"),g.LV(P,"top","0")):(g.LV(c,"padding-bottom","0.6em"),g.LV(P,"bottom","0")));return c},zJ=function(){g.O.apply(this,arguments)},HB=function(C,b,h,N,p){g.hk.call(this,C,C+b,{priority:h,
namespace:"captions"});this.id=N;this.params=p;this.j=[]},Dee=function(C){var b="_"+V5++;
return new HB(0,0x8000000000000,0,b,C)},Mk=function(C){zJ.call(this);
this.N=C;this.pens={};this.J={};this.L={};this.X="_"+V5++;this.W={};this.K=this.j=null;this.G=!0},qk=function(C,b){C=C.getAttribute(b);
if(C!=null)return Number(C)},m4=function(C,b){C=C.getAttribute(b);
if(C!=null)return C==="1"},fq=function(C,b){C=qk(C,b);
return C!==void 0?C:null},y5=function(C,b){C=C.getAttribute(b);
if(C!=null)return As.test(C),C},deC=function(C,b){var h={},N=b.getAttribute("ws");
Object.assign(h,N?C.L[N]:C.N);C=fq(b,"mh");C!=null&&(h.nG=C);C=fq(b,"ju");C!=null&&(h.textAlign=C);C=fq(b,"pd");C!=null&&(h.P2=C);C=fq(b,"sd");C!=null&&(h.lw=C);C=y5(b,"wfc");C!=null&&(h.windowColor=C);b=qk(b,"wfo");b!==void 0&&(h.windowOpacity=b/255);return h},WgI=function(C,b){var h={},N=b.getAttribute("wp");
N&&Object.assign(h,C.J[N]);C=fq(b,"ap");C!=null&&(h.W5=C);C=qk(b,"cc");C!=null&&(h.qk=C);C=qk(b,"ah");C!=null&&(h.uY=C);C=qk(b,"rc");C!=null&&(h.h$=C);b=qk(b,"av");b!=null&&(h.Dm=b);return h},Evd=function(C,b,h,N){var p={};
Object.assign(p,WgI(C,b));Object.assign(p,deC(C,b));N?g.rk(p,C.N)?(N=C.X,p=C.N):N="_"+V5++:N=b.getAttribute("id")||"_"+V5++;C=qk(b,"t")+h;b=qk(b,"d")||0x8000000000000;if(p.P2===2||p.P2===3)h=p.h$,p.h$=p.qk,p.qk=h;return new HB(C,b,0,N,p)},r5=function(C){zJ.call(this);
this.G=C;this.j=new Map;this.N=new Map;this.X=new Map;this.K=new Map},i5=function(C){C=g.cE(Math.round(C),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-C.length)+C},nvI=function(C,b,h,N,p){N===0&&(N=0x8000000000000);
var P={};b.wpWinPosId&&Object.assign(P,C.N.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(P,C.X.get(b.wsWinStyleId));C=b.rcRowCount;C!==void 0&&(P.h$=C);b=b.ccColCount;b!==void 0&&(P.qk=b);if(P.P2===2||P.P2===3)b=P.h$,P.h$=P.qk,P.qk=b;return new HB(h,N,0,p,P)},Js=function(C,b,h){g.fP.call(this,C);
this.videoData=b;this.audioTrack=h;this.G=b.i6},u5=function(C,b,h,N,p,P,c,e,L,Z){Lq.call(this,C,b,h,N,p,P,c,e,L,Z);
this.type=1},RB=function(C,b,h){this.trackData=C;
this.W=h;this.version=this.G=this.N=this.byteOffset=0;this.K=[];this.j=new DataView(this.trackData)},Q5=function(C){var b=C.byteOffset;
C.byteOffset+=1;return C.j.getUint8(b)},U6=function(C){var b=C.byteOffset;
C.byteOffset+=4;return C.j.getUint32(b)},Xa=function(C,b){zJ.call(this);
this.K=C;this.N=b;this.track=this.N.languageName==="CC3"?4:0;this.j=new z4E;this.j.K=1<<this.track},TkE=function(C){if(typeof C==="string")return!1;
C=new RB(C,8,0);return te$(C)},te$=function(C){if(!(C.byteOffset<C.j.byteLength)||U6(C)!==1380139777)return!1;
C.version=Q5(C);if(C.version>1)return!1;Q5(C);Q5(C);Q5(C);return!0},Kq=function(C,b,h,N,p,P,c,e,L,Z){Lq.call(this,C,b,h,N,p,P,c,e,L,Z);
var Y=this;this.type=2;this.nO=[];this.KO=this.V=this.rO=0;this.q2=NaN;this.ob=0;this.Yg=null;this.CO=new g.wl(this.c86,433,this);this.W&&(Z.createClientVe(this.W,this,167342),this.S(this.W,"click",function(){Z.logClick(Y.W)}),C=new g.IY(this.element,!0),g.D(this,C),C.subscribe("hoverstart",function(){Z.logVisibility(Y.W,!0)},this));
g.j6(this.element,"ytp-caption-window-rollup");g.D(this,this.CO);g.LV(this.element,"overflow","hidden")},BkE=function(C,b){if(!b)return"";
C.N&&C.K.params.lw!==1&&(b*=-1);return"translate"+(C.N?"X":"Y")+"("+b+"px)"},IZe=function(C){C.nO=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=C.K.params.h$,h=0,N=0,p=C.nO.length-1;h<b&&p>-1;){var P=C.nO[p];N+=C.N?P.offsetWidth:P.offsetHeight;h++;p--}C.V=N;b=Math;h=b.max;isNaN(C.q2)&&((N=C.j.qk)?(p=g.wk("SPAN"),g.PP(p,"\u2013".repeat(N)),g.LV(p,ovd(C,C.j.nK)),C.X.appendChild(p),C.q2=p.offsetWidth,C.X.removeChild(p)):C.q2=0);N=C.X;C.KO=h.call(b,C.q2,C.ob,(C.N?N.offsetHeight:N.offsetWidth)+1)},xeD=function(C,b){IZe(C);
var h=C.nO.reduce(function(P,c){return(C.N?c.offsetWidth:c.offsetHeight)+P},0);
h=C.V-h;if(h!==C.rO){var N=h>0&&C.rO===0,p=h<C.rO;b||isNaN(h)||N||!p||(g.j6(C.element,"ytp-rollup-mode"),g.C2(C.CO));g.LV(C.X,"transform",BkE(C,h));C.rO=h}IZe(C)},wEE=function(C,b,h,N){var p=this;
this.Z=C;this.K=b;this.logger=h;this.yV=N;this.Pb=[];this.L2=[];this.QO=null;this.dn={mpz:function(){return p.QO},
XX:function(){return p.Pb}};
C=g.Lk(this.Z.Y().experiments,"html5_override_micro_discontinuities_threshold_ms");this.j=C>0?C:10},hXE=function(C,b){C.QO=function(h,N){if(h.info.X){var p=h;
if(C.L2.length>0){for(p=C.L2.shift();C.L2.length>0;)p=g.dd(p,C.L2.shift());p=g.dd(p,h)}if(p){h=p;try{var P=g.Ww(h)*1E3}catch(Z){P=h.info.startTime*1E3}try{var c=g.oeW(h)*1E3}catch(Z){c=h.info.duration*1E3}if(P<0||c<0)P<0&&(P=h.info.startTime*1E3),c<0&&(c=h.info.duration*1E3);h.info.startTime=P/1E3;h.info.c7=P/1E3;h.info.duration=c/1E3;h.info.W=c/1E3;P=C.xW(p);c=P.yz;P={formatId:P.formatId,startTimeMs:P.startTimeMs,durationMs:P.durationMs,vT:c,KX:c};c=Cnp(C.Pb,P.startTimeMs);var e=(h=c>=0?C.Pb[c]:
null)?h.startTimeMs+h.durationMs:0,L=P.startTimeMs+P.durationMs;!h||P.startTimeMs-e>C.j?C.Pb.splice(c+1,0,P):(h.durationMs=Math.max(e,L)-h.startTimeMs,h.KX=Math.max(h.KX,P.KX));N(C.Pb);N=p.W7();bMD(C.K,N.buffer.slice(N.byteOffset,N.byteLength+N.byteOffset),b,p.info.c7)}else C.logger.j(350058965,"Empty slice")}else C.L2.push(h)};
C.Z.addEventListener("sabrCaptionsDataLoaded",C.QO)},Cnp=function(C,b){C=g.c5(C,{startTimeMs:b},function(h,N){return h.startTimeMs-N.startTimeMs});
return C>=0?C:-C-2},NQo=function(C,b){g.fP.call(this,b);
this.j=C;this.Z=b;this.logger=new g.ty("caps");this.N=this.W=null;this.J=new wEE(this.Z,this,this.logger,this.j.yV)},bMD=function(C,b,h,N){C.logger.debug(function(){return"SABR captions data received for "+N});
C.W?C.N==null?C.logger.j(350058965,"Null loaded track meta data at captions data received"):h.rL(b,C.N,N*1E3):C.logger.j(350058965,"Null Representation at captions data received")},g9o=function(C,b){var h=[],N;
for(N in C.j.j)if(C.j.j.hasOwnProperty(N)){var p=C.j.j[N];if(g.yi(p,b||null)){var P=p.info.id,c=P,e="."+P,L="",Z="";if(p=p.info.captionTrack)P=p.languageCode,c=p.displayName,e=p.vssId,L=p.kind,Z=p.id;h.push(new g.gF({id:N,languageCode:P,languageName:c,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:e,kind:L,captionId:Z}))}}return h},pPj=function(C,b,h){var N=[],p;
for(p in C.j.j)if(C.j.j.hasOwnProperty(p)){var P=C.j.j[p];if(g.yi(P,h||null)){var c=P.info.captionTrack;c&&c.languageCode===b&&N.push(P)}}return N.length?N[0]:null},PnU=function(C,b){if(!g.POW(C)||C.j!=null&&g.Va(b.Y())&&!C.j.isManifestless&&C.j.j.rawcc!=null)return!1;
b=!!C.j&&C.j.isManifestless&&Object.values(C.j.j).some(function(h){return g.yi(h,"386")});
C=!!C.j&&!C.j.isManifestless&&g.rA6(C.j);return b||C},s6=function(){zJ.call(this)},j4$=function(C,b,h,N,p,P,c,e,L){switch(c.tagName){case "b":e.bold=!0;
break;case "i":e.italic=!0;break;case "u":e.underline=!0}for(var Z=0;Z<c.childNodes.length;Z++){var Y=c.childNodes[Z];if(Y.nodeType===3)Y=new $x(b,h,N,p.id,Y.nodeValue,P||Z>0,g.A8(e)?void 0:e),L.push(Y),p.j.push(Y);else{var a={};Object.assign(a,e);j4$(C,b,h,N,p,!0,Y,a,L)}}},cWj=function(C){var b=C.split(":");
C=0;b=g.z(b);for(var h=b.next();!h.done;h=b.next())C=C*60+Number(h.value);return C*1E3},kzo=function(C,b,h,N){N=Object.assign({nG:0},N);
return new HB(C,b,h,"_"+V5++,N)},O6=function(C,b){g.O.call(this);
this.Z=C;this.If=b;this.j=null;this.K=this.Z.ST();this.logger=new g.ty("caps")},Lkd=function(C,b,h){if(typeof b==="string"||TkE(b))return[{trackData:b,
MV:h}];var N=new DataView(b);if(N.byteLength<=8||N.getUint32(4)!==1718909296)return[];var p=g.MZx(N);if(C.K&&p){var P=g.o2H(p),c=g.Flc(p);p=p.oF;P&&p&&C.K.Ng(p,P,c)}C=g.dE(N,1835295092);if(!C||!C.length||!C[0].size)return[];P=[];for(c=0;c<C.length;c++)p=C[c],p=new Uint8Array(b,p.dataOffset,p.size-(p.dataOffset-p.offset)),p=g.mW(p),P.push({trackData:p,MV:h+c*1E3});eX$(N,P,h);return P=P.filter(function(e){return!!e.trackData})},eX$=function(C,b,h){var N=g.RL(C,0,1836476516),p=9E4;
N&&(p=g.QL(N)||9E4);N=0;for(var P=g.dE(C,1836019558),c=0;c<P.length;c++){var e=P[c];c<b.length&&(e=g.RL(C,e.dataOffset,1953653094))&&(e=g.RL(C,e.dataOffset,1952867444))&&(e=g.ve(e)/p*1E3,c===0&&(N=e),b[c].MV=e-N+h||h*c*1E3)}},ZMj=function(C){var b={};
if(C=g.jz(C))b.lang=C,g.hEh.test(C)&&(b.P2=1);return b},vB=function(C){g.qK.call(this,C);
var b=this;this.Z=C;this.Qz=[];this.nO={};this.CO={};this.L=!1;this.X="NONE";this.j=this.V=this.KO=this.t4=this.zi=null;this.ob={F8:function(){b.F8()},
rL:function(P,c,e,L){b.rL(P,c,e,L)}};
this.K=null;this.If=this.Z.Y();this.videoData=this.Z.getVideoData();this.Vz=this.Z.Ti();var h;this.kh=(h=this.Z.getVideoData(1))==null?void 0:g.Kj(h);this.N={nK:{}};this.W={nK:{}};g.DS(this.videoData)?this.X="OFFLINE":PnU(this.videoData,this.Z)?this.X="SABR_LIVE":g.hsl(this.videoData,this.Z)?this.X="LIVE":this.videoData.captionTracks.length?this.X="INNERTUBE":this.videoData.pK&&(this.X="TTS");this.m6=this.If.controlsType==="3";this.Yh=new O6(this.Z,this.If);this.q2=new g.Jm(this);this.J=new g.n({B:"div",
C:"ytp-caption-window-container",T:{id:"ytp-caption-window-container"}});this.N2={top:0,right:0,bottom:0,left:0,width:1,height:1};h=null;var N=g.XY("yt-html5-player-modules::subtitlesModuleData");N&&(h=new g.AZ(N));this.storage=h;var p;this.sI=!((p=C.Q_())==null||!p.jk());this.G=Y0D(this);this.sX=!this.G&&this.m6&&this.sI&&(this.X==="LIVE"||this.X==="SABR_LIVE");g.D(this,this.Yh);this.G?this.rO=this.Df=null:(this.Df=new g.xn(this.z4,void 0,this),g.D(this,this.Df),this.rO=new g.wl(this.dKi,2E3,this),
g.D(this,this.rO));g.D(this,this.q2);g.MC(this.player,this.J.element,4);g.D(this,this.J);this.G||this.q2.S(C,"resize",this.e0);(this.G$=g.MX(this.If)&&!g.Fr()&&!this.Z.isFullscreen()&&!this.G&&!this.sX)&&this.q2.S(C,"resize",this.us6);this.q2.S(C,"onPlaybackAudioChange",this.eWX);this.q2.S(C,g.gL("captions"),function(P){b.onCueRangeEnter(P)});
this.q2.S(C,g.p8("captions"),function(P){b.onCueRangeExit(P)});
this.kh&&this.q2.S(C,"videodatachange",function(P,c){b.onVideoDataChange(P,c)});
a6E(this,Nkh()||{});this.player.IL("onCaptionsModuleAvailable")},Fkj=function(C){if(C.If.G$===1||C.videoData.wy===1||g.aD(C.videoData,"yt:cc")==="alwayson")return!0;
if(C.videoData.captionTracks.length)var b=C.getAudioTrack().K;if(C.If.G$===2){if(g.Oa(C.If))var h=l6d(C);else if(C.storage)try{h=C.storage.get("module-enabled")}catch(p){C.storage.remove("module-enabled")}else h=null;if(h!=null)return!!h}h=t90(C.player.getAudioTrack(),g.Oa(C.If));var N=g.aD(C.videoData,"yt:cc");if(o9j(C)===void 0){if(h==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return N?N==="on":!0;if(h==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return N==="on"}else return N==="on";return b==="ON"||
g.aD(C.videoData,"yt:cc")==="on"},D3=function(C,b){if(C.K&&(b===void 0||!b)||!C.videoData.captionTracks.length)return!1;
C=C.getAudioTrack();return!!C.j||C.K==="FORCED_ON"},o9j=function(C){var b=void 0,h=g.vj(g.OJ(),65);
if(g.Oa(C.If)&&h!=null){if(l6d(C)!=null)return!1;b=!h}return b},WB=function(C,b){if(!C.j)return null;
if(C.V&&C.V.X)return C.V.X;b=Gz0(C,b);b=g.Zw(C.j.K,b);var h=null;if(T2D(C.If)){var N=C.Z.isInline()?void 0:g.R1("yt-player-caption-sticky-language");for(var p=[N,C.videoData.captionsLanguagePreference,C.If.captionsLanguagePreference,g.aD(C.videoData,"yt:cc_default_lang")],P=!1,c=0;c<p.length;c++){var e=p[c];if(e){P=!0;for(var L=0;L<b.length;L++)if(g.jz(b[L])===e)return b[L];for(L=0;L<b.length;L++)if(g.jz(b[L]).split("-")[0]===e.split("-")[0])return b[L]}}if(P&&C.j&&(p=C.j.G,p.length))for(p=g.z(p),
P=p.next();!P.done;P=p.next())if(P=P.value,P.languageCode===N){h=P;break}}else for(N=[C.videoData.captionsLanguagePreference,C.If.captionsLanguagePreference,g.aD(C.videoData,"yt:cc_default_lang")],p=0;p<N.length;p++)for(P=0;P<b.length;P++)if(g.jz(b[P])===N[p])return b[P];N=null;C.V&&C.V.N&&(N=C.V.N);N||(N=b.find(function(Z){return Z.isDefault})||null);
N||(N=b[0]||d5(C));N&&h&&g.jz(N).split("-")[0]!==h.languageCode.split("-")[0]&&(N=B2j(N,h));return N},d5=function(C){return C.V&&C.V.j},E6=function(C){var b=d5(C);
return!!b&&C.K===b},S0E=function(C,b){var h=C.Z.Q_().Rb().textTracks;
C=C.K.toString();for(var N=0;N<h.length;N++){var p=h[N];p.id===C&&(b?p.mode!=="showing"&&(p.mode="showing"):p.mode==="showing"&&(p.mode="disabled"))}},TJ=function(C,b,h){C.loaded&&C.unload();
h!=null&&(C.L=h,C.L&&(g.Oa(C.If)?nq(C,!!b):ts(C,!!b)));C.If.D("html5_report_caption_format_change")&&$7p(C,C.K,b,C.L,!1);C.K=b;D3(C)&&(b=d5(C),C.If.D("html5_report_caption_format_change")&&$7p(C,C.K,b,C.L,!0),C.K=b);var N;zX0(C,(N=C.K)!=null?N:void 0);C.load()},VWC=function(C,b){if(b instanceof HB){var h=C.nO[b.id];
h&&h.K!==b&&(h.dispose(),delete C.nO[b.id],h=null);h||(h=HMd(C,b))&&(C.nO[b.id]=h)}else h=b.windowId,C.CO[h]||(C.CO[h]=[]),C.CO[h].push(b)},HMd=function(C,b){var h=MWE(C);
if(!h)return null;var N=C.K?g.jz(C.K):null;N&&g.hEh.test(N)&&(b.params.P2=1);var p=C.Vz.getPlayerSize();N=p.height*C.N2.height;p=p.width*C.N2.width;C.If.playerStyle!=="google-live"||C.N.isDefault||Object.assign(b.params,C.N);switch(b.params.nG!=null?b.params.nG:b.j.length>1?1:0){case 1:return new u5(b,C.N,C.W,h.width,h.height,p,N,C.If.experiments,C.Y_.bind(C),C.Z);case 2:return new Kq(b,C.N,C.W,h.width,h.height,p,N,C.If.experiments,C.Y_.bind(C),C.Z);default:return new Lq(b,C.N,C.W,h.width,h.height,
p,N,C.If.experiments,C.Y_.bind(C),C.Z)}},a6E=function(C,b,h){h=h===void 0?!1:h;
var N=BB.nK;C.N={};Object.assign(C.N,BB);C.N.nK={};Object.assign(C.N.nK,N);C.W={nK:{}};var p=b.backgroundOverride?C.W:C.N,P=b.background||N.background;As.test(P);p.nK.background=P;p=b.colorOverride?C.W:C.N;P=b.color||N.color;As.test(P);p.nK.color=P;p=b.windowColorOverride?C.W:C.N;P=b.windowColor||BB.windowColor;As.test(P);p.windowColor=P;p=b.backgroundOpacityOverride?C.W:C.N;P=b.backgroundOpacity;P==null&&(P=N.backgroundOpacity);p.nK.backgroundOpacity=P;p=b.fontSizeIncrementOverride?C.W:C.N;P=b.fontSizeIncrement;
P==null&&(P=N.fontSizeIncrement);p.nK.fontSizeIncrement=P;P=b.fontStyleOverride?C.W:C.N;p=b.fontStyle;p==null&&(p=N.bold&&N.italic?3:N.bold?1:N.italic?2:0);P=P.nK;switch(p){case 1:P.bold=!0;delete P.italic;break;case 2:delete P.bold;P.italic=!0;break;case 3:P.bold=!0;P.italic=!0;break;default:delete P.bold,delete P.italic}p=b.textOpacityOverride?C.W:C.N;P=b.textOpacity;P==null&&(P=N.textOpacity);p.nK.textOpacity=P;p=b.windowOpacityOverride?C.W:C.N;P=b.windowOpacity;P==null&&(P=BB.windowOpacity);p.windowOpacity=
P;p=b.charEdgeStyleOverride?C.W:C.N;P=b.charEdgeStyle;P==null&&(P=N.charEdgeStyle);p.nK.charEdgeStyle=P;p=b.fontFamilyOverride?C.W:C.N;P=b.fontFamily;P==null&&(P=N.fontFamily);p.nK.fontFamily=P;C.loaded&&C.e0();h&&g.uU("yt-player-caption-display-settings",b,2592E3)},q0e=function(C,b){if(!C.j)return{};
if(b){C.If.D("html5_report_caption_format_intent")&&!g.A8(b)&&C.ke(b.vss_id,"m");if(C.G||!g.tl(b))return;if(g.A8(b)){TJ(C,null,!0);return}for(var h,N=g.Zw(C.j.K,!0),p=0;p<N.length;p++){var P=N[p];P.languageCode!==b.languageCode||h&&(P.languageName!==b.languageName||(P.captionId||"")!==(b.captionId||"")||g.pj(P)!==b.displayName)||(h=b.translationLanguage?B2j(P,b.translationLanguage):P)}C.GN(b.position);!h||h===C.K&&C.loaded||(b=g.Jd(),N=g.jz(h),b.length&&N===b[b.length-1]||(b.push(N),g.uU("yt-player-caption-language-preferences",
b)),T2D(C.If)&&!C.Z.isInline()&&g.uU("yt-player-caption-sticky-language",N,2592E3),TJ(C,h,!0))}else return C.loaded&&C.K&&!E6(C)?g.P7(C.K):{};return""},f60=function(C,b,h){b&&!C.KO?(b=Dee({P2:0,
lang:"en"}),C.KO=[b,new $x(b.start,b.end-b.start,0,b.id,h!=null?h:"Captions look like this")],C.player.A8(C.KO)):!b&&C.KO&&(m7d(C,C.KO),C.KO=null)},m7d=function(C,b){C.player.AR(b);
b=g.z(b);for(var h=b.next();!h.done;h=b.next())g.wD(C.Qz,h.value);cB(C.Df)},zX0=function(C,b){C.If.D("html5_modify_caption_vss_logging")&&(C.videoData.iE=b)},MWE=function(C){var b=C.Vz.getVideoContentRect(!0).height,h=C.Vz.getVideoContentRect(!0).width;
if(!b||!h)return null;b*=C.N2.height;h*=C.N2.width;return{width:h,height:b}},ts=function(C,b){if(C.storage)try{C.storage.set("module-enabled",b)}catch(h){}},nq=function(C,b){C.Z.isInline()||g.uU("yt-player-sticky-caption",b,2592E3)},l6d=function(C){if(!C.Z.isInline())return g.R1("yt-player-sticky-caption")},Y0D=function(C){var b,h=!((b=C.Z.Q_())==null||!b.vV());
return C.m6&&h&&C.X!=="LIVE"&&C.X!=="SABR_LIVE"},Gz0=function(C,b){g.f6(C.videoData)&&(b=!0);
b||(b=C.X==="TTS"?!1:C.X==="INNERTUBE"?!1:!0);return b||C.If.D("web_deprecate_always_includes_asr_setting")&&g.Oa(C.If)?!0:!!g.vj(g.OJ(),66)},$7p=function(C,b,h,N,p){p?C.eq(h,!0,"g"):N?b?C.eq(h,!!h,"m"):h&&C.eq(h,!0,"m"):!b&&h&&C.eq(h,!0,"s")};
g.fP.prototype.jG=g.NW(67,function(){return!1});
g.fP.prototype.j4=g.NW(66,function(){});
g.AO.prototype.j4=g.NW(65,function(C,b,h){var N=this;this.HE();b=this.YU(C,b);var p=this.h4.Y().D("html5_report_captions_ctmp_qoe"),P=(0,g.fB)();this.HK();nTE(this,b,{format:"RAW",onSuccess:function(c){N.j=null;if(p){var e=(c.responseText.length/1024).toFixed(),L=(0,g.fB)();N.videoData.jp("capresp",{ms:L-P,kb:e})}h.rL(c.responseText,C)},
onError:p?function(c){var e;c=(e=c==null?void 0:c.status)!=null?e:0;N.videoData.jp("capfail",{status:c})}:void 0,
withCredentials:!0})});
g.rO.prototype.j4=g.NW(64,function(C,b,h){var N=this;this.HE();b=this.YU(C,b);this.HK();this.j=g.mt(b,{format:"RAW",onSuccess:function(p){N.j=null;h.rL(p.responseText,C)},
withCredentials:!0})});
g.pP.prototype.rl=g.NW(63,function(){for(var C=g.dk(document,"track",void 0,this.j),b=0;b<C.length;b++)g.gQ(C[b])});
g.Kc.prototype.rl=g.NW(62,function(){this.mediaElement.rl()});
g.pP.prototype.jk=g.NW(61,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.Kc.prototype.jk=g.NW(60,function(){return this.mediaElement.jk()});
g.pP.prototype.vV=g.NW(59,function(){return!!this.j.textTracks});
g.Kc.prototype.vV=g.NW(58,function(){return this.mediaElement.vV()});
g.pP.prototype.Ow=g.NW(57,function(C){for(var b=0;b<C.length;b++)this.j.appendChild(C[b])});
g.Kc.prototype.Ow=g.NW(56,function(C){this.mediaElement.Ow(C)});
g.cO.prototype.Ng=g.NW(51,function(C,b,h){this.uf.Ng(C,b,h)});
g.tY.prototype.Ng=g.NW(50,function(C,b,h){this.K.set(C,{qJ:b,Vh:h})});
g.TX.prototype.Ng=g.NW(49,function(C,b,h){this.Qz.Ng(C,b,h)});
g.cO.prototype.Ks=g.NW(48,function(C){return this.uf.Ks(C)});
g.TX.prototype.Ks=g.NW(47,function(C){var b=2;this.J.has(C)?b=0:g.RtK(this,C)&&(b=1);return b});
g.ty.prototype.j=g.NW(46,function(C){g.T8.apply(null,[5,this.tag,C].concat(g.M(g.yH.apply(1,arguments))))});
g.oC.prototype.F3=g.NW(43,function(C){var b=this.app.gU();return b?b.F3(C):!1});
g.WO.prototype.F3=g.NW(42,function(C){return this.l1().some(function(b){return b.namespace===C})});
g.EL.prototype.F3=g.NW(41,function(C){return this.vE.Zx.F3(C)});
g.oC.prototype.ke=g.NW(39,function(C,b){var h;(h=this.app.i$())==null||h.ke(C,b)});
g.fJ.prototype.ke=g.NW(38,function(C,b){C=[C,b];g.mQ(this,g.HO(this.provider),"cfi",C)});
g.vO.prototype.ke=g.NW(37,function(C,b){this.qoe&&this.qoe.ke(C,b)});
g.EL.prototype.ke=g.NW(36,function(C,b){this.vE.ke(C,b)});
g.oY.prototype.ke=g.NW(35,function(C,b){this.CJ().ke(C,b)});
g.oC.prototype.eq=g.NW(34,function(C,b,h){var N;(N=this.app.i$())==null||N.eq(C,b,h)});
g.fJ.prototype.eq=g.NW(33,function(C,b,h){if(this.Df!==C||this.AZ!==b)b=b==="rawcc"?"":b,h=[C,b,this.Df,h],g.mQ(this,g.HO(this.provider),"cfs",h),this.Df=C,this.AZ=b});
g.vO.prototype.eq=g.NW(32,function(C,b,h){this.qoe&&this.qoe.eq(C,b,h)});
g.EL.prototype.eq=g.NW(31,function(C,b,h){this.vE.eq(C,b,h)});
g.oY.prototype.eq=g.NW(30,function(C,b,h){this.CJ().eq(C,b,h)});
g.g4.prototype.Hc=g.NW(19,function(){return this.L});
g.SA.prototype.Hc=g.NW(18,function(){var C;return((C=this.i$())==null?void 0:C.ST())||null});
g.oC.prototype.ST=g.NW(17,function(){return this.app.Hc()});
g.EL.prototype.ST=g.NW(16,function(){return this.vE.ST()});
g.oY.prototype.ST=g.NW(15,function(){var C;return((C=this.Xo)==null?void 0:C.Hc())||null});
g.$0.prototype.Lq=g.NW(1,function(C){return(C=this.H5(C))?C.K:0});
g.TE.prototype.Lq=g.NW(0,function(){return 0});
var CF$=/#(.)(.)(.)/,whD=/^#(?:[0-9a-f]{3}){1,2}$/i,c8h={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};kx.prototype.contains=function(C){C=g.c5(this.segments,C);return C>=0||C<0&&(-C-1)%2===1};
kx.prototype.length=function(){return this.segments.length/2};
g.S(pEd,g.O);g.k=pEd.prototype;g.k.wO=function(){g.O.prototype.wO.call(this);this.N&&this.N.cancel()};
g.k.HQ=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(C){C-=this.player.Z9();var b=this.j;this.j=g.nd(this.KO.gh(C).UX);b!==this.j&&this.V&&this.V()};
g.k.reset=function(){this.X=new kx;this.W=-1;this.N&&(this.N.cancel(),this.N=null)};
g.k.dc=function(){this.HE();var C;if(C=this.j!=null)C=this.j,C=C.j.KB(C);if(C&&!this.N&&!(this.j&&this.j.startTime-this.player.getCurrentTime()>30)){C=this.j;C=C.j.A1(C);var b=C.UX[0],h;if((h=this.player.getVideoData())==null?0:h.enableServerStitchedDai)if(h=this.player.ST()){var N=b.j.info.id,p=b.yz,P=C.UX[0].c7;if(this.policy.Qz){if(h=h.PR(P,p,N,3))C.X=h}else if(N=h.Vu(P,p,N,3))if(h=h.Ks(p),h===0)N&&(C.j=new g.Zl(N));else if(h===2){this.J.start();PF0(this)&&this.seekTo(this.player.getCurrentTime());
return}}b.j.index.C2(b.yz)?(this.X.contains(C.UX[0].yz)||jVU(this,C),this.j=g.nd(C.UX)):PF0(this)&&this.seekTo(this.player.getCurrentTime())}this.J.start()};
g.S(ey,g.fP);g.k=ey.prototype;g.k.j4=function(C,b,h){var N=this;this.HK();b=e4E(this,C.getId());b||(b=C.languageCode,b=this.j.isManifestless?LgE(this,b,"386"):LgE(this,b));if(b){var p=(b.index.Lq(b.index.SJ())-b.index.getStartTime(b.index.SJ()))*1E3,P=this.Z.Y(),c=new g.OAH(P),e=function(){N.N&&N.N.reset();N.W=!0};
P.D("html5_keep_caption_data_after_seek")&&(e=null);this.N=new pEd(c,this.Z,b,function(L,Z){h.rL(L,C,Z,p)},this.J||g.nE(b.info),e)}};
g.k.jG=function(){var C=this.W;this.W=!1;return C};
g.k.aX=function(C){var b=this.Z.Y().D("html5_fallback_if_rawcc_missing");var h=this.j.j.rawcc!=null;if(!this.J||!h&&b)b=this.j.isManifestless?kAD(this,"386"):kAD(this);else{if(!h){this.logger.j(386248249,"rawcc used but unavailable");return}b=[new g.gF({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.gF({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}b=g.z(b);
for(h=b.next();!h.done;h=b.next())g.m2(this.K,h.value);C.F8()};
g.k.HK=function(){this.N&&(this.N.dispose(),this.N=null)};
g.k.YU=function(){return""};
g.k.d4=function(){this.N&&(this.N.reset(),this.Z.Sh("captions"))};
var As=/^#(?:[0-9a-f]{3}){1,2}$/i;var aZC=["left","right","center","justify"];g.S(Lq,g.n);g.k=Lq.prototype;g.k.rd=function(C,b){this.Yh=C;this.kh=b;var h=g.$X(this.element,this.element.parentElement);this.zi=C-h.x;this.Vz=b-h.y};
g.k.MA=function(C,b){if(C!==this.Yh||b!==this.kh){g.P4(this.element,"ytp-dragging")||g.j6(this.element,"ytp-dragging");var h=g.Hc(this.element);C=C-this.zi-.02*this.playerWidth;var N=b-this.Vz-.02*this.playerHeight,p=(C+h.width/2)/this.maxWidth*3;p=Math.floor(g.cE(p,0,2));var P=(N+h.height/2)/this.maxHeight*3;P=Math.floor(g.cE(P,0,2));b=p+P*3;C=(C+p/2*h.width)/this.maxWidth;C=g.cE(C,0,1)*100;h=(N+P/2*h.height)/this.maxHeight;h=g.cE(h,0,1)*100;this.K.params.W5=b;this.K.params.Dm=h;this.K.params.uY=
C;this.K.params.isDefault=!1;this.j.W5=b;this.j.Dm=h;this.j.uY=C;this.j.isDefault=!1;this.N2.W5=b;this.N2.Dm=h;this.N2.uY=C;this.N2.isDefault=!1;this.un()}};
g.k.yN=function(){g.kb(this.element,"ytp-dragging")};
g.k.un=function(){this.vg(this.J)};
g.k.getType=function(){return this.type};
g.k.vg=function(C){var b=this.G$?0:Math.min(this.E3(),this.maxWidth),h=this.Gh(),N=this.G$;if(N){var p=getComputedStyle(this.X.parentNode);p=Z3(p.borderLeftWidth)+Z3(p.borderRightWidth)+Z3(p.paddingLeft)+Z3(p.paddingRight)}else p=0;var P=p;p="";this.K.params.P2===3&&(p="rotate(180deg)");var c=N?"calc(96% - "+P+"px)":"96%";g.LV(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:h?h+"px":"","max-width":c,"max-height":c,margin:"",transform:""});this.iA(C);p={transform:p,top:"",left:"",
width:b?b+"px":"",height:h?h+"px":"","max-width":"","max-height":""};var e=this.j.uY*.96+2;c=this.j.W5;switch(c){case 0:case 3:case 6:(N=this.j.nK.fontSizeIncrement)&&N>0&&this.j.P2!==2&&this.j.P2!==3&&(e=Math.max(e/(1+N*2),2));p.left=e+"%";break;case 1:case 4:case 7:p.left=e+"%";e=this.X.offsetWidth;b||e?(b=b||e+1,p.width=b+"px",p["margin-left"]=N?b/-2-P/2+"px":b/-2+"px"):p.transform+=" translateX(-50%)";break;case 2:case 5:case 8:p.right=100-e+"%"}N=this.j.Dm*.96+2;switch(c){case 0:case 1:case 2:p.top=
N+"%";break;case 3:case 4:case 5:p.top=N+"%";(h=h||this.element.clientHeight)?(p.height=h+"px",p["margin-top"]=h/-2+"px"):p.transform+=" translateY(-50%)";break;case 6:case 7:case 8:p.bottom=100-N+"%"}g.LV(this.element,p);if(this.W){h=this.X.offsetHeight;N=1;for(b=0;b<C.length;b++)p=C[b],typeof p.text==="string"&&(N+=p.text.split("\n").length-1,p.append||b===0||N++);h/=N;this.W.style.height=h+"px";this.W.style.width=h+"px";this.element.style.paddingLeft=h+5+"px";this.element.style.paddingRight=h+
5+"px";C=Number(this.element.style.marginLeft.replace("px",""))-h-5;h=Number(this.element.style.marginRight.replace("px",""))-h-5;this.element.style.marginLeft=C+"px";this.element.style.marginRight=h+"px"}};
g.k.iA=function(C){var b;for(b=0;b<C.length&&C[b]===this.J[b];b++);if(this.sX||this.J.length>b)b=0,this.sX=!1,this.J=[],this.L=this.Df=this.Qz=null,g.hW(this.X);for(;b<C.length;b++)Si0(this,C[b])};
g.k.E3=function(){return 0};
g.k.Gh=function(){return 0};
g.k.toString=function(){return g.n.prototype.toString.call(this)};z4E.prototype.clear=function(){this.N=this.time=this.mode=0;this.j=[];this.reset()};
z4E.prototype.reset=function(){this.mode=0;this.X.reset(0);this.G.reset(1)};
var HRD=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];Yx.prototype.set=function(C){this.type=C};
Yx.prototype.get=function(){return this.type};
aB.prototype.clear=function(){this.state=0};
aB.prototype.update=function(){this.state=this.state===2?1:0};
aB.prototype.bF=function(){return this.state!==0};
aB.prototype.matches=function(C,b){return this.bF()&&C===this.eP&&b===this.RT};
fZe.prototype.reset=function(){this.timestamp=this.j=0};
l5.prototype.updateTime=function(C){for(var b=1;b<=15;++b)for(var h=1;h<=32;++h)this.N[b][h].timestamp=C};
l5.prototype.debugString=function(){for(var C="\n",b=1;b<=15;++b){for(var h=1;h<=32;++h){var N=this.N[b][h];C=N.j===0?C+"_":C+String.fromCharCode(N.j)}C+="\n"}return C};
l5.prototype.reset=function(C){for(var b=0;b<=15;b++)for(var h=0;h<=32;h++)this.N[b][h].reset();this.X=C;this.j=0;this.K=this.row=1};
var A8D=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],y8E=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],r8d=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],iR$=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];QV0.prototype.reset=function(C,b){this.G=b;this.style.set(2);this.K=this.W;this.X=this.J;this.j=this.K;var h=(C<<2)+(b<<1);this.W.reset(h);this.J.reset(h);this.text.reset((C<<2)+(b<<1)+1)};
$eD.prototype.reset=function(C){this.G=C;this.K.clear();this.X=this.N;this.N.reset(C,0);this.W.reset(C,1)};sV$.prototype.X=function(){};g.S($x,g.hk);$x.prototype.toString=function(){return g.hk.prototype.toString.call(this)};g.S(zJ,g.O);zJ.prototype.wA=function(){return[]};
zJ.prototype.reset=function(){};g.S(HB,g.hk);HB.prototype.toString=function(){return g.hk.prototype.toString.call(this)};
var V5=0;g.S(Mk,zJ);Mk.prototype.reset=function(){this.W={};this.K=this.j=null;this.G=!0};
Mk.prototype.wA=function(C,b){C=C.firstChild;C.getAttribute("format");b=b||0;Number.isFinite(b);C=Array.from(C.childNodes);C=g.z(C);for(var h=C.next();!h.done;h=C.next())if(h=h.value,h.nodeType===1)switch(h.tagName){case "head":var N=h;break;case "body":var p=h}if(N)for(N=Array.from(N.childNodes),N=g.z(N),C=N.next();!C.done;C=N.next())if(C=C.value,C.nodeType===1)switch(C.tagName){case "pen":h=C.getAttribute("id");var P=this.pens,c={},e=C.getAttribute("p");e&&Object.assign(c,this.pens[e]);e=m4(C,"b");
e!=null&&(c.bold=e);e=m4(C,"i");e!=null&&(c.italic=e);e=m4(C,"u");e!=null&&(c.underline=e);e=fq(C,"et");e!=null&&(c.charEdgeStyle=e);e=fq(C,"of");e!=null&&(c.offset=e);e=y5(C,"bc");e!=null&&(c.background=e);e=y5(C,"ec");e!=null&&(c.vJ=e);e=y5(C,"fc");e!=null&&(c.color=e);e=fq(C,"fs");e!=null&&e!==0&&(c.fontFamily=e);e=qk(C,"sz");e!==void 0&&(c.fontSizeIncrement=e/100-1);e=qk(C,"bo");e!==void 0&&(c.backgroundOpacity=e/255);e=qk(C,"fo");e!==void 0&&(c.textOpacity=e/255);e=fq(C,"rb");e!=null&&e!==10&&
e!==0&&(c.Dv=e>10?e-1:e);C=fq(C,"hg");C!=null&&(c.Hv=C);P[h]=c;break;case "ws":h=C.getAttribute("id");this.L[h]=deC(this,C);break;case "wp":h=C.getAttribute("id"),this.J[h]=WgI(this,C)}if(p){N=[];p=Array.from(p.childNodes);p=g.z(p);for(C=p.next();!C.done;C=p.next())if(C=C.value,C.nodeType===1)switch(C.tagName){case "w":this.j=Evd(this,C,b,!1);(C=this.W[this.j.id])&&C.end>this.j.start&&(C.end=this.j.start);this.W[this.j.id]=this.j;N.push(this.j);break;case "p":var L=C;e=b;h=[];P=L.getAttribute("w")||
this.X;c=!!m4(L,"a");e=(qk(L,"t")||0)+e;var Z=qk(L,"d")||5E3;c||(!this.G&&this.K&&this.K.windowId===P&&this.K.end>e&&(this.K.end=e),this.K&&this.K.text==="\n"&&(this.K.text=""));var Y=c?6:5,a=L.getAttribute("p");a=a?this.pens[a]:null;var l=Array.from(L.childNodes);l.length&&(this.G=L.getAttribute("d")!=null);for(L=0;L<l.length;L++){var F=l[L],G=void 0;L>0&&(c=!0);var V=void 0;F.nodeType===1&&(V=F);if(V&&V.tagName==="s"){if((F=(F=V.getAttribute("p"))?this.pens[F]:null)&&F.Dv&&(F.Dv===1?(F=l.slice(L,
L+4),F.length===4&&(G=vvo(e,Z,P,c,Y,F,this.pens),L+=3)):G=vvo(e,Z,P,c,Y,[V],this.pens)),!G){var q=V;G=e;V=Z;F=P;var f=c,y=Y,u=q.textContent?q.textContent:"",K=q.getAttribute("p");K=K?this.pens[K]:null;q=qk(q,"t")||0;G=new $x(G+q,V-q,y,F,u,f,K)}}else G=new $x(e,Z,Y,P,F.textContent||"",c,a);h.push(G);this.K=G}if(h.length>0)for(h[0].windowId===this.X&&(this.j=Evd(this,C,b,!0),N.push(this.j)),C=g.z(h),h=C.next();!h.done;h=C.next())h=h.value,h.windowId=this.j.id,this.j.j.push(h),N.push(h)}b=N}else b=[];
return b};var AW0=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.S(r5,zJ);r5.prototype.reset=function(){this.K.clear()};
r5.prototype.wA=function(C,b){var h=JSON.parse(C);if(!h)return[];if(h.pens){C=0;for(var N=g.z(h.pens),p=N.next();!p.done;p=N.next()){p=p.value;var P={},c=p.pParentId;c&&Object.assign(P,this.j.get(c));p.bAttr&&(P.bold=!0);p.iAttr&&(P.italic=!0);p.uAttr&&(P.underline=!0);c=p.ofOffset;c!=null&&(P.offset=c);p.szPenSize!==void 0&&(P.fontSizeIncrement=p.szPenSize/100-1);c=p.etEdgeType;c!=null&&(P.charEdgeStyle=c);p.ecEdgeColor!==void 0&&(P.vJ=i5(p.ecEdgeColor));c=p.fsFontStyle;c!=null&&c!==0&&(P.fontFamily=
c);p.fcForeColor!==void 0&&(P.color=i5(p.fcForeColor));p.foForeAlpha!==void 0&&(P.textOpacity=p.foForeAlpha/255);p.bcBackColor!==void 0&&(P.background=i5(p.bcBackColor));p.boBackAlpha!==void 0&&(P.backgroundOpacity=p.boBackAlpha/255);(c=p.rbRuby)&&c!==10&&(P.Dv=c>10?c-1:c,P.Ea=AW0.get(P.Dv));p.hgHorizGroup&&(P.Hv=p.hgHorizGroup);this.j.set(C++,P)}}if(h.wsWinStyles)for(C=0,N=g.z(h.wsWinStyles),p=N.next();!p.done;p=N.next())p=p.value,P={},(c=p.wsParentId)?Object.assign(P,this.X.get(c)):Object.assign(P,
this.G),p.mhModeHint!==void 0&&(P.nG=p.mhModeHint),p.juJustifCode!==void 0&&(P.textAlign=p.juJustifCode),p.pdPrintDir!==void 0&&(P.P2=p.pdPrintDir),p.sdScrollDir!==void 0&&(P.lw=p.sdScrollDir),p.wfcWinFillColor!==void 0&&(P.windowColor=i5(p.wfcWinFillColor)),p.wfoWinFillAlpha!==void 0&&(P.windowOpacity=p.wfoWinFillAlpha/255),this.X.set(C++,P);if(h.wpWinPositions)for(C=0,N=g.z(h.wpWinPositions),p=N.next();!p.done;p=N.next())p=p.value,P={},(c=p.wpParentId)&&Object.assign(P,this.N.get(c)),p.ahHorPos!==
void 0&&(P.uY=p.ahHorPos),p.apPoint!==void 0&&(P.W5=p.apPoint),p.avVerPos!==void 0&&(P.Dm=p.avVerPos),p.ccCols!==void 0&&(P.qk=p.ccCols),p.rcRows!==void 0&&(P.h$=p.rcRows),this.N.set(C++,P);if(h.events){C=[];h=g.z(h.events);for(N=h.next();!N.done;N=h.next()){var e=N.value;p=(e.tStartMs||0)+b;P=e.dDurationMs||0;if(e.id)c=String(e.id),N=nvI(this,e,p,P,c),C.push(N),this.K.set(c,N);else{e.wWinId?c=e.wWinId.toString():(c="_"+V5++,N=nvI(this,e,p,P,c),C.push(N),this.K.set(c,N));N=C;var L=e;P===0&&(P=5E3);
e=this.K.get(c);var Z=!!L.aAppend,Y=Z?6:5,a=L.segs,l=null;L.pPenId&&(l=this.j.get(L.pPenId));for(L=0;L<a.length;L++){var F=a[L],G=F.utf8;if(G){var V=F.tOffsetMs||0,q=null;F.pPenId&&(q=this.j.get(F.pPenId));if((e.params.nG!=null?e.params.nG:e.j.length>1?1:0)===2&&Z&&G==="\n")continue;F=null;var f=[],y;if(y=q&&q.Dv===1){y=a;var u=L;if(u+3>=y.length||!y[u+1].pPenId||!y[u+2].pPenId||!y[u+3].pPenId)y=!1;else{var K=y[u+1].pPenId;(K=this.j.get(K))&&K.Dv&&K.Dv===2?(K=y[u+2].pPenId,K=this.j.get(K),!K||!K.Dv||
K.Dv<3?y=!1:(K=y[u+3].pPenId,y=(K=this.j.get(K))&&K.Dv&&K.Dv===2?!0:!1)):y=!1}}if(y)V=a[L+1].utf8,F=a[L+3].utf8,y=a[L+2].utf8,u=this.j.get(a[L+2].pPenId),G=ORD(G,V,y,F,u),F=new $x(p,P,Y,c,G,Z,q),L+=3;else{if(G.indexOf("<")>-1){var v=void 0;f=q;y=l;u=p;K=P;var T=V,t=Y,go=Z,jV=[],CW=g.Tr("<html>"+G+"</html>");if(!CW.getElementsByTagName("parsererror").length&&((v=CW.firstChild)==null?0:v.childNodes.length))for(v=g.z(CW.firstChild.childNodes),CW=v.next();!CW.done;CW=v.next()){CW=CW.value;var W=void 0,
w=void 0,H=(w=(W=CW.textContent)==null?void 0:W.replace(/\n/g,""))!=null?w:"";if(CW.nodeType!==3||H&&H.match(/^ *$/)==null){W={};Object.assign(W,f||y);w=void 0;switch((w=CW)==null?void 0:w.tagName){case "b":W.bold=!0;break;case "i":W.italic=!0;break;case "u":W.underline=!0}jV.push(new $x(u+T,K-T,t,e.id,H,go,W))}}f=jV}f.length||(f=[new $x(p+V,P-V,Y,e.id,G,Z,q||l)])}if(f.length)for(Z=g.z(f),q=Z.next();!q.done;q=Z.next())q=q.value,N.push(q),e.j.push(q);else F&&(N.push(F),e.j.push(F))}Z=!0}}}b=C}else b=
[];return b};g.S(Js,g.fP);Js.prototype.j4=function(C,b,h){xNd(this.videoData.videoId,C.vssId,h.rL)};
Js.prototype.aX=function(C){if(this.audioTrack)for(var b=g.z(this.audioTrack.captionTracks),h=b.next();!h.done;h=b.next())g.m2(this.K,h.value);C.F8()};g.S(u5,Lq);u5.prototype.iA=function(C){var b=this.K.j;Lq.prototype.iA.call(this,C);for(C=C.length;C<b.length;C++){var h=b[C];if(P&&h.j===p)var N=P;else{N={};Object.assign(N,h.j);Object.assign(N,yWE);var p=h.j;var P=N}Si0(this,h,N)}};
var yWE={r4h:!0};g.S(RB,sV$);RB.prototype.X=function(C,b,h,N,p){if(h<N){var P="_"+V5++;h=h/1E3-this.W;N=N/1E3-this.W;C=new HB(h,N-h,5,P,{textAlign:0,W5:0,uY:b*2.5,Dm:C*5.33});p=new $x(h,N-h,5,P,p);this.K.push(C);this.K.push(p)}};
g.S(Xa,zJ);Xa.prototype.wA=function(C){C=new RB(C,C.byteLength,this.K);if(te$(C)){for(;C.byteOffset<C.j.byteLength;)for(C.version===0?C.N=U6(C)*(1E3/45):C.version===1&&(C.N=U6(C)*4294967296+U6(C)),C.G=Q5(C);C.G>0;C.G--){var b=Q5(C),h=Q5(C),N=Q5(C);b&4&&(b&3)===this.track&&(this.track===0||this.track===1)&&(b=this.j,b.j.push({time:C.N,type:this.track,Xf:h,wR:N,order:b.j.length}))}meD(this.j,C);return C.K}return[]};
Xa.prototype.reset=function(){this.j.clear()};g.S(Kq,Lq);g.k=Kq.prototype;g.k.un=function(){g.be(this.CO)};
g.k.c86=function(){g.kb(this.element,"ytp-rollup-mode");this.vg(this.Yg,!0)};
g.k.Gh=function(){return this.N?this.KO:this.V};
g.k.E3=function(){return this.N?this.V:this.KO};
g.k.vg=function(C,b){this.Yg=C;if(this.K.params.h$){for(var h=0,N=0;N<this.J.length&&h<C.length;N++)this.J[N]===C[h]&&h++;h>0&&h<C.length&&(C=this.J.concat(C.slice(h)));this.ob=this.KO;this.V=this.KO=0;Lq.prototype.vg.call(this,C);xeD(this,b)}Lq.prototype.vg.call(this,C)};wEE.prototype.unload=function(){this.QO!=null&&(this.Z.removeEventListener("sabrCaptionsDataLoaded",this.QO),this.QO=null);this.Pb=[];this.Z.publish("sabrCaptionsBufferedRangesUpdated",this.Pb)};
wEE.prototype.xW=function(C){return{formatId:g.B9(C.info.j.info,this.yV),yz:C.info.yz+(this.yV?0:1),startTimeMs:C.info.c7*1E3,durationMs:C.info.W*1E3}};g.S(NQo,g.fP);g.k=NQo.prototype;g.k.j4=function(C,b,h){this.HK();b=C.getId();b=b!=null&&b in this.j.j?this.j.j[b]:null;b||(b=C.languageCode,b=this.j.isManifestless?pPj(this,b,"386"):pPj(this,b));b&&(this.N=C,this.W=b,hXE(this.J,h),this.Z.publish("sabrCaptionsTrackChanged",g.B9(b.info,this.j.yV)))};
g.k.aX=function(C){var b=this.j.isManifestless?g9o(this,"386"):g9o(this);b=g.z(b);for(var h=b.next();!h.done;h=b.next())g.m2(this.K,h.value);C.F8()};
g.k.HK=function(){this.N&&(this.N=this.W=null,this.J.unload(),this.Z.publish("sabrCaptionsTrackChanged",null))};
g.k.YU=function(){return""};
g.k.d4=function(){this.Z.Sh("captions")};g.S(s6,zJ);
s6.prototype.wA=function(C,b){var h=[];C=C.split(rWh);for(var N=1;N<C.length;N++){var p=C[N],P=b;if(p!==""&&!iMC.test(p)){var c=JWp.exec(p);if(c&&c.length>=4){var e=cWj(c[1]),L=cWj(c[2])-e;e+=P;var Z=(c=c[3])?c.split(" "):[];c={};var Y=null;var a="";var l=null,F="";Z=g.z(Z);for(var G=Z.next();!G.done;G=Z.next())if(G=G.value.split(":"),G.length===2){var V=G[1];switch(G[0]){case "line":G=V.split(",");G[0].endsWith("%")&&(Y=G[0],c.Dm=Number.parseInt(Y,10),G.length===2&&(a=G[1].trim()));break;case "position":G=
V.split(",");l=G[0];c.uY=Number.parseInt(l,10);G.length===2&&(F=G[1].trim());break;case "align":switch(V){case "start":c.textAlign=0;break;case "middle":c.textAlign=2;break;case "end":c.textAlign=1}}}Y||a||(a="end");if(!l)switch(c.textAlign){case 0:c.uY=0;break;case 1:c.uY=100;break;case 2:c.uY=50}if(c.textAlign!=null){Y=0;switch(a){case "center":Y+=3;break;case "end":Y+=6;break;default:Y+=0}switch(F){case "line-left":Y+=0;break;case "center":Y+=1;break;case "line-right":Y+=2;break;default:switch(c.textAlign){case 0:Y+=
0;break;case 2:Y+=1;break;case 1:Y+=2}}a=Y<0||Y>8?7:Y;c.W5=a}p=p.substring(JWp.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");F=c;c=p;p={};if(c.indexOf("<")<0&&c.indexOf("&")<0)P=kzo(e,L,5,F),L=new $x(e,L,5,P.id,c,!1,g.A8(p)?void 0:p),h.push(P),h.push(L),P.j.push(L);else for(a=c.split(uld),a.length===1?(c=5,F=kzo(e,L,c,F)):(Y=c=6,F=Object.assign({qk:32},F),F=new HB(e,L,Y,"_"+V5++,F)),h.push(F),Y=e,l=0;l<a.length;l++)Z=a[l],l%2===0?(G=g.Tr("<html>"+Z+"</html>"),G.getElementsByTagName("parsererror").length?
(V=G.createElement("span"),V.appendChild(G.createTextNode(Z))):V=G.firstChild,j4$(this,Y,L-(Y-e),c,F,l>0,V,p,h)):Y=cWj(Z)+P}JWp.lastIndex=0}}return h};
var iMC=/^NOTE/,rWh=/(?:\r\n|\r|\n){2,}/,JWp=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),uld=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.sb.sM(s6,{wA:"wvppt"});g.S(O6,g.O);
O6.prototype.wA=function(C,b,h,N){N=N||0;h=Lkd(this,C,h||0);C=[];try{for(var p=g.z(h),P=p.next();!P.done;P=p.next()){var c=P.value,e=c.trackData,L=c.MV;if(typeof e!=="string"){h=C;var Z=h.concat,Y=b,a=e,l=L,F=N;if(!TkE(a))throw Error("Invalid binary caption track data");this.j||(this.j=new Xa(F,Y));var G=this.j.wA(a,l);var V=Z.call(h,G)}else{if(e.substring(0,6)==="WEBVTT"){h=C;var q=h.concat;this.j||(this.j=new s6);var f=this.j.wA(e,L);Math.random()<.01&&g.Ri(Error("Deprecated subtitles format in web player: WebVTT"));var y=
q.call(h,f)}else{h=C;var u=h.concat;a:{Y=b;if(e[0]==="{")try{this.j||(this.j=new r5(ZMj(Y)));var K=this.j.wA(e,L);break a}catch(CW){g.ux(CW);K=[];break a}var v=g.Tr(e);if(!v||!v.firstChild){var T=Error("Invalid caption track data");T.params=e;throw T;}if(v.firstChild.tagName==="timedtext"){if(Number(v.firstChild.getAttribute("format"))===3){a=v;this.j||(this.j=new Mk(ZMj(Y),this.If));K=this.j.wA(a,L);break a}var t=Error("Unsupported subtitles format in web player (Format2)");t.params=e;throw t;}if(v.firstChild.tagName===
"transcript"){var go=Error("Unsupported subtitles format in web player (Format1)");go.params=e;throw go;}var jV=Error("Invalid caption track data");jV.params=e;throw jV;}y=u.call(h,K)}V=y}C=V}return C}catch(CW){return this.logger.j(187101178,"Captions parsing failed: "+CW.message+". "),this.clear(),[]}};
O6.prototype.clear=function(){this.j&&this.j.dispose();this.j=null};
O6.prototype.reset=function(){this.j&&this.j.reset()};
O6.prototype.wO=function(){g.O.prototype.wO.call(this);this.clear()};var BB={windowColor:"#080808",windowOpacity:0,textAlign:2,W5:7,uY:50,Dm:100,isDefault:!0,nK:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.S(vB,g.qK);g.k=vB.prototype;g.k.wO=function(){if(this.G||this.sX){var C=this.Z.Q_();C&&!C.HE()&&C.rl()}else f60(this,!1);g.qK.prototype.wO.call(this)};
g.k.nQ=function(){return this.If.D("html5_honor_caption_availabilities_in_audio_track")&&this.X!=="LIVE"&&this.X!=="SABR_LIVE"};
g.k.Fa=function(){if(this.m6)return this.G||this.sX;var C=this.getAudioTrack();if(this.nQ()){if(!C.captionTracks.length)return!1;if(!this.j)return!0}C=t90(C,g.Oa(this.If));return C==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:C==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?D3(this):o9j(this)||D3(this)?!0:Fkj(this)};
g.k.load=function(){g.qK.prototype.load.call(this);this.V=this.getAudioTrack();if(this.j)this.K&&(this.Yh.clear(),this.G?S0E(this,!0):this.player.getPresentingPlayerType()!==3&&this.j.j4(this.K,"json3",this.ob),this.G||this.sX||E6(this)||this.player.IL("captionschanged",g.P7(this.K)));else{var C;this.X==="OFFLINE"?C=new Js(this.player,this.videoData,this.getAudioTrack()):this.X==="SABR_LIVE"?C=new NQo(this.videoData.j,this.player):this.X==="LIVE"?C=new ey(this.videoData.j,this.player):this.X==="INNERTUBE"?
C=new g.AO(this.player,this.videoData,this.getAudioTrack()):C=new g.rO(this.player,this.videoData.pK,this.videoData.videoId,g.LxW(this.videoData),this.videoData.BM,this.videoData.eventId);this.j=C;g.D(this,this.j);this.j.aX(this.ob)}};
g.k.unload=function(){this.G&&this.K?S0E(this,!1):(this.rO&&g.hZ(this.rO),this.player.Sh("captions"),this.Qz=[],this.j&&this.j.HK(),this.Yh.clear(),this.KO&&this.player.A8(this.KO),this.e0());g.qK.prototype.unload.call(this);this.player.rA();this.player.IL("captionschanged",{})};
g.k.create=function(){this.Fa()&&this.load();var C;a:{var b,h,N;if(this.If.D("web_player_nitrate_promo_tooltip")&&((b=this.videoData.getPlayerResponse())==null?0:(h=b.captions)==null?0:(N=h.playerCaptionsTracklistRenderer)==null?0:N.enableTouchCaptionsNitrate)){var p,P;if(b=(C=this.videoData.getPlayerResponse())==null?void 0:(p=C.captions)==null?void 0:(P=p.playerCaptionsTracklistRenderer)==null?void 0:P.captionTracks)for(C=g.z(b),p=C.next();!p.done;p=C.next())if(p=p.value,p.kind==="asr"&&p.languageCode===
"en"){C=!0;break a}}C=!1}C&&this.Z.publish("showpromotooltip",this.J.element)};
g.k.F8=function(){var C=t90(this.player.getAudioTrack(),g.Oa(this.If));var b=C==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?WB(this,this.L):C==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&D3(this)?d5(this):o9j(this)||this.L||Fkj(this)?WB(this,this.L):D3(this)?d5(this):null;if(this.G||this.sX){var h=g.Zw(this.j.K,!0);C=[];for(var N=0;N<h.length;N++){var p=h[N],P=g.wk("TRACK");P.setAttribute("kind","subtitles");P.setAttribute("label",g.pj(p));P.setAttribute("srclang",g.jz(p));P.setAttribute("id",p.toString());
this.sX||P.setAttribute("src",this.j.YU(p,"vtt"));p===b&&P.setAttribute("default","1");C.push(P)}b=this.Z.Q_();b.Ow(C);C=b.Rb();this.sI&&this.q2.S(C.textTracks,"change",this.xzO)}else!this.K&&b&&TJ(this,b),this.player.IL("onCaptionsTrackListChanged"),this.player.Mz("onApiChange")};
g.k.xzO=function(){for(var C=this.Z.Q_().Rb().textTracks,b=null,h=0;h<C.length;h++)if(C[h].mode==="showing")a:{b=g.Zw(this.j.K,!0);for(var N=0;N<b.length;N++)if(b[N].toString()===C[h].id){b=b[N];break a}b=null}(this.loaded?this.K:null)!==b&&TJ(this,b,!0)};
g.k.L3$=function(){!this.K&&this.G||this.unload()};
g.k.rL=function(C,b,h,N){if(C){var p;zX0(this,(p=this.K)!=null?p:void 0);this.j.jG()&&(this.Qz=[],this.Z.Sh("captions"),cB(this.Df),this.Yh.reset());if(this.videoData.lF){var P;h=((P=h)!=null?P:0)+this.videoData.lF}C=this.Yh.wA(C,b,h,N);if(this.kh)for(b=g.z(C),h=b.next();!h.done;h=b.next())h=h.value,h.N=this.videoData.clientPlaybackNonce,h.Uc=this.videoData.lF;b=!this.If.D("html5_keep_caption_data_after_seek")&&(this.X==="LIVE"||this.X==="SABR_LIVE");this.player.A8(C,void 0,b);!this.L||this.sX||E6(this)||
g.qo(this.If)||g.mG(this.If)||g.X_(this.If)||this.If.Qz==="shortspage"||this.player.isInline()||(g.hZ(this.rO),C=Dee({W5:0,uY:5,Dm:5,h$:2,textAlign:0,P2:0,lang:"en"}),this.t4=[C],b=["Click "," for settings"],this.zi||(h=new g.kY(g.ft()),g.D(this,h),this.zi=h.element),h=C.end-C.start,(N=g.pj(this.K))&&this.t4.push(new $x(C.start,h,0,C.id,N)),this.t4.push(new $x(C.start,h,0,C.id,b[0]),new $x(C.start,h,0,C.id,this.zi,!0),new $x(C.start,h,0,C.id,b[1],!0)),this.player.A8(this.t4),g.C2(this.rO));!this.L||
this.sX||E6(this)||(g.Oa(this.If)?nq(this,!0):ts(this,!0),this.V&&(this.V.X=this.K),this.player.rA());this.L=!1}};
g.k.onCueRangeEnter=function(C){this.Qz.push(C);cB(this.Df)};
g.k.onCueRangeExit=function(C){g.wD(this.Qz,C);this.j instanceof ey&&this.j.J&&this.player.AR([C]);cB(this.Df)};
g.k.getCaptionWindowContainerId=function(){return this.J.element.id};
g.k.dKi=function(){m7d(this,this.t4);this.t4=null};
g.k.z4=function(){var C=this;if(!this.G$||!this.G){this.Df.stop();g.nQl(this.CO);this.Qz.sort(g.Ny);var b=this.Qz;if(this.KO){var h=g.kS(b,function(P){return this.KO.indexOf(P)===-1},this);
h.length&&(b=h)}b=g.z(b);for(h=b.next();!h.done;h=b.next())VWC(this,h.value);b=g.z(Object.entries(this.nO));var N=b.next();for(h={};!N.done;h={Qc:void 0,kd:void 0},N=b.next()){var p=g.z(N.value);N=p.next().value;p=p.next().value;h.Qc=N;h.kd=p;this.CO[h.Qc]?(h.kd.element.parentNode||(h.kd instanceof Kq||h.kd instanceof u5||g.zA(this.nO,function(P){return function(c,e){e!==P.Qc&&c.K.params.W5===P.kd.K.params.W5&&c.K.params.uY===P.kd.K.params.uY&&c.K.params.Dm===P.kd.K.params.Dm&&(c.dispose(),delete C.nO[e]);
return e===P.Qc}}(h),this),this.J.element.appendChild(h.kd.element)),h.kd.vg(this.CO[h.Qc])):(h.kd.dispose(),delete this.nO[h.Qc])}}};
g.k.EJD=function(){a6E(this,{},!0);this.player.IL("captionssettingschanged")};
g.k.SD=function(){var C=BB.nK;C={background:C.background,backgroundOpacity:C.backgroundOpacity,charEdgeStyle:C.charEdgeStyle,color:C.color,fontFamily:C.fontFamily,fontSizeIncrement:C.fontSizeIncrement,fontStyle:C.bold&&C.italic?3:C.bold?1:C.italic?2:0,textOpacity:C.textOpacity,windowColor:BB.windowColor,windowOpacity:BB.windowOpacity};var b=Nkh()||{};b.background!=null&&(C.background=b.background);b.backgroundOverride!=null&&(C.backgroundOverride=b.backgroundOverride);b.backgroundOpacity!=null&&(C.backgroundOpacity=
b.backgroundOpacity);b.backgroundOpacityOverride!=null&&(C.backgroundOpacityOverride=b.backgroundOpacityOverride);b.charEdgeStyle!=null&&(C.charEdgeStyle=b.charEdgeStyle);b.charEdgeStyleOverride!=null&&(C.charEdgeStyleOverride=b.charEdgeStyleOverride);b.color!=null&&(C.color=b.color);b.colorOverride!=null&&(C.colorOverride=b.colorOverride);b.fontFamily!=null&&(C.fontFamily=b.fontFamily);b.fontFamilyOverride!=null&&(C.fontFamilyOverride=b.fontFamilyOverride);b.fontSizeIncrement!=null&&(C.fontSizeIncrement=
b.fontSizeIncrement);b.fontSizeIncrementOverride!=null&&(C.fontSizeIncrementOverride=b.fontSizeIncrementOverride);b.fontStyle!=null&&(C.fontStyle=b.fontStyle);b.fontStyleOverride!=null&&(C.fontStyleOverride=b.fontStyleOverride);b.textOpacity!=null&&(C.textOpacity=b.textOpacity);b.textOpacityOverride!=null&&(C.textOpacityOverride=b.textOpacityOverride);b.windowColor!=null&&(C.windowColor=b.windowColor);b.windowColorOverride!=null&&(C.windowColorOverride=b.windowColorOverride);b.windowOpacity!=null&&
(C.windowOpacity=b.windowOpacity);b.windowOpacityOverride!=null&&(C.windowOpacityOverride=b.windowOpacityOverride);return C};
g.k.oO=function(C,b){var h={};Object.assign(h,Nkh());Object.assign(h,C);a6E(this,h,b);this.player.IL("captionssettingschanged")};
g.k.e0=function(){!this.G&&this.loaded&&(g.GA(this.nO,function(C,b){C.dispose();delete this.nO[b]},this),this.z4())};
g.k.X8=function(C,b){switch(C){case "fontSize":if(isNaN(b))break;C=g.cE(b,-2,4);this.oO({fontSizeIncrement:C});return C;case "reload":b&&!this.G&&TJ(this,this.K,!0);break;case "stickyLoading":b!==void 0&&this.If.J&&(g.Oa(this.If)?nq(this,!!b):ts(this,!!b));break;case "track":return q0e(this,b);case "tracklist":return this.j?g.M_(g.Zw(this.j.K,!(!b||!b.includeAsr)),function(h){return g.P7(h)}):[];
case "translationLanguages":return this.j?this.j.G.map(function(h){return Object.assign({},h)}):[];
case "sampleSubtitles":this.G||b===void 0||f60(this,!!b);break;case "sampleSubtitlesCustomized":this.G||f60(this,!!b,b);break;case "recommendedTranslationLanguages":return g.Jd();case "defaultTranslationSourceTrackIndices":return this.j?this.j.L:[]}};
g.k.getOptions=function(){var C="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.If.J&&C.push("stickyLoading");return C};
g.k.FG=function(){var C=this.K;if(this.Z.F3("captions")){if(this.If.D("html5_modify_caption_vss_logging")){var b;return(C=(b=this.videoData.iE)!=null?b:null)?{cc:g.yvS(C)}:{}}if(C)return b=C.vssId,C.translationLanguage&&b&&(b="t"+b+"."+g.jz(C)),{cc:b}}return{}};
g.k.fjo=function(){this.isSubtitlesOn()?(g.Oa(this.If)?nq(this,!1):ts(this,!1),zX0(this),this.If.D("html5_report_caption_format_change")?TJ(this,null,!0):(this.unload(),D3(this,!0)&&TJ(this,d5(this),!1))):this.Ut()};
g.k.Ut=function(){var C=E6(this)||!this.K?WB(this,!0):this.K;this.If.D("html5_report_caption_format_intent")&&C&&this.ke(C.vssId,"m");this.isSubtitlesOn()||TJ(this,E6(this)||!this.K?WB(this,!0):this.K,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.K&&!E6(this)};
g.k.eWX=function(){var C=E6(this);D3(this,C)?TJ(this,this.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.nQ()&&(this.L=!1,this.K=null,this.j&&(this.j.dispose(),this.j=null)),this.Fa()&&(C?TJ(this,WB(this,!1),!1):this.load()))};
g.k.GN=function(C){C&&(this.N2={top:C.top,right:C.right,bottom:C.bottom,left:C.left,width:1-C.left-C.right,height:1-C.top-C.bottom},this.J.element.style.top=this.N2.top*100+"%",this.J.element.style.left=this.N2.left*100+"%",this.J.element.style.width=this.N2.width*100+"%",this.J.element.style.height=this.N2.height*100+"%",this.J.element.style.position="absolute",C=MWE(this))&&(this.J.element.style.width=C.width+"px",this.J.element.style.height=C.height+"px")};
g.k.onVideoDataChange=function(C,b){C==="newdata"&&(this.videoData=b,this.loaded&&this.unload(),this.L=!1,this.K=null,this.j&&(this.j.dispose(),this.j=null,this.player.IL("captionschanged",{})),this.Fa()&&this.load())};
g.k.getAudioTrack=function(){return this.kh&&this.player.getPresentingPlayerType()===2?this.videoData.BT:this.player.getAudioTrack()};
g.k.us6=function(){var C=this.Z.Q_();C&&!C.HE()&&C.rl();this.Z.isFullscreen()?(this.G=this.m6=!0,this.loaded&&this.F8()):(this.m6=this.If.controlsType==="3",this.G=Y0D(this));TJ(this,this.K)};
g.k.Y_=function(){var C,b,h,N=(C=this.videoData.getPlayerResponse())==null?void 0:(b=C.captions)==null?void 0:(h=b.playerCaptionsTracklistRenderer)==null?void 0:h.openTranscriptCommand;N&&this.player.LO("innertubeCommand",N)};
g.k.eq=function(C,b,h){var N=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,p="";C&&(p=C.vssId,p=p.replace(N,""));var P="";C&&C.getId()&&(P=C.getId()||"");C&&C.getXtags()&&(C=C.getXtags(),C=C.replace(N,""),P=P.concat(";"+C));this.Z.eq(b?p:"",b?P:"",h)};
g.k.ke=function(C,b){C=(C||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");C.length>0&&this.Z.ke(C,b)};
g.k.d4=function(){this.j&&this.j.d4()};
g.sb.sM(vB,{z4:"smucd"});g.MK("captions",vB);})(_yt_player);
