(function(g){var window=this;'use strict';var $Ro=function(C,b){if(!Number.isFinite(C))return String(C);C=String(C);var h=C.indexOf(".");h===-1&&(h=C.length);var N=C[0]==="-"?"-":"";N&&(C=C.substring(1));return N+(0,g.zU0)("0",Math.max(0,b-h))+C},zYo=function(){return{B:"svg",
T:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},U:[{B:"path",T:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},Hbh=function(){return{B:"svg",
T:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},U:[{B:"path",T:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},MIC=function(C){typeof C==="number"?(this.date=VIj(C,0,1),zs(this,1)):g.tl(C)?(this.date=VIj(C.getFullYear(),C.getMonth(),C.getDate()),zs(this,C.getDate())):(this.date=new Date(g.Cd()),C=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),zs(this,C))},VIj=function(C,b,h){b=new Date(C,b,h);
C>=0&&C<100&&b.setFullYear(b.getFullYear()-1900);return b},zs=function(C,b){C.getDate()!=b&&C.date.setUTCHours(C.date.getUTCHours()+(C.getDate()<b?1:-1))},Hi=function(C,b){g.rY.call(this,C,{B:"div",
C:"ytp-reminder-menu",T:{role:"menu",tabindex:"-1"},U:[{B:"div",C:"ytp-reminder-menu-contents",U:[{B:"div",C:"ytp-reminder-menu-items"}]}]},100,!0);this.j=b;this.N=[];this.menuPopupRenderer=void 0;this.items=this.dO("ytp-reminder-menu-items");this.hide()},qq$=function(C){return(C.menuPopupRenderer&&C.menuPopupRenderer.items||[]).reduce(function(b,h){h&&h.menuServiceItemRenderer&&b.push(h.menuServiceItemRenderer);
return b},[])},Vy=function(C){g.n.call(this,{B:"div",
U:[{B:"button",J4:["ytp-offline-slate-button","ytp-button"],U:[{B:"div",C:"ytp-offline-slate-button-icon",BE:"{{icon}}"},{B:"div",C:"ytp-offline-slate-button-text",BE:"{{text}}"}]}]});this.Z=C;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.K=void 0;this.X=this.j=null;(this.W=this.dO("ytp-offline-slate-button"))&&this.S(this.W,"click",this.J);this.hide()},fh$=function(C,b,h){!C.toggleButtonRenderer&&b&&b.toggleButtonRenderer?C.toggleButtonRenderer=b.toggleButtonRenderer:
b&&b.toggleButtonRenderer||(C.toggleButtonRenderer=null);
!C.upcomingEventReminderButtonRenderer&&h&&g.d(h,mRD)?C.upcomingEventReminderButtonRenderer=g.d(h,mRD):h&&g.d(h,mRD)||(C.upcomingEventReminderButtonRenderer=null);Mu(C)},Mu=function(C){if(C.toggleButtonRenderer){var b=C.toggleButtonRenderer;
if(b.isToggled){var h=b.toggledText?g.lI(b.toggledText):"";C.update({text:h,icon:Aed(b.toggledIcon)})}else h=b.defaultText?g.lI(b.defaultText):"",C.update({text:h,icon:Aed(b.defaultIcon)});C.show()}else C.upcomingEventReminderButtonRenderer?(b=yeo(C))?(h=b.text?g.lI(b.text):"",C.update({text:h,icon:Aed(b.icon)}),C.show()):C.hide():C.hide()},ibD=function(C,b,h){C.X||(C.X=new g.Cr(C.Z.Y().wH));
var N={context:g.ZY(C.X.config_||g.LQ())};g.q6()&&(N.context.clientScreenNonce=g.q6());N.params=h;g.bt(C.X,b,N,{timeout:5E3,onSuccess:function(){C.upcomingEventReminderButtonRenderer&&C.K&&(C.upcomingEventReminderButtonRenderer.currentState=C.K,C.K=void 0)},
onError:function(){reh(C)},
onTimeout:function(){reh(C)}})},reh=function(C){C.toggleButtonRenderer?(C.toggleButtonRenderer.isToggled=!C.toggleButtonRenderer.isToggled,Mu(C)):C.upcomingEventReminderButtonRenderer&&(C.K=void 0,Mu(C))},Aed=function(C){if(!C)return null;
switch(C.iconType){case "NOTIFICATIONS":return zYo();case "NOTIFICATIONS_NONE":return Hbh();case "NOTIFICATIONS_ACTIVE":return g.VA();default:return null}},yeo=function(C){if(!C.upcomingEventReminderButtonRenderer)return null;
var b=C.K||C.upcomingEventReminderButtonRenderer.currentState;C=g.z(C.upcomingEventReminderButtonRenderer.states||[]);for(var h=C.next();!h.done;h=C.next())if((h=g.d(h.value,JeU))&&h.state===b&&h.button&&g.d(h.button,g.Aa))return g.d(h.button,g.Aa);return null},uXe=function(C){g.n.call(this,{B:"div",
C:"ytp-offline-slate",U:[{B:"div",C:"ytp-offline-slate-background"},{B:"div",C:"ytp-offline-slate-bar",U:[{B:"span",C:"ytp-offline-slate-icon",U:[{B:"svg",T:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},U:[{B:"path",T:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{B:"circle",T:{cx:"12",cy:"12",r:"3"}}]}]},{B:"span",C:"ytp-offline-slate-messages",U:[{B:"div",C:"ytp-offline-slate-main-text",T:{"aria-label":"{{label}}"},BE:"{{mainText}}"},{B:"div",C:"ytp-offline-slate-subtitle-text",BE:"{{subtitleText}}"}]},{B:"span",C:"ytp-offline-slate-buttons"}]},{B:"button",J4:["ytp-offline-slate-close-button","ytp-button"],U:[g.Sv()]},{B:"button",J4:["ytp-offline-slate-open-button","ytp-button"],U:[g.GY()]}]});var b=this;this.api=C;this.j=this.K=null;this.background=this.dO("ytp-offline-slate-background");
this.N=this.dO("ytp-offline-slate-bar");this.W=new g.wl(function(){g.j6(b.N,"ytp-offline-slate-bar-fade")},15E3);
this.J=!1;this.X=new g.wl(function(){g.j6(b.element,"ytp-offline-slate-collapsed")},15E3);
g.D(this,this.X);g.D(this,this.W);this.countdownTimer=new g.wl(this.dX,1E3,this);this.S(C,"presentingplayerstatechange",this.sP);this.S(C,"livestatedata",this.l$);this.S(this.dO("ytp-offline-slate-close-button"),"click",function(){g.j6(b.element,"ytp-offline-slate-collapsed")});
this.S(this.dO("ytp-offline-slate-open-button"),"click",function(){g.kb(b.element,"ytp-offline-slate-collapsed")});
this.hide();C=this.getVideoData();C.getPlayerResponse()&&(C=C.getPlayerResponse().playabilityStatus)&&this.l$(C);C=this.api.getPresentingPlayerType()===8&&!this.getVideoData().JC;var h=this.api.getPresentingPlayerType()===8;g.L2(this.element,"ytp-offline-slate-premiere-trailer",C);g.L2(this.element,"ytp-offline-slate-hide-background",h)},RYE=function(C,b,h){if(b){var N=b.subtitleText!=null?g.lI(b.subtitleText):"";
h=h?h:b.mainText!=null?g.lI(b.mainText):"";var p,P,c,e;b=(e=(p=b.mainText)==null?void 0:(P=p.accessibility)==null?void 0:(c=P.accessibilityData)==null?void 0:c.label)!=null?e:h;C.update({mainText:h,subtitleText:N,label:b});g.L2(C.element,"ytp-offline-slate-single-text-line",!N);g.L2(C.N,"ytp-offline-slate-bar-hidden",!h&&!N)}},qu=function(C,b){var h=(0,g.fB)();
this.module="heartbeat";this.trigger=C;this.j=b;this.N=h},ObU=function(C){g.qK.call(this,C);
var b=this;this.J=!1;this.L=0;this.G=!1;this.K=new g.wl(function(){Q9e(b)},0);
this.j=this.heartbeatParams=null;this.X=!1;this.W=new g.HP(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.KO=new g.Cr(void 0);this.attestationResponse=Promise.resolve(void 0);this.V=Promise.resolve(void 0);this.utcOffsetMinutes=-(new MIC).getTimezoneOffset();this.N=new g.Jm(this);g.D(this,this.K);g.D(this,this.N);UR$(this);XtD(this);this.N.S(C,"heartbeatparams",this.hD);this.N.S(C,"presentingplayerstatechange",this.YZ);this.N.S(C,"videoplayerreset",this.mj);this.N.S(C,g.gL("heartbeat"),
this.onCueRangeEnter);this.X&&this.j&&Kre(this,void 0,this.j);var h=new g.hk(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),N=new g.hk(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});C.A8([h,N]);s9d(this)},s9d=function(C){var b=C.getVideoData();
!b.D("use_rta_for_player")&&b.Zu&&(b=b.botguardData)&&g.fx(b,C.player.Y())},vE0=function(C){var b,h;
return g.R(function(N){if(N.j==1)return g.J(N,g.qxK(),2);if(!N.K)return C.sequenceNumber>=3?N.return({error:"ATTESTATION_ERROR_VM_INTERNAL_ERROR"}):N.return(void 0);b=C.getVideoData();h={};return N.return(g.M8l((h.cpn=b.clientPlaybackNonce,h.encryptedVideoId=b.videoId||"",h),1500))})},UR$=function(C){var b=C.getVideoData();
if(b.Zu)if(b.D("use_rta_for_player"))C.attestationResponse=vE0(C);else if(b=new g.z5_(b),g.Vp.isInitialized()||C.sequenceNumber>=3){var h=Promise,N=h.resolve,p=null;if(b.videoData.H4){var P=g.Hkl(b);if(P){p={};var c={};P=P.split("&");P=g.z(P);for(var e=P.next();!e.done;e=P.next())e=e.value.split("="),e.length===2&&(c[e[0]]=e[1]);c.r1a&&(p.webResponse=c.r1a);c.r1c&&(p.error=DR$[Number(c.r1c)]);p.challenge=b.videoData.H4}}C.attestationResponse=N.call(h,p||void 0)}},dRj=function(C){var b=C.getVideoData();
if(!g.L6(C.getVideoData())||b.Ev)return!1;if(b.G){C=b.G.flavor==="playready"&&b.D("html5_innertube_heartbeats_for_playready");var h=b.G.flavor==="widevine"&&b.D("html5_innertube_heartbeats_for_widevine");b=g.yZ(b.G)&&b.D("html5_innertube_heartbeats_for_fairplay");return!(C||h||b)}return!0},Wr0=function(C){if(dRj(C))return!!C.heartbeatParams;
var b=C.getVideoData();return!g.L6(C.getVideoData())||b.n5||b.Tb?!!b.heartbeatToken:!1},mE=function(C,b){if(!C.K.isActive()&&C.J){var h=C.getVideoData();
if(Wr0(C)||h.isLivePlayback){if(b===void 0)if(C.G)if(C.X)b=7500;else{var N;b=((N=C.heartbeatParams)==null?0:N.interval)?C.heartbeatParams.interval*1E3:C.getVideoData().uv||6E4}else b=1E3;C.K.start(b)}}},Tto=function(C,b,h){b.xo&&(h=g.Dh(h,{internalipoverride:b.xo}));
var N={cpn:b.clientPlaybackNonce};b.contextParams&&(N.context_params=b.contextParams);b.sI&&(N.kpt=b.sI);h=g.Dh(h,N);g.mt(h,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(p){if(!C.K.isActive()&&fH(C)){C.W.reset();C.sequenceNumber++;p=p.responseText;var P=EE$(p);if(P){C.player.LO("onHeartbeat",P);var c=P.status==="ok"?P.stop_heartbeat?2:0:P.status==="stop"?1:P.status==="live_stream_offline"?0:-1}else c=(c=p.match(nEE))?c[1]==="0"?0:1:-1;tId(C,void 0,P,p,c)}},
onError:function(p){fH(C)&&Ab(C,!0,"net-"+p.status)},
onTimeout:function(){fH(C)&&Ab(C,!0,"timeout")},
withCredentials:!0})},Q9e=function(C){var b,h;
g.R(function(N){b=C.player.Y();h=C.getVideoData();if(!fH(C))return N.return();if(dRj(C))return Btp(C,b,h),N.WE(0);UR$(C);return g.J(N,Ihh(C,b,h),0)})},Btp=function(C,b,h){var N;
if((N=C.heartbeatParams)!=null&&N.url){var p=g.Dh(C.heartbeatParams.url,{request_id:g.rKo()});h.N2&&(p=g.Dh(p,{vvt:h.N2}),h.mdxEnvironment&&(p=g.Dh(p,{mdx_environment:h.mdxEnvironment})));g.Ta(b,h.oauthToken).then(function(P){P&&(p=g.Dh(p,{access_token:P}));Tto(C,h,p)})}},fH=function(C){var b=C.getVideoData();
return C.player.getPresentingPlayerType()===3||g.B(C.player.getPlayerStateObject(C.getPlayerType()),4)?!1:Wr0(C)||b.isLivePlayback?!0:(yy(C),!1)},Ihh=function(C,b,h){var N,p,P,c,e,L,Z,Y,a,l,F,G,V,q,f,y,u,K,v,T;
return g.R(function(t){if(t.j==1)return N="player/heartbeat",P={videoId:h.videoId,sequenceNumber:C.sequenceNumber,heartbeatServerData:(p=C.N2)!=null?p:h.heartbeatServerData},C.V=C.attestationResponse,h.Zu?g.J(t,C.V,3):t.WE(2);t.j!=2&&(P.attestationResponse=t.K);c=g.BT(h);L=(e=c.client)!=null?e:{};L.utcOffsetMinutes=C.utcOffsetMinutes;P.context=c;P.cpn=h.clientPlaybackNonce;if(Z=typeof Intl!=="undefined"?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)L.timeZone=Z;Y={heartbeatChecks:[]};
if(a=h.getPlayerResponse())h.heartbeatToken&&(P.heartbeatToken=h.heartbeatToken),(l=a.playabilityStatus)&&(F=l.liveStreamability)&&F.liveStreamabilityRenderer&&Y.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");h.heartbeatToken&&Y.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");g.Va(b)&&(Y.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED"),G=xRh(C),V={},G!==null&&(V.clientPlayerPositionUtcMillis=G),f=(q=C.player.N8())==null?void 0:g.Xq(q),u=((y=f)==null?void 0:y.freePreviewWatchedDuration)||
0,u>0&&(V.freePreviewWatchedDuration={seconds:""+u}),Y.unpluggedParams=V);P.heartbeatRequestParams=Y;h.isLivePlayback?(K=xRh(C),K!==null&&(P.playbackState||(P.playbackState={}),P.playbackState.playbackPosition={utcTimeMillis:K})):b.D("enable_heartbeat_vod_playback_position")&&(v=wte(C),v!==null&&(P.playbackState||(P.playbackState={}),P.playbackState.playbackPosition={streamTimeMillis:v}));C.player.publish("heartbeatRequest",P);T={timeout:3E4,onSuccess:function(go){if(!C.K.isActive()&&fH(C)){var jV=
C.getVideoData(),CW=jV.Zu&&C.V==null,W;jV.Zu=!((W=go.heartbeatAttestationConfig)==null||!W.requiresAttestation)||CW;CW=go.playabilityStatus;W=JSON.stringify(CW)||"{}";go.authenticationMismatch&&C.player.jp("authshear",{});var w=-1;var H=go.playabilityStatus;H&&(C.player.LO("onHeartbeat",H),H.status==="OK"?w=go.stopHeartbeat?2:0:H.status==="UNPLAYABLE"?w=1:H.status==="LIVE_STREAM_OFFLINE"&&(w=0));C.sequenceNumber&&w===-1||C.W.reset();C.sequenceNumber++;go.heartbeatServerData&&(C.N2=go.heartbeatServerData);
jV.XM=go;(H=go.playerCueRangeSet)&&g.OF(jV,H);go.playerCueRanges&&go.playerCueRanges.length>0&&(jV.cueRanges=go.playerCueRanges);var E,Ol;((E=go.progressBarConfig)==null?0:E.progressBarStartPosition)&&((Ol=go.progressBarConfig)==null?0:Ol.progressBarEndPosition)&&(jV.progressBarStartPosition=go.progressBarConfig.progressBarStartPosition,jV.progressBarEndPosition=go.progressBarConfig.progressBarEndPosition);jV.compositeLiveIngestionOffsetToken=go.compositeLiveIngestionOffsetToken;go.compositeLiveStatusToken!==
jV.compositeLiveStatusToken&&(jV.compositeLiveStatusToken=go.compositeLiveStatusToken);jV.publish("dataupdated");tId(C,go,CW,W,w)}},
onError:function(go){fH(C)&&Ab(C,!0,"net-"+go.status)},
onTimeout:function(){fH(C)&&Ab(C,!0,"timeout")}};
g.Ta(b,g.Uv(h)).then(function(go){go&&(T.FD="Bearer "+go);g.bt(C.KO,N,P,T)});
g.SV(t)})},tId=function(C,b,h,N,p){p===-1?(h="decode "+g.$s(N,3),Ab(C,!1,h)):p===2?(yy(C),C.G=!0):(C.L=0,C.K.stop(),p===1?(C.G=!1,h&&h.errorCode==="PLAYABILITY_ERROR_CODE_EMBARGOED"&&C.player.eX(!0),p="pe."+(h==null?void 0:h.errorCode)+";ps."+(h==null?void 0:h.status),C.player.u3("heartbeat.stop",2,C.WL(N),p),g.k1("heartbeatActionPlayerHalted",CYo(h)),(b==null?0:b.videoTransitionEndpoint)&&h&&(b=b.videoTransitionEndpoint,(N=g.d(b,g.Da))&&bnI(C,N,h,{itct:b==null?void 0:b.clickTrackingParams}))):(C.G=
!0,N=0,C.X&&h&&(N=Kre(C,b,h),C.player.publish("livestatedata",h)),N?mE(C,N):mE(C)))},Kre=function(C,b,h){var N=h.liveStreamability&&h.liveStreamability.liveStreamabilityRenderer,p=!(!N||!(N.switchStreamsImmediately||N.transitionTiming&&N.transitionTiming==="STREAM_TRANSITION_TIMING_IMMEDIATELY"));
b=hGE(C,b,N);var P=C.getVideoData(),c=C.player.getPlayerStateObject(C.getPlayerType()),e=c.isPlaying()&&!g.Gg(P)&&!C.player.isAtLiveHead(C.getPlayerType());if(P.Y().tZ()){var L,Z=((L=C.player.Q_())==null?void 0:L.jf())||{};Z.status=h.status||"";Z.dvr=""+ +e;Z["switch"]=""+ +p;Z.ended=""+ +!(!N||!N.displayEndscreen);C.player.jp("heartbeat",Z)}if(e&&!p)return b;p=N&&N.streamTransitionEndpoint&&g.d(N.streamTransitionEndpoint,g.Da);if((N&&N.transitionTiming)==="STREAM_TRANSITION_TIMING_AT_STREAM_END")C.getVideoData().transitionEndpointAtEndOfStream=
p;else if(p&&bnI(C,p,h))return b;if(h.status.toUpperCase()==="OK"){p=N&&N.broadcastId;L=C.j&&C.j.liveStreamability&&C.j.liveStreamability.liveStreamabilityRenderer&&C.j.liveStreamability.liveStreamabilityRenderer.broadcastId;e=p!==L&&p!=null;if(!g.l4(P)||e){var Y={video_id:P.videoId};P.cV&&(Y.is_live_destination="1");C.player.D("web_player_heartbeat_request_watch_next")||(Y.disable_watch_next=!0,Y.raw_watch_next_response=P.getWatchNextResponse());Y.autonav_state=P.autonavState;Y.oauth_token=P.oauthToken;
Y.force_gvi=P.Rn;Y.mC=P.mC;P.W&&(Y.vss_credentials_token=P.W,Y.vss_credentials_token_type=P.KS);P.N2&&(Y.vvt=P.N2);N=void 0;g.l4(P)?e&&(N=new qu("broadcastIdChanged",L+","+p),C.SR("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",h)):(p&&(N=new qu("formatsReceived",""+p)),C.SR("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",h));C.player.loadVideoByPlayerVars(Y,void 0,void 0,void 0,N);return b}C.player.HL("heartbeat",
C.getPlayerType())}N&&N.displayEndscreen&&(C.offlineSlate?(C=C.offlineSlate,C.J=!0,C.Bb&&C.api.Il()):c.isBuffering()&&(P=((Y=C.player.Q_())==null?void 0:Y.jf())||{},C.player.jp("hbse",P,!0),C.player.Il(),C.player.LO("onLiveMediaEnded",h)));return b},hGE=function(C,b,h){return C.player.D("web_player_use_heartbeat_poll_delay_ms")&&(C=Number(b==null?void 0:b.pollDelayMs))?C:(h=Number(h==null?void 0:h.pollDelayMs))?h:0},Ab=function(C,b,h){var N=C.player.Y();
if(!C.K.isActive()){C.K.stop();C.L++;var p=b?"heartbeat.net":"heartbeat.servererror";var P=C.getVideoData();if(P.YI||b&&!g.L6(C.getVideoData())&&!Wr0(C)&&P.isLivePlayback)P=!1;else{var c,e;((e=C.heartbeatParams)==null?0:e.retries)?c=C.heartbeatParams.retries:c=P.Sk||5;P=C.L>=c}P?(g.k1("heartbeatActionPlayerHalted",b?{enforcedPolicyToHaltOnNetworkFailure:!0}:CYo()),(b=C.getVideoData())&&b.isLivePlayback?C.player.u3(p,1,"Video playback interrupted. Please try again.",h):C.player.u3(p,1,"Sorry, there was an error licensing this video.",
h)):(N.D("html5_report_non_fatal_heartbeat_error")&&C.player.S4(p,{msg:h}),mE(C,C.W.getValue()),g.VD(C.W))}},CYo=function(C){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
C&&(b.serializedServerContext=C.additionalLoggingData);return b},yy=function(C){C.L=0;
C.K.stop();C.G=!1;C.sequenceNumber=0},XtD=function(C){var b=C.getVideoData(),h=C.player.Y();
if(b.isLivePlayback)if(g.nA(h.G)){C.X=!0;C.J=!0;if(!g.qo(h)||g.Va(h))C.offlineSlate=new uXe(C.player),g.D(C,C.offlineSlate),g.MC(C.player,C.offlineSlate.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(C.j=b.playabilityStatus);var N;((N=C.j)==null?void 0:N.status)!=="UNPLAYABLE"&&(C.j?(N=hGE(C,void 0,C.j.liveStreamability&&C.j.liveStreamability.liveStreamabilityRenderer))?mE(C,N):mE(C,7500):mE(C,1E3))}else C.player.u3("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");
else g.Id(b.q2,"heartbeat")&&C.player.HL("heartbeat",C.getPlayerType())},bnI=function(C,b,h,N){var p=b&&b.videoId;
return p?(C.player.fk(p,Object.assign({},{autonav:"1"},N||{}),void 0,!0,!0,b,g.Uv(C.getVideoData())),C.SR("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",h),!0):!1},xRh=function(C){return(C=C.player.getProgressState(C.getPlayerType()).ingestionTime)&&isFinite(C)?""+Math.floor(C*1E3):null},wte=function(C){return(C=C.player.getCurrentTime(C.getPlayerType()))&&isFinite(C)?""+Math.floor(C*1E3):null},EE$=function(C){try{var b=JSON.parse(C);
return b!=null?b:void 0}catch(h){}},NHd={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5},g3D=NHd;g3D=NHd;
var DR$=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],paE={300:"STREAMING_DEVICES_QUOTA_PER_24H_EXCEEDED",301:"ALREADY_PINNED_ON_A_DEVICE",303:"STOPPED_BY_ANOTHER_PLAYBACK",304:"TOO_MANY_STREAMS_PER_USER",305:"TOO_MANY_STREAMS_PER_ENTITLEMENT",400:"VIDEO_NOT_FOUND",401:"GEO_FAILURE",402:"STREAMING_NOT_ALLOWED",403:"UNSUPPORTED_DEVICE",405:"VIDEO_FORBIDDEN",500:"PURCHASE_NOT_FOUND",
501:"RENTAL_EXPIRED",502:"PURCHASE_REFUNDED",5E3:"BAD_REQUEST",5001:"CGI_PARAMS_MISSING",5002:"CGI_PARAMS_MALFORMED",5100:"AUTHENTICATION_MISSING",5101:"AUTHENTICATION_MALFORMED",5102:"AUTHENTICATION_EXPIRED",5200:"CAST_TOKEN_MALFORMED",5201:"CAST_TOKEN_EXPIRED",5202:"CAST_TOKEN_FAILED",5203:"CAST_SESSION_VIDEO_MISMATCHED",5204:"CAST_SESSION_DEVICE_MISMATCHED",6E3:"INVALID_DRM_MESSAGE",7E3:"SERVER_ERROR",8E3:"RETRYABLE_ERROR"};g.k=MIC.prototype;g.k.N_=g3D.FIRSTDAYOFWEEK;g.k.Xv=g3D.FIRSTWEEKCUTOFFDAY;
g.k.clone=function(){var C=new MIC(this.date);C.N_=this.N_;C.Xv=this.Xv;return C};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getYear=function(){return this.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.getTime=function(){return this.date.getTime()};
g.k.getDay=function(){return this.date.getDay()};
g.k.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.k.getUTCMonth=function(){return this.date.getUTCMonth()};
g.k.getUTCDate=function(){return this.date.getUTCDate()};
g.k.getUTCDay=function(){return this.date.getDay()};
g.k.getUTCHours=function(){return this.date.getUTCHours()};
g.k.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.k.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.k.set=function(C){this.date=new Date(C.getFullYear(),C.getMonth(),C.getDate())};
g.k.setFullYear=function(C){this.date.setFullYear(C)};
g.k.setYear=function(C){this.setFullYear(C)};
g.k.setMonth=function(C){this.date.setMonth(C)};
g.k.setDate=function(C){this.date.setDate(C)};
g.k.setTime=function(C){this.date.setTime(C)};
g.k.setUTCFullYear=function(C){this.date.setUTCFullYear(C)};
g.k.setUTCMonth=function(C){this.date.setUTCMonth(C)};
g.k.setUTCDate=function(C){this.date.setUTCDate(C)};
g.k.add=function(C){if(C.years||C.months){var b=this.getMonth()+C.months+C.years*12,h=this.getYear()+Math.floor(b/12);b%=12;b<0&&(b+=12);a:{switch(b){case 1:var N=h%4!=0||h%100==0&&h%400!=0?28:29;break a;case 5:case 8:case 10:case 3:N=30;break a}N=31}N=Math.min(N,this.getDate());this.setDate(1);this.setFullYear(h);this.setMonth(b);this.setDate(N)}C.days&&(h=this.getYear(),b=h>=0&&h<=99?-1900:0,C=new Date((new Date(h,this.getMonth(),this.getDate(),12)).getTime()+C.days*864E5),this.setDate(1),this.setFullYear(C.getFullYear()+
b),this.setMonth(C.getMonth()),this.setDate(C.getDate()),zs(this,C.getDate()))};
g.k.y8=function(C){return!(!C||this.getYear()!=C.getYear()||this.getMonth()!=C.getMonth()||this.getDate()!=C.getDate())};
g.k.toString=function(){var C=this.getFullYear(),b=C<0?"-":C>=1E4?"+":"";return[b+$Ro(Math.abs(C),b?6:4),$Ro(this.getMonth()+1,2),$Ro(this.getDate(),2)].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};var PYD=new g.fe("addUpcomingEventReminderEndpoint");var j0C=new g.fe("removeUpcomingEventReminderEndpoint");var cF$=new g.fe("updateUpcomingEventReminderButtonStateCommand");var mRD=new g.fe("upcomingEventReminderButtonRenderer"),JeU=new g.fe("upcomingEventReminderButtonStateRenderer");g.S(Hi,g.rY);
Hi.prototype.updateMenuItems=function(){var C=this,b=qq$(this),h=0;h=0;for(var N={};h<b.length;N={hP:void 0},h++){var p=this.N[h];p||(p=new g.n({B:"div",C:"ytp-reminder-menu-item",T:{role:"menuitem",tabindex:"0"},U:[{B:"div",C:"ytp-reminder-menu-item-icon",BE:"{{icon}}"},{B:"div",C:"ytp-reminder-menu-item-label",BE:"{{text}}"}]}),N.hP=h,p.listen("click",function(c){return function(){var e=c.hP;C.QV();e=qq$(C)[e];C.publish("reminderMenuItemClicked",e.serviceEndpoint||e.command)}}(N)),p.Gi(this.items),
this.N[h]=p);
var P=b[h];N=null;switch(P.icon&&P.icon.iconType){case "NOTIFICATIONS":N=zYo();break;case "NOTIFICATIONS_NONE":N=Hbh();break;case "NOTIFICATIONS_ACTIVE":N=g.VA()}P=P.text?g.lI(P.text):"";p.update({icon:N,text:P})}for(;h<this.N.length;)this.N.pop().dispose();h===0?this.QV():this.mE(this.j)};
Hi.prototype.hide=function(){this.j&&this.j.removeAttribute("aria-haspopup");g.rY.prototype.hide.call(this)};
Hi.prototype.show=function(){this.j&&this.j.setAttribute("aria-haspopup","true");g.rY.prototype.show.call(this)};
Hi.prototype.wO=function(){g.eD(this.N);g.rY.prototype.wO.call(this)};g.S(Vy,g.n);
Vy.prototype.J=function(){if(this.toggleButtonRenderer){var C=this.toggleButtonRenderer;C.isToggled?this.N(C.toggledServiceEndpoint):this.N(C.defaultServiceEndpoint);C.isToggled=!C.isToggled;Mu(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.j&&this.j.Bb)this.j.QV();else{var b=yeo(this);b&&this.N(b.serviceEndpoint||b.command);b=((C=g.d(b==null?void 0:b.command,g.ox))==null?void 0:C.commands)||[];a:{C=g.z(b);for(var h=C.next();!h.done;h=C.next()){var N=b=void 0;if(h=(b=g.d(h.value,g.u0d))==
null?void 0:(N=b.popup)==null?void 0:N.menuPopupRenderer){C=h;break a}}C=void 0}this.j||(this.j=new Hi(this.Z,this.W),this.j.Gi(this.element),g.D(this,this.j),this.j.subscribe("reminderMenuItemClicked",this.N,this));b=this.j;b.menuPopupRenderer=C;b.updateMenuItems()}};
Vy.prototype.N=function(C){var b=g.d(C,PYD),h=g.d(C,j0C);if(C&&(b||h)){if(b){var N=b;var p="notification/add_upcoming_event_reminder"}else h&&(N=h,p="notification/remove_upcoming_event_reminder");if(p&&N&&N.params)for(ibD(this,p,N.params),C=g.z(N.commands||[]),b=C.next();!b.done;b=C.next())if((b=b.value)&&g.d(b,cF$)){this.K=g.d(b,cF$).state;Mu(this);break}}};g.S(uXe,g.n);g.k=uXe.prototype;g.k.getPlayerType=function(){if(this.api.getPresentingPlayerType()===8)return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.l$=function(C){var b,h,N=C==null?void 0:(b=C.liveStreamability)==null?void 0:(h=b.liveStreamabilityRenderer)==null?void 0:h.offlineSlate;if(N){this.K=C;b=N.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.dX():RYE(this,b);var p,P,c,e;if(h=C==null?void 0:(p=C.liveStreamability)==null?void 0:(P=p.liveStreamabilityRenderer)==null?void 0:(c=P.offlineSlate)==null?void 0:(e=c.liveStreamOfflineSlateRenderer)==null?void 0:e.thumbnail){p=0;P=null;c=h.thumbnails;for(e=0;e<c.length;e++)c[e].width>
p&&(p=c[e].width||0,P=c[e].url);P&&(this.background.style.backgroundImage="url("+P+")")}else this.background.style.backgroundImage="";b.actionButtons||b.reminderButton?(this.j||(this.j=new Vy(this.api),this.j.Gi(this.dO("ytp-offline-slate-buttons")),g.D(this,this.j)),fh$(this.j,b.actionButtons&&b.actionButtons[0],b.reminderButton)):this.j&&fh$(this.j,null,null);this.K=C}else this.K=null;this.sP()};
g.k.sP=function(C){if(this.api.getPresentingPlayerType()===8)var b=!0;else{var h=this.api.getPlayerStateObject(),N=this.getVideoData();b=N.isLivePlayback&&(h.isBuffering()||g.B(h,2)||g.B(h,64));var p=N.autonavState===2&&g.B(h,2);h=h.isPlaying()&&!g.Gg(N)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!h&&!p}b&&this.K?this.Bb?(C==null?0:g.ax(C,2))&&!this.getVideoData().JC&&(g.kb(this.element,"ytp-offline-slate-collapsed"),this.X.stop(),g.kb(this.N,"ytp-offline-slate-bar-fade"),this.W.start()):(this.show(),
this.X.start(),this.api.publish("offlineslatestatechange"),this.J&&this.api.Il()):this.Bb&&(this.hide(),this.api.publish("offlineslatestatechange"))};
g.k.dX=function(){var C,b,h,N,p=(C=this.K)==null?void 0:(b=C.liveStreamability)==null?void 0:(h=b.liveStreamabilityRenderer)==null?void 0:(N=h.offlineSlate)==null?void 0:N.liveStreamOfflineSlateRenderer;p&&(C=Math.floor(g.Cd()/1E3),b=p.canShowCountdown&&Number(p.scheduledStartTime),!b||b<=C?(RYE(this,p),this.countdownTimer.stop()):(RYE(this,p,g.Vt(b-C)),g.C2(this.countdownTimer)))};
g.k.wO=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.n.prototype.wO.call(this)};qu.prototype.K=function(C){return this.trigger&&C.trigger?this.module===C.module&&this.trigger===C.trigger&&this.j===C.j:!1};
qu.prototype.isExpired=function(){return(0,g.fB)()-this.N>6E4};
qu.prototype.toString=function(){return this.module+":"+this.trigger+":"+this.j};g.S(ObU,g.qK);g.k=ObU.prototype;g.k.wO=function(){yy(this);this.player.Sh("heartbeat");g.qK.prototype.wO.call(this)};
g.k.onCueRangeEnter=function(){this.J=!0;mE(this,2E3)};
g.k.hD=function(C){this.heartbeatParams=C;mE(this,2E3)};
g.k.YZ=function(C){var b;this.player.getPresentingPlayerType()!==8&&((b=this.j)==null?void 0:b.status)!=="UNPLAYABLE"&&(g.B(C.state,2)||g.B(C.state,64)?(yy(this),this.X&&(this.J=!0,mE(this,1E3))):(g.B(C.state,1)||g.B(C.state,8))&&mE(this,2E3))};
g.k.mj=function(){this.player.getPresentingPlayerType()!==3&&mE(this,2E3)};
g.k.getPlayerType=function(){if(this.player.getPresentingPlayerType()===8)return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.Aj=function(C){switch(C){case 4:case 3:return!1}return!0};
g.k.SR=function(C,b,h){C={trigger:C,reason:b};h&&(C.serializedServerContext=h.additionalLoggingData);g.k1("heartbeatActionPlayerTransitioned",C)};
g.k.WL=function(C){var b="LICENSE",h=EE$(C);if(h)return h.reason||g.tO[b]||"";if(C=C.match(nEE))if(C=Number(C[1]))b=(b=paE[C.toString()])?b:"LICENSE";return g.tO[b]||""};
g.k.kW=function(){return!!this.offlineSlate&&this.offlineSlate.Bb};
var nEE=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.MK("heartbeat",ObU);})(_yt_player);
